/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== indice.sql ==================
static const unsigned char temp_binary_data_1[] =
"-- MATRIZ \xe2\x80\x94 banco de \xc3\xadndice (indice.sqlite)\n"
"--\n"
"-- Camada paralela e descart\xc3\xa1vel (P2). Tudo aqui pode ser apagado e\n"
"-- reconstru\xc3\xad""do a qualquer momento sem perda de informa\xc3\xa7\xc3\xa3o catalogr\xc3\xa1""fica \xe2\x80\x94\n"
"-- nenhuma tabela deste arquivo \xc3\xa9 referenciada por FOREIGN KEY a partir de\n"
"-- registro.sqlite, e o inverso (item_id, arquivo_id) \xc3\xa9 s\xc3\xb3 uma refer\xc3\xaancia\n"
"-- solta em TEXT, resolvida em tempo de consulta pela aplica\xc3\xa7\xc3\xa3o.\n"
"--\n"
"-- Em todo registro gerado por modelo: modelo, vers\xc3\xa3o e data de processamento\n"
"-- (P3). Nada aqui \xc3\xa9 \"decis\xc3\xa3o\" \xe2\x80\x94 \xc3\xa9 sugest\xc3\xa3o at\xc3\xa9 o operador confirmar, e nesse\n"
"-- momento a aplica\xc3\xa7\xc3\xa3o copia o valor para item_campo em registro.sqlite.\n"
"\n"
"PRAGMA journal_mode = WAL;\n"
"\n"
"CREATE TABLE IF NOT EXISTS schema_info (\n"
"    chave   TEXT PRIMARY KEY,\n"
"    valor   TEXT NOT NULL\n"
");\n"
"INSERT OR IGNORE INTO schema_info (chave, valor) VALUES ('versao_schema', '1');\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Fila de processamento \xe2\x80\x94 retom\xc3\xa1vel, com progresso por item (\xc2\xa7""7.2 est\xc3\xa1gio 3)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS fila_processamento (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT,\n"
"    tipo_tarefa     TEXT NOT NULL, -- 'embedding_clip' | 'transcricao' | 'ocr' | 'rosto' | 'fingerprint' | 'phash' | 'bpm_tonalidade' | 'qualidade_imagem' | 'corte_cena' | 'diarizacao'\n"
"    status          TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_progresso', 'concluido', 'erro')),\n"
"    progresso       REAL NOT NULL DEFAULT 0 CHECK (progresso >= 0 AND progresso <= 1),\n"
"    erro_mensagem   TEXT,\n"
"    iniciado_em     TEXT,\n"
"    concluido_em    TEXT,\n"
"    criado_em       TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_fila_status ON fila_processamento(status);\n"
"CREATE INDEX IF NOT EXISTS idx_fila_item ON fila_processamento(item_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Miniatura e keyframe \xe2\x80\x94 miniatura de imagem/v\xc3\xad""deo e faixa de keyframes do\n"
"-- v\xc3\xad""deo na tira de diagn\xc3\xb3stico (\xc2\xa7""7.2 est\xc3\xa1gio 1, \xc2\xa7""11.3). caminho_relativo \xc3\xa9\n"
"-- relativo \xc3\xa0 pasta do projeto, dentro de .indice-cache/ \xe2\x80\x94 puro cache visual,\n"
"-- reconstru\xc3\xadvel a qualquer momento a partir do arquivo original.\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS miniatura (\n"
"    id                  TEXT PRIMARY KEY,\n"
"    item_id             TEXT NOT NULL,\n"
"    arquivo_id          TEXT NOT NULL,\n"
"    tipo                TEXT NOT NULL CHECK (tipo IN ('miniatura', 'keyframe')),\n"
"    tempo_ref           REAL,           -- instante do frame; s\xc3\xb3 para tipo='keyframe'\n"
"    caminho_relativo    TEXT NOT NULL,\n"
"    largura             INTEGER,\n"
"    altura              INTEGER,\n"
"    gerado_em           TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_miniatura_arquivo ON miniatura(arquivo_id);\n"
"CREATE INDEX IF NOT EXISTS idx_miniatura_item ON miniatura(item_id, tipo);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Forma de onda \xe2\x80\x94 peaks pr\xc3\xa9-calculados pra faixa \"N\xc3\xadvel\" da tira de\n"
"-- diagn\xc3\xb3stico (\xc2\xa7""11.3). Downmix mono (a fase L/R \xc3\xa9 QC de captura, Etapa 5 \xe2\x80\x94\n"
"-- escopo diferente). peaks \xc3\xa9 BLOB de pares float32 [min,max] por bucket.\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS forma_onda (\n"
"    id                  TEXT PRIMARY KEY,\n"
"    item_id             TEXT NOT NULL,\n"
"    arquivo_id          TEXT NOT NULL UNIQUE,\n"
"    duracao_segundos    REAL NOT NULL,\n"
"    buckets_por_segundo REAL NOT NULL,\n"
"    peaks               BLOB NOT NULL,\n"
"    gerado_em           TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_forma_onda_item ON forma_onda(item_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Embeddings \xe2\x80\x94 CLIP de imagem/keyframe e de texto, espa\xc3\xa7o \xc3\xbanico de busca (\xc2\xa7""9.1)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS embedding (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT,\n"
"    tipo            TEXT NOT NULL CHECK (tipo IN ('imagem', 'keyframe', 'texto')),\n"
"    tempo_ref       REAL,           -- instante do keyframe, quando aplic\xc3\xa1vel\n"
"    vetor           BLOB NOT NULL,  -- float32 empacotado\n"
"    dimensao        INTEGER NOT NULL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_embedding_item ON embedding(item_id);\n"
"CREATE INDEX IF NOT EXISTS idx_embedding_tipo ON embedding(tipo);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Rostos e vozes \xe2\x80\x94 reconhecimento opt-in por projeto (\xc2\xa7""9.3, LGPD)\n"
"-- \"pessoa\" \xc3\xa9 o agrupamento (cluster) que liga rosto recorrente a voz recorrente (\xc2\xa7""9.2)\n"
"-- Vem antes de transcri\xc3\xa7\xc3\xa3o porque transcricao_palavra.falante_id referencia voz.\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS pessoa (\n"
"    id              TEXT PRIMARY KEY,\n"
"    projeto_id      TEXT NOT NULL,\n"
"    nome            TEXT,           -- preenchido pelo operador ao identificar o cluster; nulo at\xc3\xa9 l\xc3\xa1\n"
"    criado_em       TEXT NOT NULL\n"
");\n"
"\n"
"CREATE TABLE IF NOT EXISTS rosto (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    tempo_ref       REAL,           -- instante do frame, em v\xc3\xad""deo\n"
"    regiao_json     TEXT NOT NULL,  -- bbox\n"
"    vetor           BLOB NOT NULL,\n"
"    dimensao        INTEGER NOT NULL,\n"
"    pessoa_id       TEXT REFERENCES pessoa(id) ON DELETE SET NULL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_rosto_item ON rosto(item_id);\n"
"CREATE INDEX IF NOT EXISTS idx_rosto_pessoa ON rosto(pessoa_id);\n"
"\n"
"CREATE TABLE IF NOT EXISTS voz (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    tempo_inicio    REAL NOT NULL,\n"
"    tempo_fim       REAL NOT NULL,\n"
"    vetor           BLOB NOT NULL,\n"
"    dimensao        INTEGER NOT NULL,\n"
"    pessoa_id       TEXT REFERENCES pessoa(id) ON DELETE SET NULL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_voz_item ON voz(item_id);\n"
"CREATE INDEX IF NOT EXISTS idx_voz_pessoa ON voz(pessoa_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Transcri\xc3\xa7\xc3\xa3o \xe2\x80\x94 timestamp por palavra, marca de verificado (\xc2\xa7""9.3)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS transcricao (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    idioma          TEXT,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL,\n"
"    verificado      INTEGER NOT NULL DEFAULT 0 CHECK (verificado IN (0, 1)),\n"
"    verificado_por  TEXT,\n"
"    verificado_em   TEXT\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_transcricao_item ON transcricao(item_id);\n"
"\n"
"CREATE TABLE IF NOT EXISTS transcricao_palavra (\n"
"    id              TEXT PRIMARY KEY,\n"
"    transcricao_id  TEXT NOT NULL REFERENCES transcricao(id) ON DELETE CASCADE,\n"
"    texto           TEXT NOT NULL,\n"
"    tempo_inicio    REAL NOT NULL,\n"
"    tempo_fim       REAL NOT NULL,\n"
"    falante_id      TEXT REFERENCES voz(id) ON DELETE SET NULL, -- diariza\xc3\xa7\xc3\xa3o (pyannote)\n"
"    confianca       REAL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_transcricao_palavra_transcricao ON transcricao_palavra(transcricao_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- OCR (\xc2\xa7""9)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS ocr (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    texto           TEXT NOT NULL,\n"
"    regiao_json     TEXT, -- bbox na imagem/p\xc3\xa1gina, quando aplic\xc3\xa1vel\n"
"    confianca       REAL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_ocr_item ON ocr(item_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Fingerprint de \xc3\xa1udio e pHash de imagem \xe2\x80\x94 duplicata (\xc2\xa7""7.4, \xc2\xa7""9)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS fingerprint_audio (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    algoritmo       TEXT NOT NULL,\n"
"    hash            TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_fingerprint_hash ON fingerprint_audio(hash);\n"
"\n"
"CREATE TABLE IF NOT EXISTS phash_imagem (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    hash            TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_phash_hash ON phash_imagem(hash);\n"
"\n"
"CREATE TABLE IF NOT EXISTS duplicata (\n"
"    id              TEXT PRIMARY KEY,\n"
"    tipo            TEXT NOT NULL CHECK (tipo IN ('phash', 'fingerprint', 'lossy_transcodificado')),\n"
"    item_id_a       TEXT NOT NULL,\n"
"    arquivo_id_a    TEXT NOT NULL,\n"
"    item_id_b       TEXT NOT NULL,\n"
"    arquivo_id_b    TEXT NOT NULL,\n"
"    similaridade    REAL NOT NULL,\n"
"    detectado_em    TEXT NOT NULL\n"
");\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Qualidade de imagem e cortes de cena (\xc2\xa7""9)\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS qualidade_imagem (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    blur_score      REAL,\n"
"    exposicao_score REAL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE TABLE IF NOT EXISTS corte_cena (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    arquivo_id      TEXT NOT NULL,\n"
"    tempo           REAL NOT NULL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_corte_cena_arquivo ON corte_cena(arquivo_id);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- Sugest\xc3\xa3o de campo \xe2\x80\x94 ponte gen\xc3\xa9rica entre modelo e ficha (P3).\n"
"-- Cobre natureza do conte\xc3\xba""do, categoria de sample, bpm, tonalidade, tipo\n"
"-- temporal e qualquer outro campo YAML com \"sugerido_por\" ou \"preenchido_por\"\n"
"-- um modelo. Ao confirmar, a aplica\xc3\xa7\xc3\xa3o grava em registro.item_campo\n"
"-- (fonte='humano') e registro.item_historico (tipo_evento='confirmacao_sugestao_ia'),\n"
"-- e marca confirmado=1 aqui \xe2\x80\x94 o registro \xc3\xadndice n\xc3\xa3o \xc3\xa9 apagado, fica como\n"
"-- rastro de auditoria descart\xc3\xa1vel.\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS sugestao_campo (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    nivel           TEXT NOT NULL DEFAULT 'raiz',\n"
"    nivel_indice     INTEGER NOT NULL DEFAULT 0,\n"
"    campo_id        TEXT NOT NULL,\n"
"    valor           TEXT NOT NULL,\n"
"    confianca       REAL,\n"
"    modelo          TEXT NOT NULL,\n"
"    modelo_versao   TEXT NOT NULL,\n"
"    processado_em   TEXT NOT NULL,\n"
"    confirmado      INTEGER NOT NULL DEFAULT 0 CHECK (confirmado IN (0, 1)),\n"
"    confirmado_por  TEXT,\n"
"    confirmado_em   TEXT\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_sugestao_campo_item ON sugestao_campo(item_id);\n"
"CREATE INDEX IF NOT EXISTS idx_sugestao_campo_pendente ON sugestao_campo(item_id, confirmado);\n"
"\n"
"-- ---------------------------------------------------------------------------\n"
"-- AI Scan \xe2\x80\x94 resultados de an\xc3\xa1lise contextual com IA (Gemini).\n"
"-- Vive no \xc3\xadndice (P2: dados de modelo s\xc3\xa3o descart\xc3\xa1veis e reconstru\xc3\xadveis).\n"
"-- ---------------------------------------------------------------------------\n"
"CREATE TABLE IF NOT EXISTS ai_scan_resultado (\n"
"    id              TEXT PRIMARY KEY,\n"
"    item_id         TEXT NOT NULL,\n"
"    modelo          TEXT NOT NULL,\n"
"    tipo_analise    TEXT NOT NULL,\n"
"    contexto_json   TEXT NOT NULL,\n"
"    resumo          TEXT,\n"
"    confianca       REAL,\n"
"    analisado_em    TEXT NOT NULL\n"
");\n"
"\n"
"CREATE INDEX IF NOT EXISTS idx_ai_scan_resultado_item ON ai_scan_resultado(item_id);\n";

const char* indice_sql = (const char*) temp_binary_data_1;
}
