#pragma once

#include <unordered_map>
#include <string>

namespace matriz::i18n {

inline const std::unordered_map<std::string, std::string>& getPortugueseStrings() {
    static const std::unordered_map<std::string, std::string> strings = {
        {"acoes.categorizar", "Categorizar…"},
        {"acoes.copiar_caminho", "Copiar caminho"},
        {"acoes.definir_capa", "Usar imagem como capa…"},
        {"acoes.enviar_para_pasta", "Enviar para pasta"},
        {"acoes.mostrar_na_origem", "Mostrar na origem"},
        {"acoes.origem_ausente_mensagem", "O arquivo veio de:\n{caminho}\n\nConecte o disco de origem para abrir a pasta."},
        {"acoes.origem_ausente_titulo", "Origem não está conectada"},
        {"acoes.preview", "Ver prévia"},
        {"acoes.remover_capa", "Remover capa"},
        {"acoes.remover_da_lista", "Remover desta lista"},
        {"acoes.remover_da_lista_mensagem", "{n} arquivo(s) somem desta lista e do projeto, junto com a ficha preenchida.\n\nNenhum arquivo é apagado do disco: o original na fonte continua onde está."},
        {"acoes.remover_da_lista_titulo", "Remover desta lista?"},
        {"acoes.remover_do_backup", "Remover da coleção"},
        {"acoes.remover_do_backup_mensagem", "{n} arquivo(s) saem das pastas da coleção e voltam para \"Ainda sem pasta\".\n\nNenhum arquivo é apagado do disco."},
        {"acoes.remover_do_backup_titulo", "Remover da coleção?"},
        {"acoes.renomear", "Renomear…"},
        {"acoes.renomear_mensagem", "Novo nome. É ele que vai virar o nome do arquivo no backup."},
        {"acoes.renomear_mensagem_lote", "Novo nome para os {n} arquivos. A máscara numera cada um automaticamente."},
        {"acoes.renomear_previa", "No backup vai ficar: {nome}"},
        {"acoes.renomear_titulo", "Renomear"},
        {"acoes.sem_duplicatas", "Nenhum outro arquivo do projeto tem este mesmo conteúdo."},
        {"acoes.sem_pastas", "Nenhuma pasta criada ainda — crie uma no \"+\" da aba BACKUP"},
        {"acoes.ver_duplicatas", "Ver duplicatas deste arquivo"},
        {"app.nome", "BKR Matriz"},
        {"arvore.aba_acervo", "BACKUP"},
        {"arvore.aba_origem", "EXPLORER"},
        {"arvore.achatar_estrutura", "Colocar tudo direto nesta pasta"},
        {"arvore.apagar_confirmar_mensagem", "Isto só apaga a pasta do plano de organização — nenhum arquivo em disco é tocado. Os arquivos que estavam nela continuam no projeto, só voltam pra \"Ainda sem pasta\"."},
        {"arvore.apagar_confirmar_titulo", "Apagar pasta?"},
        {"arvore.backup_dica", "A estrutura que você monta e que vai ser gravada no backup."},
        {"arvore.explorer_dica", "A estrutura real do disco de origem, como ela é. Nada aqui é editável."},
        {"arvore.incluir_subpastas", "Incluir subpastas"},
        {"arvore.manter_estrutura", "Manter a estrutura de pastas"},
        {"arvore.menu_apagar", "Apagar"},
        {"arvore.menu_nova_subpasta", "Nova subpasta"},
        {"arvore.menu_renomear", "Renomear"},
        {"arvore.mostrar_conteudo_grade", "EXIBIR CONTEÚDO NA GRADE"},
        {"arvore.nao_organizados", "Ainda sem pasta"},
        {"arvore.nome_nova_pasta_mensagem", "Nome da pasta:"},
        {"arvore.nome_nova_pasta_titulo", "Nova pasta"},
        {"arvore.nova_pasta", "Nova pasta"},
        {"arvore.pasta_raiz_auto", "Importados"},
        {"arvore.renomear_pasta_mensagem", "Novo nome:"},
        {"arvore.renomear_pasta_titulo", "Renomear pasta"},
        {"arvore.soltar_pasta_mensagem", "\"{pasta}\" tem {n} arquivo(s) em subpastas."},
        {"arvore.soltar_pasta_titulo", "Como trazer esta pasta?"},
        {"arvore.todos_os_materiais", "Todos os arquivos"},
        {"backup.btn_copiar", "INICIAR CÓPIA"},
        {"backup.btn_proximo", "AVANÇAR"},
        {"backup.btn_voltar", "VOLTAR"},
        {"backup.cancelar", "Cancelar"},
        {"backup.copiando_progresso", "Copiando {0} de {1}..."},
        {"backup.copiando_titulo", "Copiando arquivos"},
        {"backup.destino_titulo", "Escolha o destino"},
        {"backup.destino_vazio", "Nenhum volume disponível. Conecte um disco externo."},
        {"backup.done_falhas", "{0} arquivos falharam ao copiar"},
        {"backup.done_titulo", "Backup Concluído"},
        {"backup.done_verificados", "{0} arquivos copiados e verificados"},
        {"backup.escolha_colecao", "Uma coleção"},
        {"backup.escolha_precisa", "Precisa de backup"},
        {"backup.escolha_recentes", "Recém-adicionados"},
        {"backup.escolha_selecionados", "Arquivos selecionados"},
        {"backup.escolha_titulo", "O que incluir no backup"},
        {"backup.escolha_tudo", "Tudo"},
        {"backup.preview_espaco", "Espaço necessário: {0}  |  Disponível: {1}"},
        {"backup.preview_ja_copiados", "{0} já com backup (ignorados)"},
        {"backup.preview_novos", "{0} novos arquivos para copiar"},
        {"backup.preview_titulo", "Prévia do backup"},
        {"backup.step_copiar", "Copiar"},
        {"backup.step_destino", "Destino"},
        {"backup.step_done", "Concluído"},
        {"backup.step_escolha", "Seleção"},
        {"backup.step_preview", "Prévia"},
        {"backup.step_verificar", "Verificar"},
        {"backup.titulo", "Backup"},
        {"backup.verificando_progresso", "Verificando {0} de {1}..."},
        {"backup.verificando_titulo", "Verificando cópias"},
        {"backup.voltar_home", "VOLTAR AO INÍCIO"},
        {"barra.adicionar", "Adicionar arquivos"},
        {"barra.adicionar_dica", "Escolha uma pasta ou arquivos pra copiar pro projeto. Você também pode arrastar direto do Finder pra qualquer lugar desta janela."},
        {"barra.backup", "Backup"},
        {"barra.backup_dica", "Copia o original byte a byte pra outro disco, seguindo as pastas que você montou em BACKUP. A origem nunca é tocada."},
        {"barra.buscar", "Buscar por nome, código ou qualquer informação"},
        {"barra.contagem", "{visiveis} de {total} arquivos"},
        {"barra.contagem_filtrada", "{visiveis} de {total} arquivos  ·  filtro ativo"},
        {"barra.detalhes_dica", "Mostra ou esconde o painel lateral com as informações do que está selecionado."},
        {"barra.modo_visao_dica", "Alternar entre visualização em grade e lista"},
        {"barra.tamanho_dica", "Tamanho das miniaturas"},
        {"catalogo.abrir", "Abrir catálogo de backup…"},
        {"catalogo.ausente", "fonte ausente"},
        {"catalogo.cancelado", "Catálogo cancelado — {feito} de {total}. O que foi gravado está salvo."},
        {"catalogo.disponivel", "disponível"},
        {"catalogo.fechar", "Fechar catálogo"},
        {"catalogo.gerado", "Catálogo gravado — {n} materiais consultáveis sem o HD conectado."},
        {"catalogo.gerando", "Gerando catálogo… {feito}/{total}"},
        {"catalogo.gerar", "Gerar catálogo de consulta"},
        {"catalogo.gerar_ajuda", "Miniaturas, fichas e a localização de cada arquivo, gravadas junto com o backup. Ocupa {tamanho} e permite consultar o acervo com o HD desconectado."},
        {"catalogo.nao_e_catalogo", "Esta pasta não tem um catálogo do Matriz dentro."},
        {"catalogo.onde_esta_corpo", "{titulo}\n\nDisco: {volume}\nPasta: {local}\n\nCaminho completo:\n{caminho}\n\nConecte o disco para abrir o arquivo."},
        {"catalogo.onde_esta_titulo", "Onde este arquivo está"},
        {"catalogo.sem_resultado", "Nenhum material encontrado para esta busca."},
        {"catalogo.titulo", "Catálogo do backup"},
        {"catalogo.vazio", "Este catálogo está vazio."},
        {"catalogo.volume_desconhecido", "disco não identificado"},
        {"catwork.all", "TODOS OS ITENS"},
        {"catwork.audio", "Áudio"},
        {"catwork.back", "Voltar ao catálogo"},
        {"catwork.documents", "Documentos"},
        {"catwork.images", "Imagens"},
        {"catwork.needs_review", "Precisa de revisão"},
        {"catwork.no_backup", "Sem backup"},
        {"catwork.offline", "Offline"},
        {"catwork.selected", "Arquivos selecionados"},
        {"catwork.sessions", "Sessões"},
        {"catwork.single_copy", "Cópia única"},
        {"catwork.source_structure", "Estrutura de origem"},
        {"catwork.video", "Vídeo"},
        {"colecoes.ausentes", "Ausentes"},
        {"colecoes.clipping", "Clipping"},
        {"colecoes.incompletos", "Incompletos"},
        {"colecoes.nao_baixados", "Não baixados"},
        {"colecoes.revisao", "Precisa de revisão"},
        {"colecoes.vulneraveis", "Sem backup ainda"},
        {"comum.cancelar", "Cancelar"},
        {"comum.erro", "Erro"},
        {"comum.nao", "Não"},
        {"comum.ok", "OK"},
        {"comum.salvar", "Salvar"},
        {"comum.sim", "Sim"},
        {"configuracoes_projeto.aviso_sobrescrever_cancelar", "Cancelar"},
        {"configuracoes_projeto.aviso_sobrescrever_confirmar", "Entendi, permitir mesmo assim"},
        {"configuracoes_projeto.aviso_sobrescrever_corpo", "Ligar esta opção permite que o master original seja sobrescrito diretamente, sem passar por uma derivada. Isso desliga a garantia padrão de preservação (dois arquivos por padrão, P1) — o arquivo original deixa de estar protegido contra sobrescrita acidental. É uma decisão do responsável pelo projeto: o software avisa uma única vez, aqui, e não pergunta de novo depois de confirmada."},
        {"configuracoes_projeto.aviso_sobrescrever_titulo", "Atenção: sobrescrita de master"},
        {"configuracoes_projeto.botao_fechar", "Fechar"},
        {"configuracoes_projeto.campo_nome", "Nome do projeto"},
        {"configuracoes_projeto.campo_permitir_sobrescrever", "Permitir sobrescrever master"},
        {"configuracoes_projeto.secao_geral", "Geral"},
        {"configuracoes_projeto.secao_master", "Master"},
        {"configuracoes_projeto.titulo", "Configurações do projeto"},
        {"consolidacao.aviso_conflitos", "{n} nome(s) repetido(s) — resolva antes de gravar."},
        {"consolidacao.aviso_espaco", "Precisa de: {necessario}  ·  Livre no destino: {disponivel}"},
        {"consolidacao.aviso_nao_organizados", "{n} arquivo(s) ainda fora de qualquer pasta da BACKUP — não entram neste backup."},
        {"consolidacao.cancelado", "Cancelado — {feito} de {total} processados. O que foi gravado está salvo e verificado."},
        {"consolidacao.consolidando", "Gravando… em acervos grandes isso pode demorar bastante."},
        {"consolidacao.consolidar", "Gravar backup"},
        {"consolidacao.destino_nao_escolhido", "Escolha o disco ou a pasta onde o backup vai ser gravado."},
        {"consolidacao.escolher_destino", "Escolher onde gravar…"},
        {"consolidacao.fechar", "Fechar"},
        {"consolidacao.ja_consolidado", "já copiado"},
        {"consolidacao.previa_vazia", "Ainda não há nada pra gravar. Arraste pastas ou arquivos da EXPLORER pras pastas da BACKUP, à esquerda — é essa organização que vira o backup."},
        {"consolidacao.progresso", "Gravando… {feito}/{total}"},
        {"consolidacao.resultado", "{consolidados} copiados, {pulados} já estavam em dia"},
        {"consolidacao.resultado_falhas", "{n} falharam"},
        {"consolidacao.titulo", "Backup"},
        {"dialogo_abrir_projeto.botao_escolher", "Escolher pasta do projeto…"},
        {"dialogo_abrir_projeto.erro_titulo", "Não foi possível abrir o projeto"},
        {"dialogo_abrir_projeto.titulo", "Abrir projeto"},
        {"dialogo_novo_projeto.botao_cancelar", "Cancelar"},
        {"dialogo_novo_projeto.botao_criar", "Criar projeto"},
        {"dialogo_novo_projeto.botao_escolher_pasta", "Escolher pasta…"},
        {"dialogo_novo_projeto.campo_instituicao", "Instituição ou selo (opcional)"},
        {"dialogo_novo_projeto.campo_isrc", "Registrante ISRC (opcional)"},
        {"dialogo_novo_projeto.campo_modo_catalogo", "Novo projeto de música"},
        {"dialogo_novo_projeto.campo_modo_preservacao", "Novo projeto de arquivos variados"},
        {"dialogo_novo_projeto.campo_nome", "Nome do projeto"},
        {"dialogo_novo_projeto.campo_pasta", "Pasta de backup"},
        {"dialogo_novo_projeto.campo_pasta_ajuda", "Uma pasta nova, num disco com espaço. É pra lá que seus arquivos serão copiados — os originais não são movidos nem apagados."},
        {"dialogo_novo_projeto.campo_prefixo", "Prefixo de nomenclatura"},
        {"dialogo_novo_projeto.campo_responsavel", "Responsável (opcional)"},
        {"dialogo_novo_projeto.erro_nome_vazio", "Dê um nome ao projeto pra continuar."},
        {"dialogo_novo_projeto.erro_pasta_vazia", "Escolha uma pasta onde o projeto vai ficar."},
        {"dialogo_novo_projeto.erro_prefixo_vazio", "O prefixo de nomenclatura é obrigatório."},
        {"dialogo_novo_projeto.erro_titulo", "Não foi possível criar o projeto"},
        {"dialogo_novo_projeto.titulo", "Novo projeto"},
        {"escuta.adicionar_marcador", "Adicionar Marcador"},
        {"escuta.arquivo_truncado", "Arquivo longo: apenas os primeiros 45 minutos foram carregados para reprodução"},
        {"escuta.correlacao", "CORRELAÇÃO"},
        {"escuta.espectro", "ESPECTRO"},
        {"escuta.fechar", "Fechar"},
        {"escuta.formato_nao_suportado", "Este formato de áudio não pode ser reproduzido aqui — o arquivo original permanece intacto"},
        {"escuta.loop_in", "Início do loop"},
        {"escuta.loop_limpar", "Limpar loop"},
        {"escuta.loop_out", "Fim do loop"},
        {"escuta.parar", "Parar"},
        {"escuta.sem_arquivo", "Este item ainda não tem arquivo anexado"},
        {"escuta.sem_forma_onda", "Nenhuma forma de onda em cache para este item"},
        {"escuta.tocar", "Reproduzir"},
        {"escuta.vault_offline", "Vault offline — reprodução desabilitada. O arquivo está em: {local}"},
        {"escuta.vetorscopio", "VETORSCÓPIO"},
        {"escuta.vu", "VU / PICO"},
        {"estado_vazio.rodape", "Seus arquivos originais não são movidos nem apagados — o Matriz faz uma cópia dentro do projeto."},
        {"estado_vazio.subtitulo", "ou clique aqui pra escolher no computador"},
        {"estado_vazio.titulo", "Arraste sua pasta ou seu HD pra cá"},
        {"ficha.alerta_rotulo", "Atenção"},
        {"ficha.alternar", "Detalhes"},
        {"ficha.arquivo_ausente", "ausente"},
        {"ficha.arquivo_obrigatorio", "obrigatório"},
        {"ficha.arquivo_presente", "presente"},
        {"ficha.cabecalho_sem_titulo", "(sem título)"},
        {"ficha.campo_booleano_nao", "Não"},
        {"ficha.campo_booleano_sim", "Sim"},
        {"ficha.herdado_do_projeto", "herdado do projeto"},
        {"ficha.lote_aplicar", "Aplicar"},
        {"ficha.lote_campos_nao_suportados", "Campos de tabela e lista de pessoas ainda não são editáveis em lote — edite item por item."},
        {"ficha.lote_desfazer", "Desfazer"},
        {"ficha.lote_escolher_tipo", "Nenhum dos materiais selecionados está classificado ainda. Escolha um tipo de mídia pra aplicar a todos:"},
        {"ficha.lote_nenhum_campo_tocado", "Edite um campo acima, depois aplique pra seleção inteira."},
        {"ficha.lote_previa", "{n} materiais serão alterados: {campos}"},
        {"ficha.lote_resultado", "{sucessos} alterados"},
        {"ficha.lote_resultado_desfeito", "{n} restaurados"},
        {"ficha.lote_resultado_falhas", ", {falhas} falharam"},
        {"ficha.lote_tipo_misto", "A seleção tem tipos de mídia diferentes. Selecione itens do mesmo tipo pra editar a ficha em lote."},
        {"ficha.lote_tipo_misto_universais", "A seleção tem tipos de mídia diferentes — só Origem e Ano existem em todos os tipos, então só esses podem ser editados juntos."},
        {"ficha.lote_titulo", "{n} materiais selecionados"},
        {"ficha.lote_valores_multiplos", "Múltiplos valores"},
        {"ficha.nao_classificado", "Ainda não classificado. Escolha um tipo de mídia pra preencher a ficha:"},
        {"ficha.nivel_faixa_adicionar", "Adicionar faixa"},
        {"ficha.nivel_faixa_numero", "Faixa {n}"},
        {"ficha.nivel_faixa_remover", "Remover faixa"},
        {"ficha.observacao_minutagem_dica", "Minutagem (MM:SS, opcional)"},
        {"ficha.observacao_nova", "Nova observação"},
        {"ficha.opcao_livre_criar", "Criar \"{texto}\""},
        {"ficha.preenchido_por_leitura_tecnica", "leitura técnica"},
        {"ficha.recategorizar", "Trocar tipo"},
        {"ficha.recategorizar_titulo", "Escolha um novo tipo de mídia:"},
        {"ficha.secao_arquivos_esperados", "Arquivos esperados"},
        {"ficha.secao_observacoes", "Observações"},
        {"ficha.sugestao_confianca", "confiança {p}%"},
        {"ficha.sugestao_confirmar", "Confirmar"},
        {"ficha.sugestao_modelo", "modelo: {modelo} {versao}"},
        {"ficha.sugestao_rotulo", "sugestão"},
        {"ficha.tabela_adicionar_linha", "Adicionar linha"},
        {"ficha.tabela_remover_linha", "Remover"},
        {"ficha.vazia", "Clique num arquivo da grade pra ver e editar as informações dele aqui."},
        {"ficha_alertas.cassete.sticky_shed", "Requer tratamento térmico antes da reprodução"},
        {"ficha_alertas.filme.quebradico", "Manuseio requer cuidado especial — risco de quebra ou combustão em nitrato"},
        {"ficha_alertas.fita_rolo.sticky_shed", "Requer tratamento térmico antes da reprodução"},
        {"ficha_alertas.minidisc.atrac_lossy", "Fonte já é lossy — a digitalização não recupera qualidade perdida na gravação original"},
        {"ficha_campos.cassete.abrangencia", "Abrangência da gravação"},
        {"ficha_campos.cassete.ano", "Ano"},
        {"ficha_campos.cassete.deck", "Deck de reprodução"},
        {"ficha_campos.cassete.direcao", "Sentido capturado"},
        {"ficha_campos.cassete.dolby", "Redução de ruído"},
        {"ficha_campos.cassete.duracao_nominal", "Duração nominal"},
        {"ficha_campos.cassete.estado_geral", "Estado geral"},
        {"ficha_campos.cassete.fita_solta_enroscada", "Fita solta ou enroscada no mecanismo"},
        {"ficha_campos.cassete.idioma", "Idioma"},
        {"ficha_campos.cassete.marca", "Marca"},
        {"ficha_campos.cassete.natureza", "Natureza do conteúdo"},
        {"ficha_campos.cassete.origem", "Origem"},
        {"ficha_campos.cassete.sticky_shed", "Sinais de sticky shed"},
        {"ficha_campos.cassete.tipo_fita", "Tipo de fita"},
        {"ficha_campos.cassete.trecho_observacao", "Observação sobre o trecho"},
        {"ficha_campos.cassete.trecho_posicao", "Posição do trecho"},
        {"ficha_campos.cd.ano", "Ano"},
        {"ficha_campos.cd.estado_fisico", "Estado físico do disco"},
        {"ficha_campos.cd.idioma", "Idioma"},
        {"ficha_campos.cd.marca_midia", "Marca da mídia (se CD-R)"},
        {"ficha_campos.cd.natureza", "Natureza do conteúdo"},
        {"ficha_campos.cd.numero_faixas", "Número de faixas"},
        {"ficha_campos.cd.origem", "Origem"},
        {"ficha_campos.cd.ripagem_bit_exata_confirmada", "Ripagem bit-exata confirmada"},
        {"ficha_campos.cd.tipo_disco", "Tipo de disco"},
        {"ficha_campos.cd.toc", "TOC / duração total"},
        {"ficha_campos.cover_art.ano", "Year"},
        {"ficha_campos.cover_art.artista", "Artist"},
        {"ficha_campos.cover_art.designer", "Designer / photographer"},
        {"ficha_campos.cover_art.dimensoes", "Dimensions"},
        {"ficha_campos.cover_art.formato", "Format"},
        {"ficha_campos.cover_art.licenca", "License / use"},
        {"ficha_campos.cover_art.origem", "Origin"},
        {"ficha_campos.cover_art.resolucao", "Resolution"},
        {"ficha_campos.cover_art.tipo_arte", "Art type"},
        {"ficha_campos.cover_art.titulo_release", "Release title"},
        {"ficha_campos.dat.ano", "Ano"},
        {"ficha_campos.dat.caminho_captura", "Caminho de captura"},
        {"ficha_campos.dat.deck", "Deck de reprodução"},
        {"ficha_campos.dat.duracao_fita", "Duração nominal"},
        {"ficha_campos.dat.erros_leitura", "Erros de leitura durante a captura"},
        {"ficha_campos.dat.estado_geral", "Estado geral"},
        {"ficha_campos.dat.idioma", "Idioma"},
        {"ficha_campos.dat.marca", "Marca da fita"},
        {"ficha_campos.dat.natureza", "Natureza do conteúdo"},
        {"ficha_campos.dat.origem", "Origem"},
        {"ficha_campos.dat.sample_rate_original", "Sample rate original"},
        {"ficha_campos.dat.subcode_disponivel", "Subcode (start ID/programa) disponível"},
        {"ficha_campos.digital_audio.ano", "Ano"},
        {"ficha_campos.digital_audio.bit_depth_declarado", "Bit depth declarado"},
        {"ficha_campos.digital_audio.codec", "Codec"},
        {"ficha_campos.digital_audio.daw_origem", "DAW de origem"},
        {"ficha_campos.digital_audio.eh_mixdown_ou_stem", "Tipo de material"},
        {"ficha_campos.digital_audio.formato_arquivo", "Formato do arquivo"},
        {"ficha_campos.digital_audio.idioma", "Idioma"},
        {"ficha_campos.digital_audio.natureza", "Natureza do conteúdo"},
        {"ficha_campos.digital_audio.origem", "Origem"},
        {"ficha_campos.digital_audio.plugins_criticos", "Plugins críticos (dependência de sessão)"},
        {"ficha_campos.digital_audio.sample_rate_declarado", "Sample rate declarado"},
        {"ficha_campos.digital_video.ano", "Ano"},
        {"ficha_campos.digital_video.camera", "Câmera / modelo"},
        {"ficha_campos.digital_video.codec", "Codec"},
        {"ficha_campos.digital_video.contagem_poligonos", "Contagem de polígonos"},
        {"ficha_campos.digital_video.data_gravacao", "Data de gravação"},
        {"ficha_campos.digital_video.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.digital_video.formato", "Formato"},
        {"ficha_campos.digital_video.formato_container", "Formato do container"},
        {"ficha_campos.digital_video.frame_rate_declarado", "Frame rate declarado"},
        {"ficha_campos.digital_video.origem", "Origem"},
        {"ficha_campos.digital_video.possui_rig", "Possui rig"},
        {"ficha_campos.digital_video.possui_texturas", "Possui texturas"},
        {"ficha_campos.digital_video.resolucao", "Resolução"},
        {"ficha_campos.digital_video.software_origem", "Software de origem"},
        {"ficha_campos.documento.ano", "Ano"},
        {"ficha_campos.documento.assinado", "Assinado"},
        {"ficha_campos.documento.autor_documento", "Autor / emissor"},
        {"ficha_campos.documento.data_documento", "Data do documento"},
        {"ficha_campos.documento.estado_fisico", "Estado físico (se digitalizado de papel)"},
        {"ficha_campos.documento.idioma", "Idioma"},
        {"ficha_campos.documento.numero_paginas", "Número de páginas"},
        {"ficha_campos.documento.origem", "Origem"},
        {"ficha_campos.documento.texto_pesquisavel", "Texto pesquisável no PDF"},
        {"ficha_campos.documento.tipo_documento", "Tipo de documento"},
        {"ficha_campos.field_recording.ambiente", "Ambiente"},
        {"ficha_campos.field_recording.ano", "Ano"},
        {"ficha_campos.field_recording.condicoes", "Condições (vento, chuva, ruído de fundo)"},
        {"ficha_campos.field_recording.equipamento_gravador", "Gravador"},
        {"ficha_campos.field_recording.idioma", "Idioma"},
        {"ficha_campos.field_recording.microfone", "Microfone"},
        {"ficha_campos.field_recording.natureza", "Natureza do conteúdo"},
        {"ficha_campos.field_recording.origem", "Origem"},
        {"ficha_campos.field_recording.padrao_polar", "Padrão polar"},
        {"ficha_campos.filme.ano", "Ano"},
        {"ficha_campos.filme.bitola", "Bitola"},
        {"ficha_campos.filme.campo_entrelacado_detectado", "Campo entrelaçado detectado"},
        {"ficha_campos.filme.cor_pb", "Cor ou preto e branco"},
        {"ficha_campos.filme.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.filme.encolhimento", "Encolhimento da base"},
        {"ficha_campos.filme.estado_geral", "Estado geral"},
        {"ficha_campos.filme.fps_captura", "FPS do arquivo capturado"},
        {"ficha_campos.filme.fps_original_declarado", "FPS original declarado"},
        {"ficha_campos.filme.mofo", "Sinais de mofo"},
        {"ficha_campos.filme.origem", "Origem"},
        {"ficha_campos.filme.pulldown_detectado", "Pulldown 3:2 detectado"},
        {"ficha_campos.filme.quadro_duplicado_detectado", "Quadro duplicado detectado"},
        {"ficha_campos.filme.quebradico", "Material quebradiço (base de nitrato/acetato degradado)"},
        {"ficha_campos.filme.som_optico", "Possui trilha sonora óptica"},
        {"ficha_campos.fita_rolo.abrangencia", "Abrangência da gravação"},
        {"ficha_campos.fita_rolo.alinhamento", "Fita de alinhamento usada"},
        {"ficha_campos.fita_rolo.ano", "Ano"},
        {"ficha_campos.fita_rolo.curva", "Curva de equalização"},
        {"ficha_campos.fita_rolo.direcao", "Sentido"},
        {"ficha_campos.fita_rolo.emendas", "Emendas visíveis"},
        {"ficha_campos.fita_rolo.espessura", "Espessura"},
        {"ficha_campos.fita_rolo.estado_geral", "Estado geral"},
        {"ficha_campos.fita_rolo.formulacao", "Formulação"},
        {"ficha_campos.fita_rolo.idioma", "Idioma"},
        {"ficha_campos.fita_rolo.largura", "Largura"},
        {"ficha_campos.fita_rolo.maquina", "Máquina de reprodução"},
        {"ficha_campos.fita_rolo.marca", "Marca"},
        {"ficha_campos.fita_rolo.natureza", "Natureza do conteúdo"},
        {"ficha_campos.fita_rolo.origem", "Origem"},
        {"ficha_campos.fita_rolo.pistas", "Configuração de pistas"},
        {"ficha_campos.fita_rolo.print_through", "Print-through audível"},
        {"ficha_campos.fita_rolo.sticky_shed", "Sinais de sticky shed"},
        {"ficha_campos.fita_rolo.trecho_observacao", "Observação sobre o trecho"},
        {"ficha_campos.fita_rolo.trecho_posicao", "Posição do trecho"},
        {"ficha_campos.fita_rolo.velocidade", "Velocidade"},
        {"ficha_campos.foto.ano", "Ano"},
        {"ficha_campos.foto.camera", "Câmera / modelo"},
        {"ficha_campos.foto.danos", "Danos visíveis"},
        {"ficha_campos.foto.data_foto", "Data da foto"},
        {"ficha_campos.foto.dimensoes", "Dimensões"},
        {"ficha_campos.foto.estado_fisico", "Estado geral"},
        {"ficha_campos.foto.evento", "Evento"},
        {"ficha_campos.foto.fotografo", "Fotógrafo"},
        {"ficha_campos.foto.licenca", "Licença / uso"},
        {"ficha_campos.foto.local", "Local"},
        {"ficha_campos.foto.origem", "Origem"},
        {"ficha_campos.foto.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.foto.suporte", "Suporte"},
        {"ficha_campos.minidisc.ano", "Ano"},
        {"ficha_campos.minidisc.atrac_lossy", "Origem em ATRAC (lossy)"},
        {"ficha_campos.minidisc.caminho_captura", "Caminho de captura"},
        {"ficha_campos.minidisc.deck", "Deck de reprodução"},
        {"ficha_campos.minidisc.erros_leitura", "Erros de leitura durante a captura"},
        {"ficha_campos.minidisc.estado_geral", "Estado geral"},
        {"ficha_campos.minidisc.idioma", "Idioma"},
        {"ficha_campos.minidisc.marca", "Marca"},
        {"ficha_campos.minidisc.modo_gravacao", "Modo de gravação"},
        {"ficha_campos.minidisc.natureza", "Natureza do conteúdo"},
        {"ficha_campos.minidisc.origem", "Origem"},
        {"ficha_campos.minidisc.tipo_disco", "Tipo de disco"},
        {"ficha_campos.negativo.ano", "Ano"},
        {"ficha_campos.negativo.cor_pb", "Cor ou preto e branco"},
        {"ficha_campos.negativo.data_foto", "Data da foto"},
        {"ficha_campos.negativo.desvanecimento", "Desvanecimento de cor"},
        {"ficha_campos.negativo.dimensoes_scan", "Dimensões do escaneamento"},
        {"ficha_campos.negativo.estado_geral", "Estado geral"},
        {"ficha_campos.negativo.formato", "Formato"},
        {"ficha_campos.negativo.local", "Local"},
        {"ficha_campos.negativo.mofo", "Sinais de mofo"},
        {"ficha_campos.negativo.origem", "Origem"},
        {"ficha_campos.negativo.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.negativo.resolucao_scan", "Resolução do escaneamento"},
        {"ficha_campos.negativo.riscos", "Riscos visíveis"},
        {"ficha_campos.release.ano", "Ano"},
        {"ficha_campos.release.artista_principal", "Artista principal"},
        {"ficha_campos.release.compositores", "Compositores"},
        {"ficha_campos.release.data_lancamento", "Data de lançamento"},
        {"ficha_campos.release.duracao", "Duração"},
        {"ficha_campos.release.editora", "Editora"},
        {"ficha_campos.release.explicito", "Conteúdo explícito"},
        {"ficha_campos.release.formato", "Formato"},
        {"ficha_campos.release.genero", "Gênero"},
        {"ficha_campos.release.idioma", "Idioma"},
        {"ficha_campos.release.isrc", "ISRC"},
        {"ficha_campos.release.numero", "Número"},
        {"ficha_campos.release.numero_catalogo", "Número de catálogo"},
        {"ficha_campos.release.origem", "Origem"},
        {"ficha_campos.release.participacao", "Participação"},
        {"ficha_campos.release.selo", "Selo"},
        {"ficha_campos.release.splits", "Splits"},
        {"ficha_campos.release.titulo", "Título"},
        {"ficha_campos.release.upc_ean", "UPC/EAN"},
        {"ficha_campos.sample.ano", "Ano"},
        {"ficha_campos.sample.bpm", "BPM"},
        {"ficha_campos.sample.categoria", "Categoria"},
        {"ficha_campos.sample.licenca", "Licença"},
        {"ficha_campos.sample.origem", "Origem"},
        {"ficha_campos.sample.origem_texto", "Origem"},
        {"ficha_campos.sample.tipo_temporal", "Tipo temporal"},
        {"ficha_campos.sample.tonalidade", "Tonalidade"},
        {"ficha_campos.slide.ano", "Ano"},
        {"ficha_campos.slide.data_foto", "Data da foto"},
        {"ficha_campos.slide.desvanecimento", "Desvanecimento de cor"},
        {"ficha_campos.slide.dimensoes_scan", "Dimensões do escaneamento"},
        {"ficha_campos.slide.estado_geral", "Estado geral"},
        {"ficha_campos.slide.formato", "Formato"},
        {"ficha_campos.slide.fungo", "Sinais de fungo"},
        {"ficha_campos.slide.local", "Local"},
        {"ficha_campos.slide.moldura", "Moldura"},
        {"ficha_campos.slide.origem", "Origem"},
        {"ficha_campos.slide.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.slide.resolucao_scan", "Resolução do escaneamento"},
        {"ficha_campos.sound_effects.ano", "Ano"},
        {"ficha_campos.sound_effects.biblioteca_origem", "Biblioteca de origem"},
        {"ficha_campos.sound_effects.categoria", "Categoria"},
        {"ficha_campos.sound_effects.licenca", "Licença"},
        {"ficha_campos.sound_effects.origem", "Origem"},
        {"ficha_campos.video.ano", "Ano"},
        {"ficha_campos.video.campo_entrelacado_detectado", "Campo entrelaçado detectado"},
        {"ficha_campos.video.cortes_cena_detectados", "Cortes de cena detectados"},
        {"ficha_campos.video.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.video.dropout_frequente", "Dropout frequente"},
        {"ficha_campos.video.estado_geral", "Estado geral"},
        {"ficha_campos.video.fita_solta_enroscada", "Fita solta ou enroscada no mecanismo"},
        {"ficha_campos.video.formato_original", "Formato original"},
        {"ficha_campos.video.fps_captura", "FPS do arquivo capturado"},
        {"ficha_campos.video.origem", "Origem"},
        {"ficha_campos.video.pulldown_detectado", "Pulldown 3:2 detectado"},
        {"ficha_campos.video.quadro_duplicado_detectado", "Quadro duplicado detectado"},
        {"ficha_campos.video.sistema", "Sistema de cor"},
        {"ficha_campos.video.tbc_usado", "TBC usado na digitalização"},
        {"ficha_campos.vinil.ano", "Ano"},
        {"ficha_campos.vinil.cartucho", "Cartucho usado"},
        {"ficha_campos.vinil.curva", "Curva de equalização"},
        {"ficha_campos.vinil.empenado", "Empenado"},
        {"ficha_campos.vinil.estado_capa", "Estado da capa"},
        {"ficha_campos.vinil.estado_disco", "Estado do disco (Goldmine)"},
        {"ficha_campos.vinil.formato", "Formato"},
        {"ficha_campos.vinil.idioma", "Idioma"},
        {"ficha_campos.vinil.natureza", "Natureza do conteúdo"},
        {"ficha_campos.vinil.numero_catalogo", "Número de catálogo"},
        {"ficha_campos.vinil.origem", "Origem"},
        {"ficha_campos.vinil.peso_gramatura", "Gramatura"},
        {"ficha_campos.vinil.riscos_audiveis", "Riscos audíveis"},
        {"ficha_campos.vinil.selo", "Selo/gravadora original"},
        {"ficha_campos.vinil.toca_discos", "Toca-discos"},
        {"ficha_campos.vinil.velocidade", "Velocidade"},
        {"ficha_grupos.3d_file.arquivo", "Arquivo"},
        {"ficha_grupos.3d_file.especificacoes", "Especificações"},
        {"ficha_grupos.betacam.content", "Content"},
        {"ficha_grupos.betacam.digitization", "Digitization"},
        {"ficha_grupos.betacam.media", "Media"},
        {"ficha_grupos.betacam.physical_condition", "Physical condition"},
        {"ficha_grupos.betamax.content", "Content"},
        {"ficha_grupos.betamax.digitization", "Digitization"},
        {"ficha_grupos.betamax.media", "Media"},
        {"ficha_grupos.betamax.physical_condition", "Physical condition"},
        {"ficha_grupos.cassete.abrangencia", "Abrangência"},
        {"ficha_grupos.cassete.conteudo", "Conteúdo"},
        {"ficha_grupos.cassete.estado_fisico", "Estado físico"},
        {"ficha_grupos.cassete.reproducao", "Reprodução"},
        {"ficha_grupos.cassete.suporte", "Suporte"},
        {"ficha_grupos.cd.captura", "Captura"},
        {"ficha_grupos.cd.conteudo", "Conteúdo"},
        {"ficha_grupos.cd.estado_fisico", "Estado físico"},
        {"ficha_grupos.cd.suporte", "Suporte"},
        {"ficha_grupos.cover_art.direitos", "Direitos"},
        {"ficha_grupos.cover_art.identificacao", "Identificação"},
        {"ficha_grupos.cover_art.identification", "Identification"},
        {"ficha_grupos.cover_art.image", "Image"},
        {"ficha_grupos.cover_art.imagem", "Imagem"},
        {"ficha_grupos.cover_art.rights", "Rights"},
        {"ficha_grupos.dat.conteudo", "Conteúdo"},
        {"ficha_grupos.dat.estado_fisico", "Estado físico"},
        {"ficha_grupos.dat.reproducao", "Reprodução"},
        {"ficha_grupos.dat.suporte", "Suporte"},
        {"ficha_grupos.digital_audio.arquivo", "Arquivo"},
        {"ficha_grupos.digital_audio.conteudo", "Conteúdo"},
        {"ficha_grupos.digital_audio.origem_digital", "Origem digital"},
        {"ficha_grupos.digital_video.arquivo", "Arquivo"},
        {"ficha_grupos.digital_video.captura", "Captura"},
        {"ficha_grupos.digital_video.conteudo", "Conteúdo"},
        {"ficha_grupos.digital_video.especificacoes", "Especificações"},
        {"ficha_grupos.documento.estado", "Estado"},
        {"ficha_grupos.documento.identificacao", "Identificação"},
        {"ficha_grupos.documento.leitura_tecnica", "Leitura técnica"},
        {"ficha_grupos.dvd.content", "Content"},
        {"ficha_grupos.dvd.media", "Media"},
        {"ficha_grupos.dvd.physical_condition", "Physical condition"},
        {"ficha_grupos.dvd.technical", "Technical"},
        {"ficha_grupos.field_recording.ambiente", "Ambiente"},
        {"ficha_grupos.field_recording.captura", "Captura"},
        {"ficha_grupos.field_recording.conteudo", "Conteúdo"},
        {"ficha_grupos.filme.conteudo", "Conteúdo"},
        {"ficha_grupos.filme.digitalizacao_proveniencia_tecnica_11_5", "Digitalização (proveniência técnica, §11.5)"},
        {"ficha_grupos.filme.estado_fisico", "Estado físico"},
        {"ficha_grupos.filme.suporte", "Suporte"},
        {"ficha_grupos.fita_rolo.abrangencia", "Abrangência"},
        {"ficha_grupos.fita_rolo.conteudo", "Conteúdo"},
        {"ficha_grupos.fita_rolo.estado_fisico", "Estado físico"},
        {"ficha_grupos.fita_rolo.reproducao", "Reprodução"},
        {"ficha_grupos.fita_rolo.suporte", "Suporte"},
        {"ficha_grupos.foto.captura", "Captura"},
        {"ficha_grupos.foto.conteudo", "Conteúdo"},
        {"ficha_grupos.foto.direitos", "Direitos"},
        {"ficha_grupos.foto.estado_fisico", "Estado físico"},
        {"ficha_grupos.minidisc.conteudo", "Conteúdo"},
        {"ficha_grupos.minidisc.estado_fisico", "Estado físico"},
        {"ficha_grupos.minidisc.reproducao", "Reprodução"},
        {"ficha_grupos.minidisc.suporte", "Suporte"},
        {"ficha_grupos.negativo.conteudo", "Conteúdo"},
        {"ficha_grupos.negativo.digitalizacao", "Digitalização"},
        {"ficha_grupos.negativo.estado_fisico", "Estado físico"},
        {"ficha_grupos.negativo.suporte", "Suporte"},
        {"ficha_grupos.sample.classificacao", "Classificação"},
        {"ficha_grupos.sample.direitos_e_origem", "Direitos e origem"},
        {"ficha_grupos.sessao.identificacao", "Identificação"},
        {"ficha_grupos.slide.conteudo", "Conteúdo"},
        {"ficha_grupos.slide.digitalizacao", "Digitalização"},
        {"ficha_grupos.slide.estado_fisico", "Estado físico"},
        {"ficha_grupos.slide.suporte", "Suporte"},
        {"ficha_grupos.sound_effects.classificacao", "Classificação"},
        {"ficha_grupos.sound_effects.direitos", "Direitos"},
        {"ficha_grupos.umatic.content", "Content"},
        {"ficha_grupos.umatic.digitization", "Digitization"},
        {"ficha_grupos.umatic.media", "Media"},
        {"ficha_grupos.umatic.physical_condition", "Physical condition"},
        {"ficha_grupos.vhs.content", "Content"},
        {"ficha_grupos.vhs.digitization", "Digitization"},
        {"ficha_grupos.vhs.media", "Media"},
        {"ficha_grupos.vhs.physical_condition", "Physical condition"},
        {"ficha_grupos.video.conteudo", "Conteúdo"},
        {"ficha_grupos.video.digitalizacao_proveniencia_tecnica_11_5", "Digitalização (proveniência técnica, §11.5)"},
        {"ficha_grupos.video.estado_fisico", "Estado físico"},
        {"ficha_grupos.video.suporte", "Suporte"},
        {"ficha_grupos.vinil.conteudo", "Conteúdo"},
        {"ficha_grupos.vinil.estado_fisico", "Estado físico"},
        {"ficha_grupos.vinil.reproducao", "Reprodução"},
        {"ficha_grupos.vinil.suporte", "Suporte"},
        {"ficha_tipos.cassete", "Cassete"},
        {"ficha_tipos.cd", "CD"},
        {"ficha_tipos.cover_art", "Cover Art"},
        {"ficha_tipos.dat", "DAT"},
        {"ficha_tipos.digital_audio", "Áudio digital"},
        {"ficha_tipos.digital_video", "Vídeo digital"},
        {"ficha_tipos.documento", "Documento"},
        {"ficha_tipos.field_recording", "Gravação de campo"},
        {"ficha_tipos.filme", "Filme (16 mm / Super 8 / 8 mm)"},
        {"ficha_tipos.fita_rolo", "Fita de rolo"},
        {"ficha_tipos.foto", "Foto"},
        {"ficha_tipos.minidisc", "MiniDisc"},
        {"ficha_tipos.negativo", "Negativo fotográfico"},
        {"ficha_tipos.release", "Release fonográfico"},
        {"ficha_tipos.sample", "Sample"},
        {"ficha_tipos.slide", "Slide / diapositivo"},
        {"ficha_tipos.sound_effects", "Efeito sonoro"},
        {"ficha_tipos.video", "Vídeo analógico digitalizado"},
        {"ficha_tipos.vinil", "Vinil"},
        {"filtros.limpar", "Limpar filtros"},
        {"filtros.nome_colecao_mensagem", "Nome da coleção:"},
        {"filtros.nome_colecao_titulo", "Salvar coleção inteligente"},
        {"filtros.origem_analogico", "Analógico"},
        {"filtros.origem_digital", "Digital"},
        {"filtros.salvar_colecao", "Salvar busca atual…"},
        {"filtros.secao_colecoes", "Coleções inteligentes"},
        {"filtros.secao_colecoes_embutidas", "Coleções inteligentes"},
        {"filtros.secao_collection", "Conteúdo"},
        {"filtros.secao_content", "Conteúdo"},
        {"filtros.secao_extensao", "Tipo de arquivo"},
        {"filtros.secao_origem", "Origem"},
        {"filtros.secao_vaults", "Vaults"},
        {"grade.adicionar_material", "Adicionar material…"},
        {"grade.agrupar_automatico", "Agrupar: tipo"},
        {"grade.agrupar_por_ano", "Agrupar: ano"},
        {"grade.modo_grade", "Grade"},
        {"grade.modo_lista", "Lista"},
        {"grade.nao_classificado", "Não classificado"},
        {"grade.sem_ano", "Sem ano"},
        {"grade.tamanho_grande", "G"},
        {"grade.tamanho_lista", "Lista"},
        {"grade.tamanho_medio", "M"},
        {"grade.tamanho_pequeno", "P"},
        {"guia.backup_corpo", "Clique em Backup e escolha o disco de destino. O Matriz grava tudo na organização que você montou."},
        {"guia.backup_titulo", "Pronto pra gravar o backup"},
        {"guia.classificar_corpo", "Selecione vários (clique num, depois Shift+clique noutro) e use \"Editar em lote\" pra dar categoria e informações a todos de uma vez."},
        {"guia.classificar_titulo", "{n} arquivo(s) ainda sem categoria"},
        {"guia.mostrar", "Dica"},
        {"guia.ocultar", "Entendi"},
        {"guia.organizar_corpo", "Abra a aba BACKUP à esquerda, crie pastas no \"+\", e arraste pastas ou arquivos da EXPLORER pra dentro delas."},
        {"guia.organizar_titulo", "Agora monte a organização do backup"},
        {"guia.vazio_corpo", "Pode ser um HD inteiro, uma pasta ou arquivos soltos. Nada é movido nem apagado: o Matriz copia pra dentro do projeto e monta a visualização."},
        {"guia.vazio_titulo", "Comece arrastando seus arquivos pra cá"},
        {"hierarquia.acrescentar", "+ acrescentar nível…"},
        {"hierarquia.nivel_ano", "Ano"},
        {"hierarquia.nivel_artista", "Artista"},
        {"hierarquia.nivel_origem", "Origem"},
        {"hierarquia.nivel_pasta_manual", "Pastas que eu montei à mão"},
        {"hierarquia.nivel_projeto", "Projeto"},
        {"hierarquia.nivel_tipo_arquivo", "Tipo de arquivo"},
        {"hierarquia.nivel_tipo_midia", "Tipo de mídia"},
        {"hierarquia.titulo", "Estrutura de pastas do backup"},
        {"home.atencao_titulo", "PRECISA DE ATENÇÃO"},
        {"home.backup_desc", "Copie itens verificados para um destino seguro com verificação de integridade."},
        {"home.backup_titulo", "BACKUP"},
        {"home.catalog_desc", "Navegue, busque e edite metadados de itens já no acervo."},
        {"home.catalog_titulo", "GRADE"},
        {"home.ingest_desc", "Examine uma pasta, auto-classifique arquivos, revise exceções e registre itens — arquivos de origem permanecem intactos."},
        {"home.ingest_titulo", "ADICIONAR MÍDIA"},
        {"home.preservacao_desc", "Visualize estatísticas, métricas e análises do acervo."},
        {"home.preservacao_titulo", "ANÁLISE"},
        {"home.subtitulo", "O que você gostaria de fazer?"},
        {"home.titulo", "Início"},
        {"home.total_assets", "{0} itens no acervo"},
        {"home.total_assets_vazio", "Nenhum item no acervo ainda — comece adicionando mídia."},
        {"ingest.btn_importar", "IMPORTAR"},
        {"ingest.btn_proximo", "AVANÇAR"},
        {"ingest.btn_voltar", "VOLTAR"},
        {"ingest.cancelado", "Cancelado — {feito} de {total} processados. O que foi feito está salvo."},
        {"ingest.cancelando", "Cancelando…"},
        {"ingest.cancelar", "Cancelar"},
        {"ingest.concluido_assets", "{0} itens adicionados ao acervo"},
        {"ingest.concluido_titulo", "Importação Concluída"},
        {"ingest.concluido_ver_acervo", "VER ACERVO"},
        {"ingest.concluido_ver_novos", "VER NOVOS ITENS"},
        {"ingest.concluido_ver_problemas", "REVISAR PROBLEMAS"},
        {"ingest.concluido_ver_todos", "VER TODOS OS ITENS"},
        {"ingest.concluido_voltar_home", "VOLTAR AO INÍCIO"},
        {"ingest.descobre_analisando", "Analisando {0} de {1} arquivos..."},
        {"ingest.descobre_listando", "Examinando pasta..."},
        {"ingest.descobre_titulo", "Descobrindo e analisando arquivos"},
        {"ingest.erro_extensao_desconhecida", "extensão não reconhecida (tipo de mídia não pôde ser inferido)"},
        {"ingest.importando_progresso", "Gravando {0} de {1}..."},
        {"ingest.importando_titulo", "Importando itens"},
        {"ingest.ja_em_andamento", "Já existe um lote sendo ingerido. Aguarde terminar antes de iniciar outro."},
        {"ingest.nenhum_arquivo", "Nenhum arquivo compatível encontrado nesta pasta."},
        {"ingest.progresso", "Ingerindo… {feito}/{total}"},
        {"ingest.resumo_categorias", "{0} áudio | {1} vídeo | {2} imagens | {3} documentos | {4} outros"},
        {"ingest.resumo_duplicatas", "{n} já conhecido(s)"},
        {"ingest.resumo_erros", "{n} falharam"},
        {"ingest.resumo_novos", "{n} novo(s)"},
        {"ingest.review_aplicar_todos", "Aplicar a todos os similares"},
        {"ingest.review_nenhum", "Nada requer revisão — todos os arquivos foram auto-classificados."},
        {"ingest.review_titulo", "Revisar exceções"},
        {"ingest.selecionar_tipo_confirmar", "Ingerir"},
        {"ingest.selecionar_tipo_corpo", "{n} arquivo(s) selecionado(s). Qual o tipo de mídia de origem deste lote?"},
        {"ingest.selecionar_tipo_titulo", "Tipo de mídia"},
        {"ingest.source_arrastar", "Arraste uma pasta aqui ou clique para selecionar"},
        {"ingest.source_titulo", "Escolha a origem"},
        {"ingest.step_concluido", "Concluído"},
        {"ingest.step_descobre", "Descobrir"},
        {"ingest.step_importar", "Importar"},
        {"ingest.step_review", "Revisar"},
        {"ingest.step_source", "Origem"},
        {"ingest.step_verificar", "Verificar"},
        {"ingest.titulo", "Ingestão"},
        {"ingest.verificando_progresso", "Verificando {0} de {1}..."},
        {"ingest.verificando_titulo", "Verificando importação"},
        {"janela_principal.titulo", "BKR Matriz"},
        {"menu.ajuda", "Ajuda"},
        {"menu.arquivo", "Arquivo"},
        {"menu.arquivo_abrir_projeto", "Abrir projeto…"},
        {"menu.arquivo_fechar_projeto", "Fechar projeto"},
        {"menu.arquivo_ingerir_arquivos", "Adicionar arquivos…"},
        {"menu.arquivo_novo_projeto", "Novo projeto…"},
        {"menu.arquivo_sair", "Sair"},
        {"menu.audio_device", "Dispositivo de Áudio..."},
        {"menu.desfazer", "Desfazer (Cmd+Z)"},
        {"menu.editar", "Editar"},
        {"menu.exibir", "Exibir"},
        {"menu.exibir_tema_bkr_dark", "BKR Dark"},
        {"menu.exibir_tema_system_crt", "System CRT"},
        {"menu.log_projeto", "Registro do Projeto (log.md)..."},
        {"menu.preferencias", "Preferências"},
        {"menu.preferencias_gerais", "Preferências / Tema / Chave IA..."},
        {"menu.preferencias_idioma_ingles", "English"},
        {"menu.preferencias_idioma_portugues", "Português"},
        {"menu.projeto", "Projeto"},
        {"menu.projeto_configuracoes", "Configurações do projeto…"},
        {"menu.remover_backup", "Remover Selecionados do Backup (C)"},
        {"menu.sobre", "Sobre o BKR Matriz..."},
        {"menu.novo", "Novo"},
        {"menu.abrir", "Abrir"},
        {"menu.recentes", "Abrir Arquivos Recentes"},
        {"menu.sem_recentes", "Nenhum Arquivo Recente"},
        {"menu.salvar", "Salvar (Cmd+S)"},
        {"menu.salvar_como", "Salvar Como... (Cmd+Shift+S)"},
        {"menu.fechar", "Fechar"},
        {"menu.renomear_item", "Renomear Item(ns)... (R)"},
        {"metadados.bit_depth", "Profundidade"},
        {"metadados.canais", "Canais"},
        {"metadados.codec", "Codec"},
        {"metadados.criado_em", "Criado em"},
        {"metadados.dimensoes", "Dimensões"},
        {"metadados.duracao", "Duração"},
        {"metadados.editaveis", "Metadados do backup"},
        {"metadados.editaveis_ajuda", "o que você preenche"},
        {"metadados.extensao", "Extensão"},
        {"metadados.fps", "Quadros por segundo"},
        {"metadados.lossy", "Já vinha comprimido com perda"},
        {"metadados.mais", "+ {n} outros campos"},
        {"metadados.modificado_em", "Modificado em"},
        {"metadados.sample_rate", "Taxa de amostragem"},
        {"metadados.somente_leitura", "somente leitura"},
        {"metadados.tamanho", "Tamanho do arquivo"},
        {"metadados.tamanho_arquivo", "Tamanho do arquivo"},
        {"metadados.titulo", "Metadados originais"},
        {"metadados.vazio", "Este arquivo não trouxe metadado técnico legível."},
        {"metricas.bit_depth", "Bit depth"},
        {"metricas.bitrate", "Bitrate"},
        {"metricas.canais", "Canais"},
        {"metricas.codec", "Codec"},
        {"metricas.dimensao", "Dimensões"},
        {"metricas.duracao", "Duração"},
        {"metricas.espaco_cor", "Espaço de cor"},
        {"metricas.formato", "Formato"},
        {"metricas.fps", "FPS"},
        {"metricas.itens", "Itens"},
        {"metricas.lra", "LRA"},
        {"metricas.lufs_i", "LUFS-I"},
        {"metricas.paginas", "Páginas"},
        {"metricas.pico", "Pico"},
        {"metricas.profundidade", "Profundidade"},
        {"metricas.resolucao", "Resolução"},
        {"metricas.resumo_grade", "Na grade"},
        {"metricas.sample_rate", "Sample rate"},
        {"metricas.sem_arquivo", "Ainda sem arquivo"},
        {"metricas.tamanho", "Tamanho"},
        {"mosaico.buscar_placeholder", "Buscar"},
        {"mosaico.contagem_itens", "{n} itens"},
        {"mosaico.estado_alerta", "Alerta"},
        {"mosaico.estado_aprovado", "Aprovado"},
        {"mosaico.estado_arquivado", "Arquivado"},
        {"mosaico.estado_capturado", "Capturado"},
        {"mosaico.estado_catalogado", "Catalogado"},
        {"mosaico.estado_duplicata", "Já conhecido"},
        {"mosaico.estado_em_analise", "Em análise"},
        {"mosaico.estado_nao_digitalizado", "Não digitalizado"},
        {"mosaico.estado_novo", "Novo"},
        {"mosaico.estado_publicado", "Publicado"},
        {"mosaico.estado_qc_ok", "QC ok"},
        {"mosaico.estado_revisado", "Revisado"},
        {"mosaico.filtrar_estado", "Estado"},
        {"mosaico.filtrar_tipo", "Tipo de mídia"},
        {"mosaico.ordenar", "Ordenar por"},
        {"mosaico.ordenar_atualizado", "Atualizado recentemente"},
        {"mosaico.ordenar_codigo", "Código"},
        {"mosaico.ordenar_estado", "Estado"},
        {"mosaico.ordenar_titulo", "Título"},
        {"mosaico.solte_para_ingerir", "Solte para ingerir"},
        {"mosaico.todos", "Todos"},
        {"mosaico.vazio", "Nenhum item neste projeto ainda. Arraste arquivos aqui ou use Arquivo > Ingerir arquivos…"},
        {"nav.backup", "BACKUP"},
        {"nav.catalog", "CATÁLOGO"},
        {"nav.home", "INÍCIO"},
        {"nav.preservation", "PRESERVAÇÃO"},
        {"navegador.abrir", "Navegar arquivos…"},
        {"navegador.adicionar", "ADICIONAR AO BACKUP"},
        {"navegador.adicionar_n", "ADICIONAR {n} AO BACKUP"},
        {"navegador.buscar", "Buscar nesta pasta e nas subpastas"},
        {"navegador.filtro_audio", "Só áudio"},
        {"navegador.filtro_documento", "Só documentos"},
        {"navegador.filtro_imagem", "Só imagens"},
        {"navegador.filtro_todos", "Todos os arquivos"},
        {"navegador.filtro_video", "Só vídeo"},
        {"navegador.manter_estrutura", "Manter a estrutura de pastas"},
        {"navegador.ordem_data", "Ordem: data"},
        {"navegador.ordem_nome", "Ordem: nome"},
        {"navegador.ordem_tamanho", "Ordem: tamanho"},
        {"navegador.ordem_tipo", "Ordem: tipo"},
        {"navegador.previa_pasta", "Pasta"},
        {"navegador.previa_vazia", "Selecione algo pra ver a prévia."},
        {"navegador.resumo_selecao", "{n} arquivos, {tamanho}"},
        {"navegador.secao_favoritos", "FAVORITOS"},
        {"navegador.secao_recentes", "RECENTES"},
        {"navegador.secao_volumes", "VOLUMES"},
        {"navegador.selecao_vazia", "Nada selecionado."},
        {"navegador.titulo", "Adicionar ao backup"},
        {"navegador.vazio", "Nada aqui."},
        {"navegador.visao_colunas", "Colunas"},
        {"navegador.visao_icones", "Ícones"},
        {"navegador.visao_lista", "Lista"},
        {"painel_inconsistencias.titulo", "Precisa de atenção"},
        {"painel_inconsistencias.vazio", "Nada pendente por aqui — está tudo consistente."},
        {"preferencias.fechar", "FECHAR"},
        {"preferencias.idioma", "Idioma:"},
        {"preferencias.idioma_dica", "Selecione o idioma da interface"},
        {"preferencias.idioma_en", "English (EN-US)"},
        {"preferencias.idioma_pt_br", "Português do Brasil (PT-BR)"},
        {"preferencias.janela_titulo", "Preferências e Tema"},
        {"preferencias.salvar", "SALVAR E APLICAR"},
        {"preferencias.tema", "Aparência / Tema visual:"},
        {"preferencias.tema_dark", "Escuro (BKR Dark)"},
        {"preferencias.tema_light", "Claro (BKR Light)"},
        {"preferencias.titulo", "Preferências do Aplicativo"},
        {"preferencias.tooltips", "Exibir dicas de contexto (tooltips)"},
        {"preserv.checksum_problems", "Problemas de checksum"},
        {"preserv.health_critical", "CRÍTICO"},
        {"preserv.health_good", "BOM"},
        {"preserv.health_warning", "ALERTA"},
        {"preserv.incomplete", "Incompleto"},
        {"preserv.needs_backup", "Precisa de backup"},
        {"preserv.needs_review", "Precisa de revisão"},
        {"preserv.single_copy", "Cópia única (vulnerável)"},
        {"preserv.titulo", "Saúde do Acervo"},
        {"preserv.total_assets", "Total de itens"},
        {"preserv.verified", "Verificado"},
        {"preserv.view_in_catalog", "Ver no catálogo"},
        {"preview.dimensoes", "Dimensões"},
        {"preview.duracao", "Duração"},
        {"preview.pausar", "Pausar"},
        {"preview.sample_rate", "Taxa de amostragem"},
        {"preview.sem_arquivo", "Este item ainda não tem arquivo associado."},
        {"preview.sem_visualizacao", "Sem prévia disponível para este tipo de arquivo."},
        {"preview.tocar", "Tocar"},
        {"preview.video_sem_player", "Reprodução de vídeo ainda não implementada — mostrando o keyframe e os dados técnicos."},
        {"renomear_lote.adicionar_antes", "Antes do Nome"},
        {"renomear_lote.adicionar_depois", "Depois do Nome"},
        {"renomear_lote.campo_procurar", "Localizar:"},
        {"renomear_lote.campo_substituir_por", "Substituir por:"},
        {"renomear_lote.campo_texto", "Texto:"},
        {"renomear_lote.inserir_entre_prefixo_e_nome", "Entre Prefixo e Nome Original"},
        {"renomear_lote.previa", "Prévia: {nome}"},
        {"renomear_lote.renomear", "Renomear"},
        {"renomear_lote.substituir", "Substituir Texto"},
        {"renomear_lote.titulo", "Renomear em Lote"},
        {"selecao.contagem", "{n} arquivos selecionados"},
        {"selecao.contagem_um", "1 arquivo selecionado"},
        {"selecao.editar_lote", "Editar em lote"},
        {"selecao.limpar", "Limpar seleção"},
        {"selecao.selecionar_todos", "Selecionar todos"},
        {"tela_inicial.botao_abrir", "Abrir um projeto que já existe…"},
        {"tela_inicial.cartao_archive_descricao", "Fotos, vídeos, documentos, fitas, papéis digitalizados — material misturado que você quer guardar e achar depois."},
        {"tela_inicial.cartao_archive_publico", "Ex.: o HD com tudo o que você acumulou"},
        {"tela_inicial.cartao_archive_titulo", "ACERVO"},
        {"tela_inicial.cartao_catalog_descricao", "Discos, faixas, masters e samples — material que se organiza por artista e por lançamento."},
        {"tela_inicial.cartao_catalog_publico", "Ex.: o HD de projetos do estúdio"},
        {"tela_inicial.cartao_catalog_titulo", "CATÁLOGO"},
        {"tela_inicial.recente_modo_archive", "Arquivos variados"},
        {"tela_inicial.recente_modo_catalog", "Música"},
        {"tela_inicial.recentes_titulo", "Continuar de onde parou"},
        {"tela_inicial.subtitulo", "Escolha um dos dois e arraste seus arquivos. Dá pra mudar de ideia depois criando outro projeto."},
        {"tela_inicial.titulo", "O que você quer organizar?"},
        {"timeline.marcador", "+ Marcador"},
        {"timeline.marcador_apagar", "Apagar marcador"},
        {"timeline.marcador_dica", "O que este ponto indica?"},
        {"timeline.marcador_editar", "Editar texto"},
        {"timeline.sem_onda", "Sem forma de onda pra este arquivo."},
        {"timeline.timecode", "Timecode"},
        {"timeline.zoom_tudo", "Ver tudo"},
        {"transporte.fim", "END"},
        {"transporte.inicio", "START"},
        {"transporte.jog", "JOG"},
        {"transporte.play", "PLAY"},
        {"transporte.shuttle", "SHUTTLE"},
        {"transporte.stop", "STOP"},
        {"vault.backup_planejado", "{n} item(ns) adicionado(s) ao plano de backup deste disco — {total} no total"},
        {"vault.backup_planejado_falhou", "Não foi possível adicionar estes itens ao plano de backup"},
        {"vault.reconciliando", "Verificando o que mudou no disco reconectado..."},
    };
    return strings;
}

} // namespace matriz::i18n
