#pragma once

#include <unordered_map>
#include <string>

namespace matriz::i18n {

inline const std::unordered_map<std::string, std::string>& getPortugueseStrings() {
    static const std::unordered_map<std::string, std::string> strings = {
        {"acoes.categorizar", "Categorizar…"},
        {"acoes.copiar_caminho", "Copiar caminho"},
        {"acoes.definir_capa", "Usar imagem como capa…"},
        {"acoes.enviar_para_pasta", "Enviar para pasta"},
        {"acoes.mostrar_na_origem", "Mostrar na origem"},
        {"acoes.origem_ausente_mensagem", "O arquivo veio de:\n{caminho}\n\nConecte o disco de origem para abrir a pasta."},
        {"acoes.origem_ausente_titulo", "Origem não está conectada"},
        {"acoes.preview", "Ver prévia"},
        {"acoes.remover_capa", "Remover capa"},
        {"acoes.remover_da_lista", "Remover desta lista"},
        {"acoes.remover_da_lista_mensagem", "{n} arquivo(s) somem desta lista e do projeto, junto com a ficha preenchida.\n\nNenhum arquivo é apagado do disco: o original na fonte continua onde está."},
        {"acoes.remover_da_lista_titulo", "Remover desta lista?"},
        {"acoes.remover_do_backup", "Remover da coleção"},
        {"acoes.remover_do_backup_mensagem", "{n} arquivo(s) saem das pastas da coleção e voltam para \"Ainda sem pasta\".\n\nNenhum arquivo é apagado do disco."},
        {"acoes.remover_do_backup_titulo", "Remover da coleção?"},
        {"acoes.renomear", "Renomear…"},
        {"acoes.renomear_mensagem", "Novo nome. É ele que vai virar o nome do arquivo no backup."},
        {"acoes.renomear_mensagem_lote", "Novo nome para os {n} arquivos. A máscara numera cada um automaticamente."},
        {"acoes.renomear_previa", "No backup vai ficar: {nome}"},
        {"acoes.renomear_titulo", "Renomear"},
        {"acoes.sem_duplicatas", "Nenhum outro arquivo do projeto tem este mesmo conteúdo."},
        {"acoes.sem_pastas", "Nenhuma pasta criada ainda — crie uma no \"+\" da aba BACKUP"},
        {"acoes.ver_duplicatas", "Ver duplicatas deste arquivo"},
        {"app.nome", "BKR Matriz"},
        {"arvore.aba_acervo", "BACKUP"},
        {"arvore.aba_origem", "EXPLORER"},
        {"arvore.achatar_estrutura", "Colocar tudo direto nesta pasta"},
        {"arvore.apagar_confirmar_mensagem", "Isto só apaga a pasta do plano de organização — nenhum arquivo em disco é tocado. Os arquivos que estavam nela continuam no projeto, só voltam pra \"Ainda sem pasta\"."},
        {"arvore.apagar_confirmar_titulo", "Apagar pasta?"},
        {"arvore.backup_dica", "A estrutura que você monta e que vai ser gravada no backup."},
        {"arvore.explorer_dica", "A estrutura real do disco de origem, como ela é. Nada aqui é editável."},
        {"arvore.incluir_subpastas", "Incluir subpastas"},
        {"arvore.manter_estrutura", "Manter a estrutura de pastas"},
        {"arvore.menu_apagar", "Apagar"},
        {"arvore.menu_nova_subpasta", "Nova subpasta"},
        {"arvore.menu_renomear", "Renomear"},
        {"arvore.mostrar_conteudo_grade", "EXIBIR CONTEÚDO NA GRADE"},
        {"arvore.nao_organizados", "Ainda sem pasta"},
        {"arvore.nome_nova_pasta_mensagem", "Nome da pasta:"},
        {"arvore.nome_nova_pasta_titulo", "Nova pasta"},
        {"arvore.nova_pasta", "Nova pasta"},
        {"arvore.pasta_raiz_auto", "Importados"},
        {"arvore.renomear_pasta_mensagem", "Novo nome:"},
        {"arvore.renomear_pasta_titulo", "Renomear pasta"},
        {"arvore.soltar_pasta_mensagem", "\"{pasta}\" tem {n} arquivo(s) em subpastas."},
        {"arvore.soltar_pasta_titulo", "Como trazer esta pasta?"},
        {"arvore.todos_os_materiais", "Todos os arquivos"},
        {"backup.btn_copiar", "INICIAR CÓPIA"},
        {"backup.btn_proximo", "AVANÇAR"},
        {"backup.btn_voltar", "VOLTAR"},
        {"backup.cancelar", "Cancelar"},
        {"backup.copiando_progresso", "Copiando {0} de {1}..."},
        {"backup.copiando_titulo", "Copiando arquivos"},
        {"backup.destino_titulo", "Escolha o destino"},
        {"backup.destino_vazio", "Nenhum volume disponível. Conecte um disco externo."},
        {"backup.done_falhas", "{0} arquivos falharam ao copiar"},
        {"backup.done_titulo", "Backup Concluído"},
        {"backup.done_verificados", "{0} arquivos copiados e verificados"},
        {"backup.escolha_colecao", "Uma coleção"},
        {"backup.escolha_precisa", "Precisa de backup"},
        {"backup.escolha_recentes", "Recém-adicionados"},
        {"backup.escolha_selecionados", "Arquivos selecionados"},
        {"backup.escolha_titulo", "O que incluir no backup"},
        {"backup.escolha_tudo", "Tudo"},
        {"backup.preview_espaco", "Espaço necessário: {0}  |  Disponível: {1}"},
        {"backup.preview_ja_copiados", "{0} já com backup (ignorados)"},
        {"backup.preview_novos", "{0} novos arquivos para copiar"},
        {"backup.preview_titulo", "Prévia do backup"},
        {"backup.step_copiar", "Copiar"},
        {"backup.step_destino", "Destino"},
        {"backup.step_done", "Concluído"},
        {"backup.step_escolha", "Seleção"},
        {"backup.step_preview", "Prévia"},
        {"backup.step_verificar", "Verificar"},
        {"backup.titulo", "Backup"},
        {"backup.verificando_progresso", "Verificando {0} de {1}..."},
        {"backup.verificando_titulo", "Verificando cópias"},
        {"backup.voltar_home", "VOLTAR AO INÍCIO"},
        {"barra.adicionar", "Adicionar arquivos"},
        {"barra.adicionar_dica", "Escolha uma pasta ou arquivos pra copiar pro projeto. Você também pode arrastar direto do Finder pra qualquer lugar desta janela."},
        {"barra.backup", "Backup"},
        {"barra.backup_dica", "Copia o original byte a byte pra outro disco, seguindo as pastas que você montou em BACKUP. A origem nunca é tocada."},
        {"barra.buscar", "Buscar por nome, código ou qualquer informação"},
        {"barra.contagem", "{visiveis} de {total} arquivos"},
        {"barra.contagem_filtrada", "{visiveis} de {total} arquivos  ·  filtro ativo"},
        {"barra.detalhes_dica", "Mostra ou esconde o painel lateral com as informações do que está selecionado."},
        {"barra.modo_visao_dica", "Alternar entre visualização em grade e lista"},
        {"barra.tamanho_dica", "Tamanho das miniaturas"},
        {"catalogo.abrir", "Abrir catálogo de backup…"},
        {"catalogo.ausente", "fonte ausente"},
        {"catalogo.cancelado", "Catálogo cancelado — {feito} de {total}. O que foi gravado está salvo."},
        {"catalogo.disponivel", "disponível"},
        {"catalogo.fechar", "Fechar catálogo"},
        {"catalogo.gerado", "Catálogo gravado — {n} materiais consultáveis sem o HD conectado."},
        {"catalogo.gerando", "Gerando catálogo… {feito}/{total}"},
        {"catalogo.gerar", "Gerar catálogo de consulta"},
        {"catalogo.gerar_ajuda", "Miniaturas, fichas e a localização de cada arquivo, gravadas junto com o backup. Ocupa {tamanho} e permite consultar o acervo com o HD desconectado."},
        {"catalogo.nao_e_catalogo", "Esta pasta não tem um catálogo do Matriz dentro."},
        {"catalogo.onde_esta_corpo", "{titulo}\n\nDisco: {volume}\nPasta: {local}\n\nCaminho completo:\n{caminho}\n\nConecte o disco para abrir o arquivo."},
        {"catalogo.onde_esta_titulo", "Onde este arquivo está"},
        {"catalogo.sem_resultado", "Nenhum material encontrado para esta busca."},
        {"catalogo.titulo", "Catálogo do backup"},
        {"catalogo.vazio", "Este catálogo está vazio."},
        {"catalogo.volume_desconhecido", "disco não identificado"},
        {"catwork.all", "TODOS OS ITENS"},
        {"catwork.audio", "Áudio"},
        {"catwork.back", "Voltar ao catálogo"},
        {"catwork.documents", "Documentos"},
        {"catwork.images", "Imagens"},
        {"catwork.needs_review", "Precisa de revisão"},
        {"catwork.no_backup", "Sem backup"},
        {"catwork.offline", "Offline"},
        {"catwork.selected", "Arquivos selecionados"},
        {"catwork.sessions", "Sessões"},
        {"catwork.single_copy", "Cópia única"},
        {"catwork.source_structure", "Estrutura de origem"},
        {"catwork.video", "Vídeo"},
        {"colecoes.ausentes", "Ausentes"},
        {"colecoes.clipping", "Clipping"},
        {"colecoes.incompletos", "Incompletos"},
        {"colecoes.nao_baixados", "Não baixados"},
        {"colecoes.revisao", "Precisa de revisão"},
        {"colecoes.vulneraveis", "Sem backup ainda"},
        {"comum.cancelar", "Cancelar"},
        {"comum.erro", "Erro"},
        {"comum.nao", "Não"},
        {"comum.ok", "OK"},
        {"comum.salvar", "Salvar"},
        {"comum.sim", "Sim"},
        {"configuracoes_projeto.aviso_sobrescrever_cancelar", "Cancelar"},
        {"configuracoes_projeto.aviso_sobrescrever_confirmar", "Entendi, permitir mesmo assim"},
        {"configuracoes_projeto.aviso_sobrescrever_corpo", "Ligar esta opção permite que o master original seja sobrescrito diretamente, sem passar por uma derivada. Isso desliga a garantia padrão de preservação (dois arquivos por padrão, P1) — o arquivo original deixa de estar protegido contra sobrescrita acidental. É uma decisão do responsável pelo projeto: o software avisa uma única vez, aqui, e não pergunta de novo depois de confirmada."},
        {"configuracoes_projeto.aviso_sobrescrever_titulo", "Atenção: sobrescrita de master"},
        {"configuracoes_projeto.botao_fechar", "Fechar"},
        {"configuracoes_projeto.campo_nome", "Nome do projeto"},
        {"configuracoes_projeto.campo_permitir_sobrescrever", "Permitir sobrescrever master"},
        {"configuracoes_projeto.secao_geral", "Geral"},
        {"configuracoes_projeto.secao_master", "Master"},
        {"configuracoes_projeto.titulo", "Configurações do projeto"},
        {"consolidacao.aviso_conflitos", "{n} nome(s) repetido(s) — resolva antes de gravar."},
        {"consolidacao.aviso_espaco", "Precisa de: {necessario}  ·  Livre no destino: {disponivel}"},
        {"consolidacao.aviso_nao_organizados", "{n} arquivo(s) ainda fora de qualquer pasta da BACKUP — não entram neste backup."},
        {"consolidacao.cancelado", "Cancelado — {feito} de {total} processados. O que foi gravado está salvo e verificado."},
        {"consolidacao.consolidando", "Gravando… em acervos grandes isso pode demorar bastante."},
        {"consolidacao.consolidar", "Gravar backup"},
        {"consolidacao.destino_nao_escolhido", "Escolha o disco ou a pasta onde o backup vai ser gravado."},
        {"consolidacao.escolher_destino", "Escolher onde gravar…"},
        {"consolidacao.fechar", "Fechar"},
        {"consolidacao.ja_consolidado", "já copiado"},
        {"consolidacao.previa_vazia", "Ainda não há nada pra gravar. Arraste pastas ou arquivos da EXPLORER pras pastas da BACKUP, à esquerda — é essa organização que vira o backup."},
        {"consolidacao.progresso", "Gravando… {feito}/{total}"},
        {"consolidacao.resultado", "{consolidados} copiados, {pulados} já estavam em dia"},
        {"consolidacao.resultado_falhas", "{n} falharam"},
        {"consolidacao.titulo", "Backup"},
        {"dialogo_abrir_projeto.botao_escolher", "Escolher pasta do projeto…"},
        {"dialogo_abrir_projeto.erro_titulo", "Não foi possível abrir o projeto"},
        {"dialogo_abrir_projeto.titulo", "Abrir projeto"},
        {"dialogo_novo_projeto.botao_cancelar", "Cancelar"},
        {"dialogo_novo_projeto.botao_criar", "Criar projeto"},
        {"dialogo_novo_projeto.botao_escolher_pasta", "Escolher pasta…"},
        {"dialogo_novo_projeto.campo_instituicao", "Instituição ou selo (opcional)"},
        {"dialogo_novo_projeto.campo_isrc", "Registrante ISRC (opcional)"},
        {"dialogo_novo_projeto.campo_modo_catalogo", "Novo projeto de música"},
        {"dialogo_novo_projeto.campo_modo_preservacao", "Novo projeto de arquivos variados"},
        {"dialogo_novo_projeto.campo_nome", "Nome do projeto"},
        {"dialogo_novo_projeto.campo_pasta", "Pasta de backup"},
        {"dialogo_novo_projeto.campo_pasta_ajuda", "Uma pasta nova, num disco com espaço. É pra lá que seus arquivos serão copiados — os originais não são movidos nem apagados."},
        {"dialogo_novo_projeto.campo_prefixo", "Prefixo de nomenclatura"},
        {"dialogo_novo_projeto.campo_responsavel", "Responsável (opcional)"},
        {"dialogo_novo_projeto.erro_nome_vazio", "Dê um nome ao projeto pra continuar."},
        {"dialogo_novo_projeto.erro_pasta_vazia", "Escolha uma pasta onde o projeto vai ficar."},
        {"dialogo_novo_projeto.erro_prefixo_vazio", "O prefixo de nomenclatura é obrigatório."},
        {"dialogo_novo_projeto.erro_titulo", "Não foi possível criar o projeto"},
        {"dialogo_novo_projeto.titulo", "Novo projeto"},
        {"escuta.adicionar_marcador", "Adicionar Marcador"},
        {"escuta.arquivo_truncado", "Arquivo longo: apenas os primeiros 45 minutos foram carregados para reprodução"},
        {"escuta.correlacao", "CORRELAÇÃO"},
        {"escuta.espectro", "ESPECTRO"},
        {"escuta.fechar", "Fechar"},
        {"escuta.formato_nao_suportado", "Este formato de áudio não pode ser reproduzido aqui — o arquivo original permanece intacto"},
        {"escuta.loop_in", "Início do loop"},
        {"escuta.loop_limpar", "Limpar loop"},
        {"escuta.loop_out", "Fim do loop"},
        {"escuta.parar", "Parar"},
        {"escuta.sem_arquivo", "Este item ainda não tem arquivo anexado"},
        {"escuta.sem_forma_onda", "Nenhuma forma de onda em cache para este item"},
        {"escuta.tocar", "Reproduzir"},
        {"escuta.vault_offline", "Vault offline — reprodução desabilitada. O arquivo está em: {local}"},
        {"escuta.vetorscopio", "VETORSCÓPIO"},
        {"escuta.vu", "VU / PICO"},
        {"estado_vazio.rodape", "Seus arquivos originais não são movidos nem apagados — o Matriz faz uma cópia dentro do projeto."},
        {"estado_vazio.subtitulo", "ou clique aqui pra escolher no computador"},
        {"estado_vazio.titulo", "Arraste sua pasta ou seu HD pra cá"},
        {"ficha.alerta_rotulo", "Atenção"},
        {"ficha.alternar", "Detalhes"},
        {"ficha.arquivo_ausente", "ausente"},
        {"ficha.arquivo_obrigatorio", "obrigatório"},
        {"ficha.arquivo_presente", "presente"},
        {"ficha.cabecalho_sem_titulo", "(sem título)"},
        {"ficha.campo_booleano_nao", "Não"},
        {"ficha.campo_booleano_sim", "Sim"},
        {"ficha.herdado_do_projeto", "herdado do projeto"},
        {"ficha.lote_aplicar", "Aplicar"},
        {"ficha.lote_campos_nao_suportados", "Campos de tabela e lista de pessoas ainda não são editáveis em lote — edite item por item."},
        {"ficha.lote_desfazer", "Desfazer"},
        {"ficha.lote_escolher_tipo", "Nenhum dos materiais selecionados está classificado ainda. Escolha um tipo de mídia pra aplicar a todos:"},
        {"ficha.lote_nenhum_campo_tocado", "Edite um campo acima, depois aplique pra seleção inteira."},
        {"ficha.lote_previa", "{n} materiais serão alterados: {campos}"},
        {"ficha.lote_resultado", "{sucessos} alterados"},
        {"ficha.lote_resultado_desfeito", "{n} restaurados"},
        {"ficha.lote_resultado_falhas", ", {falhas} falharam"},
        {"ficha.lote_tipo_misto", "A seleção tem tipos de mídia diferentes. Selecione itens do mesmo tipo pra editar a ficha em lote."},
        {"ficha.lote_tipo_misto_universais", "A seleção tem tipos de mídia diferentes — só Origem e Ano existem em todos os tipos, então só esses podem ser editados juntos."},
        {"ficha.lote_titulo", "{n} materiais selecionados"},
        {"ficha.lote_valores_multiplos", "Múltiplos valores"},
        {"ficha.nao_classificado", "Ainda não classificado. Escolha um tipo de mídia pra preencher a ficha:"},
        {"ficha.nivel_faixa_adicionar", "Adicionar faixa"},
        {"ficha.nivel_faixa_numero", "Faixa {n}"},
        {"ficha.nivel_faixa_remover", "Remover faixa"},
        {"ficha.observacao_minutagem_dica", "Minutagem (MM:SS, opcional)"},
        {"ficha.observacao_nova", "Nova observação"},
        {"ficha.opcao_livre_criar", "Criar \"{texto}\""},
        {"ficha.preenchido_por_leitura_tecnica", "leitura técnica"},
        {"ficha.recategorizar", "Trocar tipo"},
        {"ficha.recategorizar_titulo", "Escolha um novo tipo de mídia:"},
        {"ficha.secao_arquivos_esperados", "Arquivos esperados"},
        {"ficha.secao_observacoes", "Observações"},
        {"ficha.sugestao_confianca", "confiança {p}%"},
        {"ficha.sugestao_confirmar", "Confirmar"},
        {"ficha.sugestao_modelo", "modelo: {modelo} {versao}"},
        {"ficha.sugestao_rotulo", "sugestão"},
        {"ficha.tabela_adicionar_linha", "Adicionar linha"},
        {"ficha.tabela_remover_linha", "Remover"},
        {"ficha.vazia", "Clique num arquivo da grade pra ver e editar as informações dele aqui."},
        {"ficha_alertas.cassete.sticky_shed", "Requer tratamento térmico antes da reprodução"},
        {"ficha_alertas.filme.quebradico", "Manuseio requer cuidado especial — risco de quebra ou combustão em nitrato"},
        {"ficha_alertas.fita_rolo.sticky_shed", "Requer tratamento térmico antes da reprodução"},
        {"ficha_alertas.minidisc.atrac_lossy", "Fonte já é lossy — a digitalização não recupera qualidade perdida na gravação original"},
        {"ficha_campos.cassete.abrangencia", "Abrangência da gravação"},
        {"ficha_campos.cassete.ano", "Ano"},
        {"ficha_campos.cassete.deck", "Deck de reprodução"},
        {"ficha_campos.cassete.direcao", "Sentido capturado"},
        {"ficha_campos.cassete.dolby", "Redução de ruído"},
        {"ficha_campos.cassete.duracao_nominal", "Duração nominal"},
        {"ficha_campos.cassete.estado_geral", "Estado geral"},
        {"ficha_campos.cassete.fita_solta_enroscada", "Fita solta ou enroscada no mecanismo"},
        {"ficha_campos.cassete.idioma", "Idioma"},
        {"ficha_campos.cassete.marca", "Marca"},
        {"ficha_campos.cassete.natureza", "Natureza do conteúdo"},
        {"ficha_campos.cassete.origem", "Origem"},
        {"ficha_campos.cassete.sticky_shed", "Sinais de sticky shed"},
        {"ficha_campos.cassete.tipo_fita", "Tipo de fita"},
        {"ficha_campos.cassete.trecho_observacao", "Observação sobre o trecho"},
        {"ficha_campos.cassete.trecho_posicao", "Posição do trecho"},
        {"ficha_campos.cd.ano", "Ano"},
        {"ficha_campos.cd.estado_fisico", "Estado físico do disco"},
        {"ficha_campos.cd.idioma", "Idioma"},
        {"ficha_campos.cd.marca_midia", "Marca da mídia (se CD-R)"},
        {"ficha_campos.cd.natureza", "Natureza do conteúdo"},
        {"ficha_campos.cd.numero_faixas", "Número de faixas"},
        {"ficha_campos.cd.origem", "Origem"},
        {"ficha_campos.cd.ripagem_bit_exata_confirmada", "Ripagem bit-exata confirmada"},
        {"ficha_campos.cd.tipo_disco", "Tipo de disco"},
        {"ficha_campos.cd.toc", "TOC / duração total"},
        {"ficha_campos.cover_art.ano", "Year"},
        {"ficha_campos.cover_art.artista", "Artist"},
        {"ficha_campos.cover_art.designer", "Designer / photographer"},
        {"ficha_campos.cover_art.dimensoes", "Dimensions"},
        {"ficha_campos.cover_art.formato", "Format"},
        {"ficha_campos.cover_art.licenca", "License / use"},
        {"ficha_campos.cover_art.origem", "Origin"},
        {"ficha_campos.cover_art.resolucao", "Resolution"},
        {"ficha_campos.cover_art.tipo_arte", "Art type"},
        {"ficha_campos.cover_art.titulo_release", "Release title"},
        {"ficha_campos.dat.ano", "Ano"},
        {"ficha_campos.dat.caminho_captura", "Caminho de captura"},
        {"ficha_campos.dat.deck", "Deck de reprodução"},
        {"ficha_campos.dat.duracao_fita", "Duração nominal"},
        {"ficha_campos.dat.erros_leitura", "Erros de leitura durante a captura"},
        {"ficha_campos.dat.estado_geral", "Estado geral"},
        {"ficha_campos.dat.idioma", "Idioma"},
        {"ficha_campos.dat.marca", "Marca da fita"},
        {"ficha_campos.dat.natureza", "Natureza do conteúdo"},
        {"ficha_campos.dat.origem", "Origem"},
        {"ficha_campos.dat.sample_rate_original", "Sample rate original"},
        {"ficha_campos.dat.subcode_disponivel", "Subcode (start ID/programa) disponível"},
        {"ficha_campos.digital_audio.ano", "Ano"},
        {"ficha_campos.digital_audio.bit_depth_declarado", "Bit depth declarado"},
        {"ficha_campos.digital_audio.codec", "Codec"},
        {"ficha_campos.digital_audio.daw_origem", "DAW de origem"},
        {"ficha_campos.digital_audio.eh_mixdown_ou_stem", "Tipo de material"},
        {"ficha_campos.digital_audio.formato_arquivo", "Formato do arquivo"},
        {"ficha_campos.digital_audio.idioma", "Idioma"},
        {"ficha_campos.digital_audio.natureza", "Natureza do conteúdo"},
        {"ficha_campos.digital_audio.origem", "Origem"},
        {"ficha_campos.digital_audio.plugins_criticos", "Plugins críticos (dependência de sessão)"},
        {"ficha_campos.digital_audio.sample_rate_declarado", "Sample rate declarado"},
        {"ficha_campos.digital_video.ano", "Ano"},
        {"ficha_campos.digital_video.camera", "Câmera / modelo"},
        {"ficha_campos.digital_video.codec", "Codec"},
        {"ficha_campos.digital_video.contagem_poligonos", "Contagem de polígonos"},
        {"ficha_campos.digital_video.data_gravacao", "Data de gravação"},
        {"ficha_campos.digital_video.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.digital_video.formato", "Formato"},
        {"ficha_campos.digital_video.formato_container", "Formato do container"},
        {"ficha_campos.digital_video.frame_rate_declarado", "Frame rate declarado"},
        {"ficha_campos.digital_video.origem", "Origem"},
        {"ficha_campos.digital_video.possui_rig", "Possui rig"},
        {"ficha_campos.digital_video.possui_texturas", "Possui texturas"},
        {"ficha_campos.digital_video.resolucao", "Resolução"},
        {"ficha_campos.digital_video.software_origem", "Software de origem"},
        {"ficha_campos.documento.ano", "Ano"},
        {"ficha_campos.documento.assinado", "Assinado"},
        {"ficha_campos.documento.autor_documento", "Autor / emissor"},
        {"ficha_campos.documento.data_documento", "Data do documento"},
        {"ficha_campos.documento.estado_fisico", "Estado físico (se digitalizado de papel)"},
        {"ficha_campos.documento.idioma", "Idioma"},
        {"ficha_campos.documento.numero_paginas", "Número de páginas"},
        {"ficha_campos.documento.origem", "Origem"},
        {"ficha_campos.documento.texto_pesquisavel", "Texto pesquisável no PDF"},
        {"ficha_campos.documento.tipo_documento", "Tipo de documento"},
        {"ficha_campos.field_recording.ambiente", "Ambiente"},
        {"ficha_campos.field_recording.ano", "Ano"},
        {"ficha_campos.field_recording.condicoes", "Condições (vento, chuva, ruído de fundo)"},
        {"ficha_campos.field_recording.equipamento_gravador", "Gravador"},
        {"ficha_campos.field_recording.idioma", "Idioma"},
        {"ficha_campos.field_recording.microfone", "Microfone"},
        {"ficha_campos.field_recording.natureza", "Natureza do conteúdo"},
        {"ficha_campos.field_recording.origem", "Origem"},
        {"ficha_campos.field_recording.padrao_polar", "Padrão polar"},
        {"ficha_campos.filme.ano", "Ano"},
        {"ficha_campos.filme.bitola", "Bitola"},
        {"ficha_campos.filme.campo_entrelacado_detectado", "Campo entrelaçado detectado"},
        {"ficha_campos.filme.cor_pb", "Cor ou preto e branco"},
        {"ficha_campos.filme.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.filme.encolhimento", "Encolhimento da base"},
        {"ficha_campos.filme.estado_geral", "Estado geral"},
        {"ficha_campos.filme.fps_captura", "FPS do arquivo capturado"},
        {"ficha_campos.filme.fps_original_declarado", "FPS original declarado"},
        {"ficha_campos.filme.mofo", "Sinais de mofo"},
        {"ficha_campos.filme.origem", "Origem"},
        {"ficha_campos.filme.pulldown_detectado", "Pulldown 3:2 detectado"},
        {"ficha_campos.filme.quadro_duplicado_detectado", "Quadro duplicado detectado"},
        {"ficha_campos.filme.quebradico", "Material quebradiço (base de nitrato/acetato degradado)"},
        {"ficha_campos.filme.som_optico", "Possui trilha sonora óptica"},
        {"ficha_campos.fita_rolo.abrangencia", "Abrangência da gravação"},
        {"ficha_campos.fita_rolo.alinhamento", "Fita de alinhamento usada"},
        {"ficha_campos.fita_rolo.ano", "Ano"},
        {"ficha_campos.fita_rolo.curva", "Curva de equalização"},
        {"ficha_campos.fita_rolo.direcao", "Sentido"},
        {"ficha_campos.fita_rolo.emendas", "Emendas visíveis"},
        {"ficha_campos.fita_rolo.espessura", "Espessura"},
        {"ficha_campos.fita_rolo.estado_geral", "Estado geral"},
        {"ficha_campos.fita_rolo.formulacao", "Formulação"},
        {"ficha_campos.fita_rolo.idioma", "Idioma"},
        {"ficha_campos.fita_rolo.largura", "Largura"},
        {"ficha_campos.fita_rolo.maquina", "Máquina de reprodução"},
        {"ficha_campos.fita_rolo.marca", "Marca"},
        {"ficha_campos.fita_rolo.natureza", "Natureza do conteúdo"},
        {"ficha_campos.fita_rolo.origem", "Origem"},
        {"ficha_campos.fita_rolo.pistas", "Configuração de pistas"},
        {"ficha_campos.fita_rolo.print_through", "Print-through audível"},
        {"ficha_campos.fita_rolo.sticky_shed", "Sinais de sticky shed"},
        {"ficha_campos.fita_rolo.trecho_observacao", "Observação sobre o trecho"},
        {"ficha_campos.fita_rolo.trecho_posicao", "Posição do trecho"},
        {"ficha_campos.fita_rolo.velocidade", "Velocidade"},
        {"ficha_campos.foto.ano", "Ano"},
        {"ficha_campos.foto.camera", "Câmera / modelo"},
        {"ficha_campos.foto.danos", "Danos visíveis"},
        {"ficha_campos.foto.data_foto", "Data da foto"},
        {"ficha_campos.foto.dimensoes", "Dimensões"},
        {"ficha_campos.foto.estado_fisico", "Estado geral"},
        {"ficha_campos.foto.evento", "Evento"},
        {"ficha_campos.foto.fotografo", "Fotógrafo"},
        {"ficha_campos.foto.licenca", "Licença / uso"},
        {"ficha_campos.foto.local", "Local"},
        {"ficha_campos.foto.origem", "Origem"},
        {"ficha_campos.foto.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.foto.suporte", "Suporte"},
        {"ficha_campos.minidisc.ano", "Ano"},
        {"ficha_campos.minidisc.atrac_lossy", "Origem em ATRAC (lossy)"},
        {"ficha_campos.minidisc.caminho_captura", "Caminho de captura"},
        {"ficha_campos.minidisc.deck", "Deck de reprodução"},
        {"ficha_campos.minidisc.erros_leitura", "Erros de leitura durante a captura"},
        {"ficha_campos.minidisc.estado_geral", "Estado geral"},
        {"ficha_campos.minidisc.idioma", "Idioma"},
        {"ficha_campos.minidisc.marca", "Marca"},
        {"ficha_campos.minidisc.modo_gravacao", "Modo de gravação"},
        {"ficha_campos.minidisc.natureza", "Natureza do conteúdo"},
        {"ficha_campos.minidisc.origem", "Origem"},
        {"ficha_campos.minidisc.tipo_disco", "Tipo de disco"},
        {"ficha_campos.negativo.ano", "Ano"},
        {"ficha_campos.negativo.cor_pb", "Cor ou preto e branco"},
        {"ficha_campos.negativo.data_foto", "Data da foto"},
        {"ficha_campos.negativo.desvanecimento", "Desvanecimento de cor"},
        {"ficha_campos.negativo.dimensoes_scan", "Dimensões do escaneamento"},
        {"ficha_campos.negativo.estado_geral", "Estado geral"},
        {"ficha_campos.negativo.formato", "Formato"},
        {"ficha_campos.negativo.local", "Local"},
        {"ficha_campos.negativo.mofo", "Sinais de mofo"},
        {"ficha_campos.negativo.origem", "Origem"},
        {"ficha_campos.negativo.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.negativo.resolucao_scan", "Resolução do escaneamento"},
        {"ficha_campos.negativo.riscos", "Riscos visíveis"},
        {"ficha_campos.release.ano", "Ano"},
        {"ficha_campos.release.artista_principal", "Artista principal"},
        {"ficha_campos.release.compositores", "Compositores"},
        {"ficha_campos.release.data_lancamento", "Data de lançamento"},
        {"ficha_campos.release.duracao", "Duração"},
        {"ficha_campos.release.editora", "Editora"},
        {"ficha_campos.release.explicito", "Conteúdo explícito"},
        {"ficha_campos.release.formato", "Formato"},
        {"ficha_campos.release.genero", "Gênero"},
        {"ficha_campos.release.idioma", "Idioma"},
        {"ficha_campos.release.isrc", "ISRC"},
        {"ficha_campos.release.numero", "Número"},
        {"ficha_campos.release.numero_catalogo", "Número de catálogo"},
        {"ficha_campos.release.origem", "Origem"},
        {"ficha_campos.release.participacao", "Participação"},
        {"ficha_campos.release.selo", "Selo"},
        {"ficha_campos.release.splits", "Splits"},
        {"ficha_campos.release.titulo", "Título"},
        {"ficha_campos.release.upc_ean", "UPC/EAN"},
        {"ficha_campos.sample.ano", "Ano"},
        {"ficha_campos.sample.bpm", "BPM"},
        {"ficha_campos.sample.categoria", "Categoria"},
        {"ficha_campos.sample.licenca", "Licença"},
        {"ficha_campos.sample.origem", "Origem"},
        {"ficha_campos.sample.origem_texto", "Origem"},
        {"ficha_campos.sample.tipo_temporal", "Tipo temporal"},
        {"ficha_campos.sample.tonalidade", "Tonalidade"},
        {"ficha_campos.slide.ano", "Ano"},
        {"ficha_campos.slide.data_foto", "Data da foto"},
        {"ficha_campos.slide.desvanecimento", "Desvanecimento de cor"},
        {"ficha_campos.slide.dimensoes_scan", "Dimensões do escaneamento"},
        {"ficha_campos.slide.estado_geral", "Estado geral"},
        {"ficha_campos.slide.formato", "Formato"},
        {"ficha_campos.slide.fungo", "Sinais de fungo"},
        {"ficha_campos.slide.local", "Local"},
        {"ficha_campos.slide.moldura", "Moldura"},
        {"ficha_campos.slide.origem", "Origem"},
        {"ficha_campos.slide.pessoas_identificadas", "Pessoas identificadas"},
        {"ficha_campos.slide.resolucao_scan", "Resolução do escaneamento"},
        {"ficha_campos.sound_effects.ano", "Ano"},
        {"ficha_campos.sound_effects.biblioteca_origem", "Biblioteca de origem"},
        {"ficha_campos.sound_effects.categoria", "Categoria"},
        {"ficha_campos.sound_effects.licenca", "Licença"},
        {"ficha_campos.sound_effects.origem", "Origem"},
        {"ficha_campos.video.ano", "Ano"},
        {"ficha_campos.video.campo_entrelacado_detectado", "Campo entrelaçado detectado"},
        {"ficha_campos.video.cortes_cena_detectados", "Cortes de cena detectados"},
        {"ficha_campos.video.descricao_conteudo", "Descrição do conteúdo"},
        {"ficha_campos.video.dropout_frequente", "Dropout frequente"},
        {"ficha_campos.video.estado_geral", "Estado geral"},
        {"ficha_campos.video.fita_solta_enroscada", "Fita solta ou enroscada no mecanismo"},
        {"ficha_campos.video.formato_original", "Formato original"},
        {"ficha_campos.video.fps_captura", "FPS do arquivo capturado"},
        {"ficha_campos.video.origem", "Origem"},
        {"ficha_campos.video.pulldown_detectado", "Pulldown 3:2 detectado"},
        {"ficha_campos.video.quadro_duplicado_detectado", "Quadro duplicado detectado"},
        {"ficha_campos.video.sistema", "Sistema de cor"},
        {"ficha_campos.video.tbc_usado", "TBC usado na digitalização"},
        {"ficha_campos.vinil.ano", "Ano"},
        {"ficha_campos.vinil.cartucho", "Cartucho usado"},
        {"ficha_campos.vinil.curva", "Curva de equalização"},
        {"ficha_campos.vinil.empenado", "Empenado"},
        {"ficha_campos.vinil.estado_capa", "Estado da capa"},
        {"ficha_campos.vinil.estado_disco", "Estado do disco (Goldmine)"},
        {"ficha_campos.vinil.formato", "Formato"},
        {"ficha_campos.vinil.idioma", "Idioma"},
        {"ficha_campos.vinil.natureza", "Natureza do conteúdo"},
        {"ficha_campos.vinil.numero_catalogo", "Número de catálogo"},
        {"ficha_campos.vinil.origem", "Origem"},
        {"ficha_campos.vinil.peso_gramatura", "Gramatura"},
        {"ficha_campos.vinil.riscos_audiveis", "Riscos audíveis"},
        {"ficha_campos.vinil.selo", "Selo/gravadora original"},
        {"ficha_campos.vinil.toca_discos", "Toca-discos"},
        {"ficha_campos.vinil.velocidade", "Velocidade"},
        {"ficha_grupos.3d_file.arquivo", "Arquivo"},
        {"ficha_grupos.3d_file.especificacoes", "Especificações"},
        {"ficha_grupos.betacam.content", "Content"},
        {"ficha_grupos.betacam.digitization", "Digitization"},
        {"ficha_grupos.betacam.media", "Media"},
        {"ficha_grupos.betacam.physical_condition", "Physical condition"},
        {"ficha_grupos.betamax.content", "Content"},
        {"ficha_grupos.betamax.digitization", "Digitization"},
        {"ficha_grupos.betamax.media", "Media"},
        {"ficha_grupos.betamax.physical_condition", "Physical condition"},
        {"ficha_grupos.cassete.abrangencia", "Abrangência"},
        {"ficha_grupos.cassete.conteudo", "Conteúdo"},
        {"ficha_grupos.cassete.estado_fisico", "Estado físico"},
        {"ficha_grupos.cassete.reproducao", "Reprodução"},
        {"ficha_grupos.cassete.suporte", "Suporte"},
        {"ficha_grupos.cd.captura", "Captura"},
        {"ficha_grupos.cd.conteudo", "Conteúdo"},
        {"ficha_grupos.cd.estado_fisico", "Estado físico"},
        {"ficha_grupos.cd.suporte", "Suporte"},
        {"ficha_grupos.cover_art.direitos", "Direitos"},
        {"ficha_grupos.cover_art.identificacao", "Identificação"},
        {"ficha_grupos.cover_art.identification", "Identification"},
        {"ficha_grupos.cover_art.image", "Image"},
        {"ficha_grupos.cover_art.imagem", "Imagem"},
        {"ficha_grupos.cover_art.rights", "Rights"},
        {"ficha_grupos.dat.conteudo", "Conteúdo"},
        {"ficha_grupos.dat.estado_fisico", "Estado físico"},
        {"ficha_grupos.dat.reproducao", "Reprodução"},
        {"ficha_grupos.dat.suporte", "Suporte"},
        {"ficha_grupos.digital_audio.arquivo", "Arquivo"},
        {"ficha_grupos.digital_audio.conteudo", "Conteúdo"},
        {"ficha_grupos.digital_audio.origem_digital", "Origem digital"},
        {"ficha_grupos.digital_video.arquivo", "Arquivo"},
        {"ficha_grupos.digital_video.captura", "Captura"},
        {"ficha_grupos.digital_video.conteudo", "Conteúdo"},
        {"ficha_grupos.digital_video.especificacoes", "Especificações"},
        {"ficha_grupos.documento.estado", "Estado"},
        {"ficha_grupos.documento.identificacao", "Identificação"},
        {"ficha_grupos.documento.leitura_tecnica", "Leitura técnica"},
        {"ficha_grupos.dvd.content", "Content"},
        {"ficha_grupos.dvd.media", "Media"},
        {"ficha_grupos.dvd.physical_condition", "Physical condition"},
        {"ficha_grupos.dvd.technical", "Technical"},
        {"ficha_grupos.field_recording.ambiente", "Ambiente"},
        {"ficha_grupos.field_recording.captura", "Captura"},
        {"ficha_grupos.field_recording.conteudo", "Conteúdo"},
        {"ficha_grupos.filme.conteudo", "Conteúdo"},
        {"ficha_grupos.filme.digitalizacao_proveniencia_tecnica_11_5", "Digitalização (proveniência técnica, §11.5)"},
        {"ficha_grupos.filme.estado_fisico", "Estado físico"},
        {"ficha_grupos.filme.suporte", "Suporte"},
        {"ficha_grupos.fita_rolo.abrangencia", "Abrangência"},
        {"ficha_grupos.fita_rolo.conteudo", "Conteúdo"},
        {"ficha_grupos.fita_rolo.estado_fisico", "Estado físico"},
        {"ficha_grupos.fita_rolo.reproducao", "Reprodução"},
        {"ficha_grupos.fita_rolo.suporte", "Suporte"},
        {"ficha_grupos.foto.captura", "Captura"},
        {"ficha_grupos.foto.conteudo", "Conteúdo"},
        {"ficha_grupos.foto.direitos", "Direitos"},
        {"ficha_grupos.foto.estado_fisico", "Estado físico"},
        {"ficha_grupos.minidisc.conteudo", "Conteúdo"},
        {"ficha_grupos.minidisc.estado_fisico", "Estado físico"},
        {"ficha_grupos.minidisc.reproducao", "Reprodução"},
        {"ficha_grupos.minidisc.suporte", "Suporte"},
        {"ficha_grupos.negativo.conteudo", "Conteúdo"},
        {"ficha_grupos.negativo.digitalizacao", "Digitalização"},
        {"ficha_grupos.negativo.estado_fisico", "Estado físico"},
        {"ficha_grupos.negativo.suporte", "Suporte"},
        {"ficha_grupos.sample.classificacao", "Classificação"},
        {"ficha_grupos.sample.direitos_e_origem", "Direitos e origem"},
        {"ficha_grupos.sessao.identificacao", "Identificação"},
        {"ficha_grupos.slide.conteudo", "Conteúdo"},
        {"ficha_grupos.slide.digitalizacao", "Digitalização"},
        {"ficha_grupos.slide.estado_fisico", "Estado físico"},
        {"ficha_grupos.slide.suporte", "Suporte"},
        {"ficha_grupos.sound_effects.classificacao", "Classificação"},
        {"ficha_grupos.sound_effects.direitos", "Direitos"},
        {"ficha_grupos.umatic.content", "Content"},
        {"ficha_grupos.umatic.digitization", "Digitization"},
        {"ficha_grupos.umatic.media", "Media"},
        {"ficha_grupos.umatic.physical_condition", "Physical condition"},
        {"ficha_grupos.vhs.content", "Content"},
        {"ficha_grupos.vhs.digitization", "Digitization"},
        {"ficha_grupos.vhs.media", "Media"},
        {"ficha_grupos.vhs.physical_condition", "Physical condition"},
        {"ficha_grupos.video.conteudo", "Conteúdo"},
        {"ficha_grupos.video.digitalizacao_proveniencia_tecnica_11_5", "Digitalização (proveniência técnica, §11.5)"},
        {"ficha_grupos.video.estado_fisico", "Estado físico"},
        {"ficha_grupos.video.suporte", "Suporte"},
        {"ficha_grupos.vinil.conteudo", "Conteúdo"},
        {"ficha_grupos.vinil.estado_fisico", "Estado físico"},
        {"ficha_grupos.vinil.reproducao", "Reprodução"},
        {"ficha_grupos.vinil.suporte", "Suporte"},
        {"ficha_tipos.cassete", "Cassete"},
        {"ficha_tipos.cd", "CD"},
        {"ficha_tipos.cover_art", "Cover Art"},
        {"ficha_tipos.dat", "DAT"},
        {"ficha_tipos.digital_audio", "Áudio digital"},
        {"ficha_tipos.digital_video", "Vídeo digital"},
        {"ficha_tipos.documento", "Documento"},
        {"ficha_tipos.field_recording", "Gravação de campo"},
        {"ficha_tipos.filme", "Filme (16 mm / Super 8 / 8 mm)"},
        {"ficha_tipos.fita_rolo", "Fita de rolo"},
        {"ficha_tipos.foto", "Foto"},
        {"ficha_tipos.minidisc", "MiniDisc"},
        {"ficha_tipos.negativo", "Negativo fotográfico"},
        {"ficha_tipos.release", "Release fonográfico"},
        {"ficha_tipos.sample", "Sample"},
        {"ficha_tipos.slide", "Slide / diapositivo"},
        {"ficha_tipos.sound_effects", "Efeito sonoro"},
        {"ficha_tipos.video", "Vídeo analógico digitalizado"},
        {"ficha_tipos.vinil", "Vinil"},
        {"filtros.limpar", "Limpar filtros"},
        {"filtros.nome_colecao_mensagem", "Nome da coleção:"},
        {"filtros.nome_colecao_titulo", "Salvar coleção inteligente"},
        {"filtros.origem_analogico", "Analógico"},
        {"filtros.origem_digital", "Digital"},
        {"filtros.salvar_colecao", "Salvar busca atual…"},
        {"filtros.secao_colecoes", "Coleções inteligentes"},
        {"filtros.secao_colecoes_embutidas", "Coleções inteligentes"},
        {"filtros.secao_collection", "Conteúdo"},
        {"filtros.secao_content", "Conteúdo"},
        {"filtros.secao_extensao", "Tipo de arquivo"},
        {"filtros.secao_origem", "Origem"},
        {"filtros.secao_vaults", "Vaults"},
        {"grade.adicionar_material", "Adicionar material…"},
        {"grade.agrupar_automatico", "Agrupar: tipo"},
        {"grade.agrupar_por_ano", "Agrupar: ano"},
        {"grade.modo_grade", "Grade"},
        {"grade.modo_lista", "Lista"},
        {"grade.nao_classificado", "Não classificado"},
        {"grade.sem_ano", "Sem ano"},
        {"grade.tamanho_grande", "G"},
        {"grade.tamanho_lista", "Lista"},
        {"grade.tamanho_medio", "M"},
        {"grade.tamanho_pequeno", "P"},
        {"guia.backup_corpo", "Clique em Backup e escolha o disco de destino. O Matriz grava tudo na organização que você montou."},
        {"guia.backup_titulo", "Pronto pra gravar o backup"},
        {"guia.classificar_corpo", "Selecione vários (clique num, depois Shift+clique noutro) e use \"Editar em lote\" pra dar categoria e informações a todos de uma vez."},
        {"guia.classificar_titulo", "{n} arquivo(s) ainda sem categoria"},
        {"guia.mostrar", "Dica"},
        {"guia.ocultar", "Entendi"},
        {"guia.organizar_corpo", "Abra a aba BACKUP à esquerda, crie pastas no \"+\", e arraste pastas ou arquivos da EXPLORER pra dentro delas."},
        {"guia.organizar_titulo", "Agora monte a organização do backup"},
        {"guia.vazio_corpo", "Pode ser um HD inteiro, uma pasta ou arquivos soltos. Nada é movido nem apagado: o Matriz copia pra dentro do projeto e monta a visualização."},
        {"guia.vazio_titulo", "Comece arrastando seus arquivos pra cá"},
        {"hierarquia.acrescentar", "+ acrescentar nível…"},
        {"hierarquia.nivel_ano", "Ano"},
        {"hierarquia.nivel_artista", "Artista"},
        {"hierarquia.nivel_origem", "Origem"},
        {"hierarquia.nivel_pasta_manual", "Pastas que eu montei à mão"},
        {"hierarquia.nivel_projeto", "Projeto"},
        {"hierarquia.nivel_tipo_arquivo", "Tipo de arquivo"},
        {"hierarquia.nivel_tipo_midia", "Tipo de mídia"},
        {"hierarquia.titulo", "Estrutura de pastas do backup"},
        {"home.atencao_titulo", "PRECISA DE ATENÇÃO"},
        {"home.backup_desc", "Copie itens verificados para um destino seguro com verificação de integridade."},
        {"home.backup_titulo", "BACKUP"},
        {"home.catalog_desc", "Navegue, busque e edite metadados de itens já no acervo."},
        {"home.catalog_titulo", "GRADE"},
        {"home.ingest_desc", "Examine uma pasta, auto-classifique arquivos, revise exceções e registre itens — arquivos de origem permanecem intactos."},
        {"home.ingest_titulo", "ADICIONAR MÍDIA"},
        {"home.preservacao_desc", "Visualize estatísticas, métricas e análises do acervo."},
        {"home.preservacao_titulo", "ANÁLISE"},
        {"home.subtitulo", "O que você gostaria de fazer?"},
        {"home.titulo", "Início"},
        {"home.total_assets", "{0} itens no acervo"},
        {"home.total_assets_vazio", "Nenhum item no acervo ainda — comece adicionando mídia."},
        {"ingest.btn_importar", "IMPORTAR"},
        {"ingest.btn_proximo", "AVANÇAR"},
        {"ingest.btn_voltar", "VOLTAR"},
        {"ingest.cancelado", "Cancelado — {feito} de {total} processados. O que foi feito está salvo."},
        {"ingest.cancelando", "Cancelando…"},
        {"ingest.cancelar", "Cancelar"},
        {"ingest.concluido_assets", "{0} itens adicionados ao acervo"},
        {"ingest.concluido_titulo", "Importação Concluída"},
        {"ingest.concluido_ver_acervo", "VER ACERVO"},
        {"ingest.concluido_ver_novos", "VER NOVOS ITENS"},
        {"ingest.concluido_ver_problemas", "REVISAR PROBLEMAS"},
        {"ingest.concluido_ver_todos", "VER TODOS OS ITENS"},
        {"ingest.concluido_voltar_home", "VOLTAR AO INÍCIO"},
        {"ingest.descobre_analisando", "Analisando {0} de {1} arquivos..."},
        {"ingest.descobre_listando", "Examinando pasta..."},
        {"ingest.descobre_titulo", "Descobrindo e analisando arquivos"},
        {"ingest.erro_extensao_desconhecida", "extensão não reconhecida (tipo de mídia não pôde ser inferido)"},
        {"ingest.importando_progresso", "Gravando {0} de {1}..."},
        {"ingest.importando_titulo", "Importando itens"},
        {"ingest.ja_em_andamento", "Já existe um lote sendo ingerido. Aguarde terminar antes de iniciar outro."},
        {"ingest.nenhum_arquivo", "Nenhum arquivo compatível encontrado nesta pasta."},
        {"ingest.progresso", "Ingerindo… {feito}/{total}"},
        {"ingest.resumo_categorias", "{0} áudio | {1} vídeo | {2} imagens | {3} documentos | {4} outros"},
        {"ingest.resumo_duplicatas", "{n} já conhecido(s)"},
        {"ingest.resumo_erros", "{n} falharam"},
        {"ingest.resumo_novos", "{n} novo(s)"},
        {"ingest.review_aplicar_todos", "Aplicar a todos os similares"},
        {"ingest.review_nenhum", "Nada requer revisão — todos os arquivos foram auto-classificados."},
        {"ingest.review_titulo", "Revisar exceções"},
        {"ingest.selecionar_tipo_confirmar", "Ingerir"},
        {"ingest.selecionar_tipo_corpo", "{n} arquivo(s) selecionado(s). Qual o tipo de mídia de origem deste lote?"},
        {"ingest.selecionar_tipo_titulo", "Tipo de mídia"},
        {"ingest.source_arrastar", "Arraste uma pasta aqui ou clique para selecionar"},
        {"ingest.source_titulo", "Escolha a origem"},
        {"ingest.step_concluido", "Concluído"},
        {"ingest.step_descobre", "Descobrir"},
        {"ingest.step_importar", "Importar"},
        {"ingest.step_review", "Revisar"},
        {"ingest.step_source", "Origem"},
        {"ingest.step_verificar", "Verificar"},
        {"ingest.titulo", "Ingestão"},
        {"ingest.verificando_progresso", "Verificando {0} de {1}..."},
        {"ingest.verificando_titulo", "Verificando importação"},
        {"janela_principal.titulo", "BKR Matriz"},
        {"menu.ajuda", "Ajuda"},
        {"menu.arquivo", "Arquivo"},
        {"menu.arquivo_abrir_projeto", "Abrir projeto…"},
        {"menu.arquivo_fechar_projeto", "Fechar projeto"},
        {"menu.arquivo_ingerir_arquivos", "Adicionar arquivos…"},
        {"menu.arquivo_novo_projeto", "Novo projeto…"},
        {"menu.arquivo_sair", "Sair"},
        {"menu.audio_device", "Dispositivo de Áudio..."},
        {"menu.desfazer", "Desfazer (Cmd+Z)"},
        {"menu.editar", "Editar"},
        {"menu.exibir", "Exibir"},
        {"menu.exibir_tema_bkr_dark", "BKR Dark"},
        {"menu.exibir_tema_system_crt", "System CRT"},
        {"menu.log_projeto", "Registro do Projeto (log.md)..."},
        {"menu.preferencias", "Preferências"},
        {"menu.preferencias_gerais", "Preferências / Tema / Chave IA..."},
        {"menu.preferencias_idioma_ingles", "English"},
        {"menu.preferencias_idioma_portugues", "Português"},
        {"menu.projeto", "Projeto"},
        {"menu.projeto_configuracoes", "Configurações do projeto…"},
        {"menu.remover_backup", "Remover Selecionados do Backup (C)"},
        {"menu.sobre", "Sobre o BKR Matriz..."},
        {"menu.novo", "Novo"},
        {"menu.abrir", "Abrir"},
        {"menu.recentes", "Abrir Arquivos Recentes"},
        {"menu.sem_recentes", "Nenhum Arquivo Recente"},
        {"menu.salvar", "Salvar (Cmd+S)"},
        {"menu.salvar_como", "Salvar Como... (Cmd+Shift+S)"},
        {"menu.fechar", "Fechar"},
        {"menu.renomear_item", "Renomear Item(ns)... (R)"},
        {"metadados.bit_depth", "Profundidade"},
        {"metadados.canais", "Canais"},
        {"metadados.codec", "Codec"},
        {"metadados.criado_em", "Criado em"},
        {"metadados.dimensoes", "Dimensões"},
        {"metadados.duracao", "Duração"},
        {"metadados.editaveis", "Metadados do backup"},
        {"metadados.editaveis_ajuda", "o que você preenche"},
        {"metadados.extensao", "Extensão"},
        {"metadados.fps", "Quadros por segundo"},
        {"metadados.lossy", "Já vinha comprimido com perda"},
        {"metadados.mais", "+ {n} outros campos"},
        {"metadados.modificado_em", "Modificado em"},
        {"metadados.sample_rate", "Taxa de amostragem"},
        {"metadados.somente_leitura", "somente leitura"},
        {"metadados.tamanho", "Tamanho do arquivo"},
        {"metadados.tamanho_arquivo", "Tamanho do arquivo"},
        {"metadados.titulo", "Metadados originais"},
        {"metadados.vazio", "Este arquivo não trouxe metadado técnico legível."},
        {"metricas.bit_depth", "Bit depth"},
        {"metricas.bitrate", "Bitrate"},
        {"metricas.canais", "Canais"},
        {"metricas.codec", "Codec"},
        {"metricas.dimensao", "Dimensões"},
        {"metricas.duracao", "Duração"},
        {"metricas.espaco_cor", "Espaço de cor"},
        {"metricas.formato", "Formato"},
        {"metricas.fps", "FPS"},
        {"metricas.itens", "Itens"},
        {"metricas.lra", "LRA"},
        {"metricas.lufs_i", "LUFS-I"},
        {"metricas.paginas", "Páginas"},
        {"metricas.pico", "Pico"},
        {"metricas.profundidade", "Profundidade"},
        {"metricas.resolucao", "Resolução"},
        {"metricas.resumo_grade", "Na grade"},
        {"metricas.sample_rate", "Sample rate"},
        {"metricas.sem_arquivo", "Ainda sem arquivo"},
        {"metricas.tamanho", "Tamanho"},
        {"mosaico.buscar_placeholder", "Buscar"},
        {"mosaico.contagem_itens", "{n} itens"},
        {"mosaico.estado_alerta", "Alerta"},
        {"mosaico.estado_aprovado", "Aprovado"},
        {"mosaico.estado_arquivado", "Arquivado"},
        {"mosaico.estado_capturado", "Capturado"},
        {"mosaico.estado_catalogado", "Catalogado"},
        {"mosaico.estado_duplicata", "Já conhecido"},
        {"mosaico.estado_em_analise", "Em análise"},
        {"mosaico.estado_nao_digitalizado", "Não digitalizado"},
        {"mosaico.estado_novo", "Novo"},
        {"mosaico.estado_publicado", "Publicado"},
        {"mosaico.estado_qc_ok", "QC ok"},
        {"mosaico.estado_revisado", "Revisado"},
        {"mosaico.filtrar_estado", "Estado"},
        {"mosaico.filtrar_tipo", "Tipo de mídia"},
        {"mosaico.ordenar", "Ordenar por"},
        {"mosaico.ordenar_atualizado", "Atualizado recentemente"},
        {"mosaico.ordenar_codigo", "Código"},
        {"mosaico.ordenar_estado", "Estado"},
        {"mosaico.ordenar_titulo", "Título"},
        {"mosaico.solte_para_ingerir", "Solte para ingerir"},
        {"mosaico.todos", "Todos"},
        {"mosaico.vazio", "Nenhum item neste projeto ainda. Arraste arquivos aqui ou use Arquivo > Ingerir arquivos…"},
        {"nav.backup", "BACKUP"},
        {"nav.catalog", "CATÁLOGO"},
        {"nav.home", "INÍCIO"},
        {"nav.preservation", "PRESERVAÇÃO"},
        {"navegador.abrir", "Navegar arquivos…"},
        {"navegador.adicionar", "ADICIONAR AO BACKUP"},
        {"navegador.adicionar_n", "ADICIONAR {n} AO BACKUP"},
        {"navegador.buscar", "Buscar nesta pasta e nas subpastas"},
        {"navegador.filtro_audio", "Só áudio"},
        {"navegador.filtro_documento", "Só documentos"},
        {"navegador.filtro_imagem", "Só imagens"},
        {"navegador.filtro_todos", "Todos os arquivos"},
        {"navegador.filtro_video", "Só vídeo"},
        {"navegador.manter_estrutura", "Manter a estrutura de pastas"},
        {"navegador.ordem_data", "Ordem: data"},
        {"navegador.ordem_nome", "Ordem: nome"},
        {"navegador.ordem_tamanho", "Ordem: tamanho"},
        {"navegador.ordem_tipo", "Ordem: tipo"},
        {"navegador.previa_pasta", "Pasta"},
        {"navegador.previa_vazia", "Selecione algo pra ver a prévia."},
        {"navegador.resumo_selecao", "{n} arquivos, {tamanho}"},
        {"navegador.secao_favoritos", "FAVORITOS"},
        {"navegador.secao_recentes", "RECENTES"},
        {"navegador.secao_volumes", "VOLUMES"},
        {"navegador.selecao_vazia", "Nada selecionado."},
        {"navegador.titulo", "Adicionar ao backup"},
        {"navegador.vazio", "Nada aqui."},
        {"navegador.visao_colunas", "Colunas"},
        {"navegador.visao_icones", "Ícones"},
        {"navegador.visao_lista", "Lista"},
        {"painel_inconsistencias.titulo", "Precisa de atenção"},
        {"painel_inconsistencias.vazio", "Nada pendente por aqui — está tudo consistente."},
        {"preferencias.fechar", "FECHAR"},
        {"preferencias.idioma", "Idioma:"},
        {"preferencias.idioma_dica", "Selecione o idioma da interface"},
        {"preferencias.idioma_en", "English (EN-US)"},
        {"preferencias.idioma_pt_br", "Português do Brasil (PT-BR)"},
        {"preferencias.janela_titulo", "Preferências e Tema"},
        {"preferencias.salvar", "SALVAR E APLICAR"},
        {"preferencias.tema", "Aparência / Tema visual:"},
        {"preferencias.tema_dark", "Escuro (BKR Dark)"},
        {"preferencias.tema_light", "Claro (BKR Light)"},
        {"preferencias.titulo", "Preferências do Aplicativo"},
        {"preferencias.tooltips", "Exibir dicas de contexto (tooltips)"},
        {"preserv.checksum_problems", "Problemas de checksum"},
        {"preserv.health_critical", "CRÍTICO"},
        {"preserv.health_good", "BOM"},
        {"preserv.health_warning", "ALERTA"},
        {"preserv.incomplete", "Incompleto"},
        {"preserv.needs_backup", "Precisa de backup"},
        {"preserv.needs_review", "Precisa de revisão"},
        {"preserv.single_copy", "Cópia única (vulnerável)"},
        {"preserv.titulo", "Saúde do Acervo"},
        {"preserv.total_assets", "Total de itens"},
        {"preserv.verified", "Verificado"},
        {"preserv.view_in_catalog", "Ver no catálogo"},
        {"preview.dimensoes", "Dimensões"},
        {"preview.duracao", "Duração"},
        {"preview.pausar", "Pausar"},
        {"preview.sample_rate", "Taxa de amostragem"},
        {"preview.sem_arquivo", "Este item ainda não tem arquivo associado."},
        {"preview.sem_visualizacao", "Sem prévia disponível para este tipo de arquivo."},
        {"preview.tocar", "Tocar"},
        {"preview.video_sem_player", "Reprodução de vídeo ainda não implementada — mostrando o keyframe e os dados técnicos."},
        {"renomear_lote.adicionar_antes", "Antes do Nome"},
        {"renomear_lote.adicionar_depois", "Depois do Nome"},
        {"renomear_lote.campo_procurar", "Localizar:"},
        {"renomear_lote.campo_substituir_por", "Substituir por:"},
        {"renomear_lote.campo_texto", "Texto:"},
        {"renomear_lote.inserir_entre_prefixo_e_nome", "Entre Prefixo e Nome Original"},
        {"renomear_lote.previa", "Prévia: {nome}"},
        {"renomear_lote.renomear", "Renomear"},
        {"renomear_lote.substituir", "Substituir Texto"},
        {"renomear_lote.titulo", "Renomear em Lote"},
        {"selecao.contagem", "{n} arquivos selecionados"},
        {"selecao.contagem_um", "1 arquivo selecionado"},
        {"selecao.editar_lote", "Editar em lote"},
        {"selecao.limpar", "Limpar seleção"},
        {"selecao.selecionar_todos", "Selecionar todos"},
        {"tela_inicial.botao_abrir", "Abrir um projeto que já existe…"},
        {"tela_inicial.cartao_archive_descricao", "Fotos, vídeos, documentos, fitas, papéis digitalizados — material misturado que você quer guardar e achar depois."},
        {"tela_inicial.cartao_archive_publico", "Ex.: o HD com tudo o que você acumulou"},
        {"tela_inicial.cartao_archive_titulo", "ACERVO"},
        {"tela_inicial.cartao_catalog_descricao", "Discos, faixas, masters e samples — material que se organiza por artista e por lançamento."},
        {"tela_inicial.cartao_catalog_publico", "Ex.: o HD de projetos do estúdio"},
        {"tela_inicial.cartao_catalog_titulo", "CATÁLOGO"},
        {"tela_inicial.recente_modo_archive", "Arquivos variados"},
        {"tela_inicial.recente_modo_catalog", "Música"},
        {"tela_inicial.recentes_titulo", "Continuar de onde parou"},
        {"tela_inicial.subtitulo", "Escolha um dos dois e arraste seus arquivos. Dá pra mudar de ideia depois criando outro projeto."},
        {"tela_inicial.titulo", "O que você quer organizar?"},
        {"timeline.marcador", "+ Marcador"},
        {"timeline.marcador_apagar", "Apagar marcador"},
        {"timeline.marcador_dica", "O que este ponto indica?"},
        {"timeline.marcador_editar", "Editar texto"},
        {"timeline.sem_onda", "Sem forma de onda pra este arquivo."},
        {"timeline.timecode", "Timecode"},
        {"timeline.zoom_tudo", "Ver tudo"},
        {"transporte.fim", "END"},
        {"transporte.inicio", "START"},
        {"transporte.jog", "JOG"},
        {"transporte.play", "PLAY"},
        {"transporte.shuttle", "SHUTTLE"},
        {"transporte.stop", "STOP"},
        {"vault.backup_planejado", "{n} item(ns) adicionado(s) ao plano de backup deste disco — {total} no total"},
        {"vault.backup_planejado_falhou", "Não foi possível adicionar estes itens ao plano de backup"},
        {"vault.reconciliando", "Verificando o que mudou no disco reconectado..."},
        {"preferencias.janela_titulo", "Preferências e Tema"},
        {"preferencias.titulo", "Preferências do Aplicativo"},
        {"preferencias.idioma", "Idioma / Language:"},
        {"preferencias.tema", "Aparência / Tema da UI:"},
        {"preferencias.tema_dark", "Escuro (BKR Dark)"},
        {"preferencias.tema_light", "Claro (BKR Light)"},
        {"preferencias.tooltips", "Exibir dicas ao passar o mouse (tooltips)"},
        {"preferencias.salvar", "SALVAR E APLICAR"},
        {"preferencias.fechar", "FECHAR"},
        {"catwork.secao_library", "BIBLIOTECA"},
        {"catwork.folders", "Pastas"},
        {"catwork.duplicates", "Duplicatas"},
        {"catwork.secao_media_type", "TIPO DE MÍDIA"},
        {"catwork.secao_status", "ESTADO"},
        {"catwork.secao_date", "DATA"},
        {"catwork.secao_content", "CONTEÚDO"},
        {"catwork.data_from", "DE"},
        {"catwork.data_to", "ATÉ"},
        {"catwork.any_start", "Qualquer / Início"},
        {"catwork.any_end", "Qualquer / Fim"},
        {"comum.limpar", "Limpar"},
        {"comum.desconhecido", "Desconhecido"},
        {"catwork.selecionar_todos", "SELECIONAR TODOS"},
        {"catwork.desmarcar", "DESMARCAR TODOS"},
        {"catwork.destacar_editados_on", "Destacar Editados: ON"},
        {"catwork.destacar_editados_off", "Destacar Editados: OFF"},
        {"catwork.ocultar_editados_on", "Ocultar Editados: ON"},
        {"catwork.ocultar_editados_off", "Ocultar Editados: OFF"},
        {"menu.limpar_metadados", "Limpar Metadados (Resetar para Original)"},
        {"metadados.confirmar_limpar_titulo", "Limpar Metadados"},
        {"metadados.confirmar_limpar_msg", "Deseja restaurar os metadados originais da ingestão para os itens selecionados? Todas as alterações e tags adicionadas serão removidas."},
        {"backup.titulo_configuracao", "Configuração de Backup"},
        {"backup.titulo_catalogo", "Backup e Consolidação do Catálogo"},
        {"backup.secao_origem", "ORIGEM"},
        {"backup.secao_destino", "DESTINO"},
        {"backup.secao_organizacao", "ORGANIZAÇÃO"},
        {"backup.secao_opcoes", "OPÇÕES"},
        {"backup.origem_todos_projeto", "Todos os itens do projeto"},
        {"backup.origem_todos_catalogo", "Todos os itens do catálogo"},
        {"backup.origem_intake", "Itens do intake"},
        {"backup.origem_selecionados", "Selecionar Arquivos ({n})"},
        {"backup.origem_sem_backup", "Itens ainda sem backup"},
        {"backup.origem_de_conteudo", "Por conteúdo"},
        {"backup.escolher_pasta", "Escolher Pasta Personalizada..."},
        {"backup.preservar_estrutura", "Preservar Estrutura Original de Pastas"},
        {"backup.preservar_estrutura_dica", "Preserva a estrutura de pastas original da origem, desconsiderando ajustes da aba MAPA"},
        {"backup.usar_estrutura_mapa", "Usar a estrutura de pastas da aba MAPA"},
        {"backup.usar_estrutura_mapa_dica", "Organiza as pastas do backup conforme a árvore virtual configurada na aba MAPA"},
        {"backup.prefixo_arquivos", "Prefixo do nome dos arquivos:"},
        {"backup.prefixo_arquivos_dica", "Prefixo customizado para os arquivos consolidados no backup"},
        {"backup.sem_conteudo", "Sem conteúdo definido"},
        {"backup.manter_organizacao", "Manter organização do catálogo"},
        {"backup.verificar_checksum", "Verificar checksum após cópia (SHA-256)"},
        {"backup.gerar_banco_sqlite", "Gerar Banco de Dados do Catálogo de Backup (SQLite)"},
        {"backup.embutir_metadados", "Embutir metadados nos arquivos de backup (EXIF/XMP/iXML)"},
        {"backup.btn_exportar_metadados", "EXPORTAR METADADOS"},
        {"backup.btn_fazer_backup", "FAZER BACKUP"},
        {"backup.resumo_itens_espaco", "Itens: {n} | Espaço: {s}"},
        {"backup.ja_em_backup", "(já em backup)"},
        {"comum.fechar_projeto", "FECHAR PROJETO"},
        {"preferencias.idioma_en", "English (EN-US)"},
        {"preferencias.idioma_pt_br", "Português do Brasil (PT-BR)"},
        {"preferencias.idioma_dica", "Selecionar idioma da interface"},
        {"menu.novo", "Novo"},
        {"menu.abrir", "Abrir"},
        {"menu.recentes", "Abrir Recentes"},
        {"menu.sem_recentes", "Nenhum Arquivo Recente"},
        {"menu.salvar", "Salvar (Cmd+S)"},
        {"menu.salvar_como", "Salvar Como... (Cmd+Shift+S)"},
        {"menu.fechar", "Fechar"},
        {"menu.editar", "Editar"},
        {"menu.desfazer", "Desfazer (Cmd+Z)"},
        {"menu.renomear_item", "Renomear Item(ns)... (R)"},
        {"menu.remover_backup", "Remover Selecionados do Backup (C)"},
        {"menu.log_projeto", "Registro do Projeto (log.md)..."},
        {"menu.preferencias_gerais", "Preferências / Tema / Chave de IA..."},
        {"menu.audio_device", "Dispositivo de Áudio..."},
        {"menu.sobre", "Sobre o BKR Matriz..."},
        {"menu.agrupar_pasta", "Agrupar em Pasta"},
        {"menu.mover_para_pasta", "Mover para Pasta"},
        {"catwork.aba_metadata", "Metadados"},
        {"comum.tamanho", "TAMANHO"},
        {"duplicatas.btn_scan", "LOCALIZAR DUPLICATAS"},
        {"duplicatas.btn_scan_dica", "Iniciar verificação de duplicatas por atributos"},
        {"duplicatas.lbl_scope", "Varredura:"},
        {"duplicatas.scope_all", "TODOS OS ARQUIVOS"},
        {"duplicatas.scope_selected", "ARQUIVOS SELECIONADOS"},
        {"duplicatas.lbl_type", "Tipo:"},
        {"duplicatas.type_all", "TODOS OS ARQUIVOS"},
        {"duplicatas.type_image", "IMAGEM"},
        {"duplicatas.type_video", "VÍDEO"},
        {"duplicatas.type_audio", "ÁUDIO"},
        {"duplicatas.type_docs", "DOCUMENTOS"},
        {"duplicatas.type_sessions", "SESSÕES"},
        {"duplicatas.type_other", "OUTROS"},
        {"duplicatas.lbl_size", "Tamanho:"},
        {"duplicatas.size_none", "Sem Filtro de Tamanho"},
        {"duplicatas.size_bigger", "Tamanho maior que"},
        {"duplicatas.size_smaller", "Tamanho menor que"},
        {"duplicatas.size_equals", "Tamanho igual a"},
        {"duplicatas.btn_validate_all", "VALIDAR TODAS"},
        {"duplicatas.btn_dismiss_all", "IGNORAR TODAS"},
        {"duplicatas.btn_validate", "VALIDAR COMO DUPLICATA"},
        {"duplicatas.btn_dismiss", "NÃO É DUPLICATA (IGNORAR)"},
        {"duplicatas.possible_duplicate", "DUPLICATA EM POTENCIAL"},
        {"duplicatas.existing_original", "ORIGINAL EXISTENTE"},
        {"duplicatas.show_source", "MOSTRAR NA ORIGEM"},
        {"duplicatas.copy_path", "COPIAR CAMINHO"},
        {"duplicatas.title", "Título:"},
        {"duplicatas.code", "Código:"},
        {"duplicatas.format", "Formato:"},
        {"duplicatas.duration", "Duração:"},
        {"duplicatas.dimensions", "Dimensões:"},
        {"duplicatas.file_size", "Tamanho:"},
        {"duplicatas.orientation", "Orientação:"},
        {"duplicatas.color_space", "Espaço de Cores:"},
        {"duplicatas.path", "Caminho:"},
        {"duplicatas.collection", "COLEÇÃO:"},
        {"duplicatas.scanning", "Localizando candidatos a duplicata..."},
        {"duplicatas.nenhuma", "Nenhuma duplicata encontrada"},
        {"duplicatas.encontradas", "{n} pares de duplicatas encontrados"},
        {"duplicatas.offline", "Arquivo offline ou não encontrado"},
        {"duplicatas.imagem_invalida", "Arquivo de imagem inválido"},
        {"arvore_backup.titulo", "MAPA DE PASTAS"},
        {"arvore_backup.btn_importar", "\xe2\x86\xbb IMPORTAR / ATUALIZAR ESTRUTURA DE PASTAS"},
        {"arvore_backup.btn_criar_pasta", "+ NOVA PASTA"},
        {"arvore_backup.btn_renomear", "RENOMEAR"},
        {"arvore_backup.btn_apagar", "DELETE"},
        {"arvore_backup.btn_auto_arranjar", "AJUSTAR"},
        {"arvore_backup.btn_fit", "AJUSTAR"},
        {"arvore_backup.vazio", "A ÁRVORE está vazia. Clique em '+ NOVA PASTA' ou importe uma estrutura de pastas para preencher o gráfico."},
        {"arvore_backup.no_ativo", "PASTA [ATIVA]"},
        {"arvore_backup.no_desativado", "PASTA [DESATIVADA]"},
        {"arvore_backup.itens", "{n} itens"},
        {"arvore_backup.exibir_grade", "EXIBIR CONTEÚDO NA GRADE"},
        {"arvore_backup.subpastas", "SUBPASTAS"},
        {"arvore_backup.arquivos", "ARQUIVOS"},
        {"arvore_backup.pasta_vazia", "Pasta vazia"},
        {"arvore_backup.importar_msg", "Isso excluirá todas as pastas e conexões atuais e recriará a árvore de pastas a partir dos caminhos originais dos arquivos.\n\nQualquer organização personalizada será perdida.\n\nContinuar?"},
        {"arvore_backup.importar_btn", "Importar"},
        {"arvore_backup.cancelar_btn", "Cancelar"},
        {"arvore_backup.criar_pasta_titulo", "CRIAR PASTA"},
        {"arvore_backup.criar_pasta_msg", "Digite o nome da nova pasta:"},
        {"arvore_backup.criar_pasta_padrao", "Nova Pasta"},
        {"arvore_backup.renomear_pasta_titulo", "RENOMEAR PASTA"},
        {"arvore_backup.renomear_pasta_msg", "Digite o novo nome da pasta:"},
        {"arvore_backup.nova_subpasta", "+ Nova Subpasta"},
        {"arvore_backup.nova_subpasta_titulo", "NOVA SUBPASTA"},
        {"arvore_backup.nova_subpasta_msg", "Digite o nome da subpasta:"},
        {"arvore_backup.nova_subpasta_padrao", "Nova Subpasta"},
        {"arvore_backup.desconectar_pai", "Desconectar da Pasta Pai"},
        {"arvore_backup.renomear_pasta_menu", "Renomear Pasta..."},
        {"arvore_backup.alternar_ativo", "Alternar ATIVO / DESATIVADO"},
        {"arvore_backup.apagar_pasta_menu", "Excluir Pasta"},
        {"arvore_backup.falha_importar", "Falha ao importar estrutura: "},
        {"arvore_backup.zoom", "Zoom:"},
        {"arvore_backup.items", "itens"},
        {"analytics.titulo", "Análise da Coleção - Treemap Explorer"},
        {"analytics.total_assets", "TOTAL DE ATIVOS"},
        {"analytics.total_assets_sub", "Arquivos catalogados"},
        {"analytics.storage_size", "ESPAÇO EM DISCO"},
        {"analytics.storage_size_sub", "Volume ocupado"},
        {"analytics.primary_format", "FORMATO PRINCIPAL"},
        {"analytics.primary_format_sub", "{n} ativos"},
        {"analytics.needs_attention", "REQUER ATENÇÃO"},
        {"analytics.needs_attention_sub", "arquivos sem metadados obrigatórios"},
        {"analytics.backup_health", "ESTADO DO BACKUP"},
        {"analytics.backup_health_sub", "{n} vulneráveis (clique)"},
        {"analytics.btn_root", "RAIZ GLOBAL"},
        {"analytics.btn_up", "SUBIR"},
        {"analytics.stats", "CATÁLOGO TOTAL: {t} ATIVOS ({ts})  |  VISUALIZAÇÃO: {v} ({vs})"},
        {"analytics.all_assets", "TODOS OS ATIVOS"},
        {"analytics.vazio", "Nenhum ativo catalogado ainda."},
        {"analytics.cat_audio", "ÁUDIO"},
        {"analytics.cat_video", "VÍDEO"},
        {"analytics.cat_image", "IMAGEM"},
        {"analytics.cat_doc", "DOCUMENTO"},
        {"analytics.cat_text", "TEXTO"},
        {"analytics.cat_other", "OUTRO"},
        {"analytics.cat_total", "TOTAL DO CATÁLOGO (AGREGADO)"},
        {"analytics.colecoes", "COLEÇÕES ({n})"},
        {"analytics.sem_colecoes", "Nenhuma coleção vinculada ainda. Importe coleções na aba COLEÇÕES para visualizar análises consolidadas."},
        {"analytics.colecao_prefixo", "COLEÇÃO: "},
        {"analytics.vulneraveis_clique", "vulneráveis (clique)"},
        {"analytics.tooltip_name", "Nome: "},
        {"analytics.tooltip_size", "Tamanho: "},
        {"analytics.tooltip_media_type", "Tipo de Mídia: "},
        {"analytics.tooltip_extension", "Extensão: "},
        {"analytics.tooltip_path", "Caminho: "},
        {"analytics.ativos", "ativos"},
        {"storage.titulo", "STORAGE & MEDIA LOG"},
        {"storage.subtitulo", "Identidades de hardware, integridade dos discos e histórico em calendário das operações de Ingest e Backup."},
        {"storage.btn_refresh", "ATUALIZAR"},
        {"storage.col_source", "DISCOS DE ORIGEM (INGEST)"},
        {"storage.col_backup", "DISCOS DE BACKUP (DESTINO)"},
        {"storage.all_sessions", "Todas as sessões ({n} registros)"},
        {"storage.logs_for_date", "Registros de: {d} ({n} sessões)"},
        {"storage.btn_all_sessions", "Todas as sessões"},
        {"storage.btn_open_folder", "Abrir pasta de logs"},
        {"storage.col_date", "Data e hora"},
        {"storage.col_action", "Ação"},
        {"storage.col_operator", "Operador"},
        {"storage.col_volume", "Itens/vol"},
        {"storage.col_health", "Integridade"},
        {"storage.col_report", "LOG"},
        {"storage.model", "Modelo"},
        {"storage.serial", "Serial"},
        {"storage.mount", "Montagem"},
        {"storage.format", "Formato"},
        {"storage.connected", "Conectado"},
        {"storage.disconnected", "Desconectado"},
        {"storage.unmounted", "Offline / Desmontado"},
        {"storage.healthy", "Saudável"},
        {"storage.attention", "Atenção"},
        {"storage.critical", "Crítico"},
        {"storage.smart", "SMART"},
        {"storage.sensors", "Sensores"},
        {"storage.sectors", "Setores"},
        {"storage.used_free", "{u} usado ({p}%) \u00B7 {f} livre"},
        {"storage.files_count", "{n} arquivos"},
        {"storage.last", "último"},
        {"storage.backup_count", "{n} backup"},
        {"storage.backups_count", "{n} backups"},
        {"storage.empty_source", "Nenhuma mídia de origem registrada ainda.\nImporte arquivos ou mídias via INGESTÃO para registrar dispositivos de origem automaticamente."},
        {"storage.empty_backup", "Nenhum disco de backup registrado ainda.\nExecute um backup na aba BACKUP para registrar mídias físicas de destino."},
        {"storage.diag_titulo", "DIAGNÓSTICO DE REGISTRO DE STORAGE"},
        {"storage.temp_na", "Temp N/D"},
        {"storage.power", "ligado"},
        {"storage.realloc", "Realocados "},
        {"storage.pending", "Pendentes "},
        {"storage.not_supported", "Não suportado"},
        {"storage.passed", "Aprovado"},
        {"storage.failing", "Falhando"},
        {"storage.unknown", "Desconhecido"},
        {"storage.scanning_telemetry", "Escaneando telemetria ao vivo..."},
        {"storage.telemetry_unavailable", "Telemetria do volume indisponível"},
        {"storage.storage_device", "Dispositivo de Armazenamento"},
        {"storage.capacity", "Capacidade: "},
        {"intake.titulo", "LOTE DE INGESTÃO"},
        {"intake.ativos_contador", "{n} ativos no lote"},
        {"intake.btn_ingerir", "+ Ingerir Arquivos / Pastas"},
        {"intake.filtro_all", "Todos ({n})"},
        {"intake.filtro_audio", "Áudio ({n})"},
        {"intake.filtro_video", "Vídeo ({n})"},
        {"intake.filtro_image", "Imagens ({n})"},
        {"intake.filtro_doc", "Documentos ({n})"},
        {"intake.filtro_other", "Outros ({n})"},
        {"intake.selecionados", "{n} selecionados"},
        {"intake.selecionar_todos", "Selecionar tudo"},
        {"intake.limpar_selecao", "Limpar seleção"},
        {"intake.rotulo_conteudo", "Conteúdo:"},
        {"intake.btn_aplicar", "Aplicar"},
        {"intake.btn_origem_lote", "Mídia de origem..."},
        {"intake.btn_geo_lote", "Localização..."},
        {"intake.btn_enviar_catalogo", "Enviar para o Catálogo"},
        {"intake.btn_excluir_lote", "Remover do Lote"},
        {"intake.btn_enviar_selecionados", "Enviar selecionados para o GRID"},
        {"intake.btn_enviar_todos", "Enviar todos para o GRID"},
        {"intake.btn_rejeitar_selecionados", "Rejeitar selecionados"},
        {"intake.definir", "Definir..."},
        {"intake.popup_osm_batch", "MÍDIA DE ORIGEM ORIGINAL (LOTE)"},
        {"intake.popup_osm", "MÍDIA DE ORIGEM ORIGINAL"},
        {"intake.popup_geo_batch", "LOCALIZAÇÃO GEOGRÁFICA (SOBREPOSIÇÃO EM LOTE)"},
        {"intake.popup_geo", "LOCALIZAÇÃO GEOGRÁFICA"},
        {"intake.btn_aplicar_selecionados", "Aplicar aos Selecionados"},
        {"intake.sem_itens_filtro", "Nenhum item da ingestão corresponde ao filtro atual."},
        {"intake.nenhuma_colecao", "Nenhum"},
        {"intake.tooltip_lista", "Visualização em lista (tabela)"},
        {"intake.tooltip_icones", "Visualização em ícones (miniaturas)"},
        {"intake.tooltip_ingerir", "Importar mais arquivos ou pastas para a ingestão"},
        {"intake.col_select", ""},
        {"intake.col_type", "TIPO"},
        {"intake.col_name", "ATIVO / NOME DO ARQUIVO"},
        {"intake.col_date", "DATA DE CRIAÇÃO"},
        {"intake.col_size", "TAMANHO"},
        {"intake.col_path", "CAMINHO"},
        {"intake.col_collection", "CONTEÚDO"},
        {"intake.col_source_media", "MÍDIA DE ORIGEM ORIGINAL"},
        {"intake.col_action", "AÇÃO"},
        {"hub.titulo", "COLEÇÕES"},
        {"hub.subtitulo", "Coleções pertencentes a este catálogo. Abra qualquer coleção para gerenciar seus ativos ou importe novas coleções."},
        {"hub.btn_importar", "+ IMPORTAR COLEÇÃO..."},
        {"hub.btn_abrir", "ABRIR COLEÇÃO"},
        {"hub.btn_relocar", "LOCALIZAR COLEÇÃO..."},
        {"hub.btn_desvincular", "DESVINCULAR"},
        {"hub.btn_backup", "BACKUP CONSOLIDADO"},
        {"hub.col_status", "STATUS"},
        {"hub.col_nome", "NOME DA COLEÇÃO"},
        {"hub.col_grupo", "GRUPO"},
        {"hub.col_assets", "TOTAL DE ATIVOS"},
        {"hub.col_tamanho", "TAMANHO TOTAL"},
        {"hub.col_caminho", "LOCALIZAÇÃO / CAMINHO"},
        {"hub.resumo", "{c} coleção(ões) vinculada(s)  |  {a} ativos totais  |  {s}"},
        {"hub.dialog_importar_titulo", "Selecionar pasta do projeto de coleção para importar para o catálogo"},
        {"hub.dialog_invalida_titulo", "Pasta de Coleção Inválida"},
        {"hub.dialog_invalida_msg", "A pasta selecionada não é um diretório de projeto BKR válido (registro.sqlite ausente)."},
        {"hub.dialog_relocar_titulo", "Localizar pasta da coleção para: "},
        {"hub.dialog_relocar_invalida_msg", "A pasta selecionada não contém um banco de dados de coleção válido (registro.sqlite)."},
        {"preservacao.titulo_dashboard", "Painel de Preservação e Saúde do Acervo"},
        {"preservacao.subtitulo_dashboard", "Monitore integridade, status de backup, direitos e metadados."},
        {"preservacao.banner_status", "ESTADO DE SAÚDE DO ACERVO"},
        {"preservacao.status_bom", "BOM"},
        {"preservacao.status_alerta", "ATENÇÃO"},
        {"preservacao.status_critico", "CRÍTICO"},
        {"preservacao.card_total", "TOTAL DE ATIVOS"},
        {"preservacao.card_persistent_id", "IDENTIFICADOR PERSISTENTE"},
        {"preservacao.card_fixity_sha256", "SHA-256 CALCULADO"},
        {"preservacao.card_fixity_verificada", "FIXIDADE VERIFICADA"},
        {"preservacao.card_falha_integridade", "FALHAS DE INTEGRIDADE"},
        {"preservacao.card_formato_identificado", "FORMATO IDENTIFICADO"},
        {"preservacao.card_backup_verificado", "BACKUP VERIFICADO (PREMIS)"},
        {"preservacao.card_sem_backup", "SEM BACKUP VERIFICADO"},
        {"preservacao.card_direitos_desconhecidos", "DIREITOS DESCONHECIDOS"},
        {"preservacao.card_sem_fixity", "SEM SHA-256"},
        {"preservacao.card_eventos", "EVENTOS DE PRESERVAÇÃO"},
        {"preservacao.card_vulneraveis", "REQUER BACKUP (CÓPIA ÚNICA)"},
        {"preservacao.card_formato_risco", "FORMATO EM RISCO"},
        {"preservacao.card_regra_321", "REGRA DE BACKUP 3-2-1"},
        {"preservacao.card_vault_refresh", "DISCO REQUER ATUALIZAÇÃO"},
        {"preservacao.card_compliance_score", "ÍNDICE DE CONFORMIDADE"},
        {"dialogo.fechar", "FECHAR"},
        {"dialogo.localizar_arquivo", "LOCALIZAR ARQUIVO"},
        {"dialogo.trabalhar_offline", "TRABALHAR OFFLINE"},
        {"dialogo.cancelar", "CANCELAR"},
        {"vulnerabilidades.titulo", "INTEGRIDADE DO BACKUP E ANÁLISE DE RISCOS"},
        {"vulnerabilidades.subtitulo", "Detalhamento categorizado de riscos para os ativos do projeto. Clique em qualquer cartão para filtrar os arquivos diretamente na Grade."},
        {"vulnerabilidades.cat_meta", "METADADOS AUSENTES"},
        {"vulnerabilidades.cat_meta_desc", "Ativos sem metadados obrigatórios no catálogo (Lançamento/Ano, Tipo de Mídia ou Tipo de Coleção)."},
        {"vulnerabilidades.cat_dup", "ARQUIVOS DUPLICADOS"},
        {"vulnerabilidades.cat_dup_desc", "Ativos compartilhando o mesmo checksum SHA-256 no projeto ou arquivos duplicados na ingestão."},
        {"vulnerabilidades.cat_offline", "OFFLINE / ORIGEM AUSENTE"},
        {"vulnerabilidades.cat_offline_desc", "Ativos cujos arquivos master estão em volumes desconectados ou ausentes no disco."},
        {"vulnerabilidades.cat_single", "CÓPIA ÚNICA (SEM BACKUP)"},
        {"vulnerabilidades.cat_single_desc", "Ativos sem réplica verificada em nenhum disco de backup secundário."},
        {"vulnerabilidades.arquivos_contador", "{n} arquivos"},
        {"vulnerabilidades.clique_grid", "Clique para ver e selecionar na Grade \u2192"},
        {"vulnerabilidades.dialog_titulo", "Diagnóstico de Saúde e Riscos do Backup"},
        {"sobre.dialog_titulo", "Sobre o BKR Matriz"},
        {"sobre.versao", "Versão 1.0"},
        {"sobre.desenvolvido_por", "Desenvolvido por A. Guerra"},
        {"sobre.direitos_reservados", "© 2026 BKR Systems. Todos os direitos reservados."},
        {"relink.inicial_titulo", "LOCALIZAÇÃO DOS ATIVOS NÃO ENCONTRADA"},
        {"relink.inicial_desc", "Os ativos deste projeto não foram localizados em seus caminhos registrados.\n\nPor favor, localize um arquivo de ativo deste projeto. O sistema irá deduzir automaticamente a nova raiz de armazenamento e reconectar os ativos acessíveis."},
        {"relink.arquivo_esperado_exemplo", "Arquivo esperado de exemplo ({t}):"},
        {"relink.dialog_inicial_titulo", "Localização dos Ativos Não Encontrada"},
        {"relink.localizar_ativo_conhecido", "Localizar Ativo Conhecido ({n})"},
        {"relink.ativo_offline", "ATIVO OFFLINE"},
        {"relink.offline_desc", "O arquivo físico original não foi encontrado na sua localização registrada."},
        {"relink.rotulo_titulo", "Título:"},
        {"relink.rotulo_localizacao_esperada", "Localização esperada:"},
        {"relink.rotulo_armazenamento", "Armazenamento:"},
        {"relink.armazenamento_local", "Armazenamento Local"},
        {"relink.dialog_offline_titulo", "Reconectar Ativo Offline"},
        {"relink.localizar_arquivo_ativo", "Localizar Arquivo de Ativo ({n})"},
        {"relink.divergencia_checksum_titulo", "Divergência de Checksum — Conteúdo do Arquivo Diferente"},
        {"relink.divergencia_checksum_msg", "O arquivo selecionado não corresponde ao hash ou tamanho do arquivo original.\n\nSHA-256 Original: {o}...\nSHA-256 Selecionado: {s}...\n\nDeseja substituir o ativo? Um novo ID de Ativo será atribuído, e a substituição será registrada no log do projeto."},
        {"relink.btn_substituir_ativo", "Substituir Ativo (Novo ID)"},
        {"barra.src_tree", "ÁRVORE ORIGEM"},
        {"barra.src_tree_dica", "Exibir/ocultar estrutura do diretório de origem"},
        {"barra.dest_tree", "ÁRVORE DESTINO"},
        {"barra.dest_tree_dica", "Exibir/ocultar estrutura de destino do backup"},
        {"barra.advanced", "AVANÇADO"},
        {"barra.advanced_dica", "Exibir/ocultar árvores de diretórios avançadas"},
        {"barra.todos_ativos", "TODOS OS ATIVOS"},
        {"barra.audio", "ÁUDIO"},
        {"barra.video", "VÍDEO"},
        {"barra.image", "IMAGEM"},
        {"barra.document", "DOCUMENTO"},
        {"barra.status_rotulo", "STATUS:"},
        {"barra.status_todos", "TODOS"},
        {"barra.status_online", "ONLINE"},
        {"barra.status_offline", "OFFLINE"},
        {"catwork.toggle_ficha_texto", "\xe2\x97\x80 Metadados"},
        {"catwork.toggle_ficha_tooltip_show", "Exibir inspetor de metadados"},
        {"catwork.toggle_ficha_tooltip_hide", "Recolher inspetor de metadados"},
        {"catwork.toggle_ficha_tooltip", "Recolher / expandir inspetor de metadados"},
    };
    return strings;
}

} // namespace matriz::i18n
