#pragma once

#include <unordered_map>
#include <string>

namespace matriz::i18n {

inline const std::unordered_map<std::string, std::string>& getEnglishStrings() {
    static const std::unordered_map<std::string, std::string> strings = {
        {"acoes.categorizar", "Change Type"},
        {"acoes.copiar_caminho", "Copy path"},
        {"acoes.definir_capa", "Use image as cover..."},
        {"acoes.enviar_para_pasta", "Send to folder"},
        {"acoes.mostrar_na_origem", "Show at source"},
        {"acoes.origem_ausente_mensagem", "This file came from:\n{caminho}\n\nConnect the source drive to open the folder."},
        {"acoes.origem_ausente_titulo", "Source isn't connected"},
        {"acoes.preview", "Preview"},
        {"acoes.remover_capa", "Remove cover"},
        {"acoes.remover_da_lista", "Remove from this list"},
        {"acoes.remover_da_lista_mensagem", "{n} file(s) disappear from this list and from the project, along with the details you filled in.\n\nNo file is deleted from disk: the original at the source stays where it is."},
        {"acoes.remover_da_lista_titulo", "Remove from this list?"},
        {"acoes.remover_do_backup", "Remove from backup"},
        {"acoes.remover_do_backup_mensagem", "{n} file(s) leave the BACKUP folders and go back to \"No folder yet\".\n\nNo file is deleted from disk."},
        {"acoes.remover_do_backup_titulo", "Remove from backup?"},
        {"acoes.renomear", "Rename..."},
        {"acoes.renomear_mensagem", "New name. This is what becomes the file name in the backup."},
        {"acoes.renomear_mensagem_lote", "New name for the {n} files. The mask numbers each one automatically."},
        {"acoes.renomear_previa", "In the backup it will be: {nome}"},
        {"acoes.renomear_titulo", "Rename"},
        {"acoes.sem_duplicatas", "No other file in the project has this same content."},
        {"acoes.sem_pastas", "No folders yet  -  create one with \"+\" in BACKUP TREE"},
        {"acoes.ver_duplicatas", "Show duplicates of this file"},
        {"app.nome", "BKR Matriz"},
        {"arvore.aba_acervo", "BACKUP TREE"},
        {"arvore.aba_origem", "SOURCE"},
        {"arvore.achatar_estrutura", "Put everything directly in this folder"},
        {"arvore.apagar_confirmar_mensagem", "This only removes the folder from your planned layout  -  no file on disk is touched. Files that were in it stay in the project, they just go back to \"No folder yet\"."},
        {"arvore.apagar_confirmar_titulo", "Delete folder?"},
        {"arvore.backup_dica", "The structure you build, and the one that gets written to the backup."},
        {"arvore.explorer_dica", "The real structure of the source disk, as it is. Nothing here is editable."},
        {"arvore.incluir_subpastas", "Include subfolders"},
        {"arvore.manter_estrutura", "Keep the folder structure"},
        {"arvore.menu_apagar", "Delete"},
        {"arvore.menu_nova_subpasta", "New subfolder"},
        {"arvore.menu_renomear", "Rename"},
        {"arvore.nao_organizados", "No folder yet"},
        {"arvore.nome_nova_pasta_mensagem", "Folder name:"},
        {"arvore.nome_nova_pasta_titulo", "New folder"},
        {"arvore.nova_pasta", "New folder"},
        {"arvore.pasta_raiz_auto", "Imported"},
        {"renomear_lote.titulo", "Batch Rename"},
        {"renomear_lote.adicionar_depois", "After the Name"},
        {"renomear_lote.adicionar_antes", "Before the Name"},
        {"renomear_lote.substituir", "Replace Text"},
        {"renomear_lote.inserir_entre_prefixo_e_nome", "Between Prefix and Original Name"},
        {"renomear_lote.campo_texto", "Text:"},
        {"renomear_lote.campo_procurar", "Find:"},
        {"renomear_lote.campo_substituir_por", "Replace with:"},
        {"renomear_lote.previa", "Preview: {nome}"},
        {"renomear_lote.renomear", "Rename"},
        {"arvore.mostrar_conteudo_grade", "SHOW CONTENT IN GRID"},
        {"catwork.selected", "Selected files"},
        {"arvore.renomear_pasta_mensagem", "New name:"},
        {"arvore.renomear_pasta_titulo", "Rename folder"},
        {"arvore.soltar_pasta_mensagem", "\"{pasta}\" has {n} file(s) in subfolders."},
        {"arvore.soltar_pasta_titulo", "How should this folder come in?"},
        {"arvore.todos_os_materiais", "All files"},
        {"barra.adicionar", "Add files"},
        {"barra.adicionar_dica", "Pick a folder or files to copy into the project. You can also drag straight from Finder onto anywhere in this window."},
        {"barra.backup", "Backup"},
        {"barra.backup_dica", "Copies the original byte for byte to another drive, following the folders you built under BACKUP. The source is never touched."},
        {"barra.buscar", "Search by name, code or any detail"},
        {"barra.contagem", "{visiveis} of {total} files"},
        {"barra.contagem_filtrada", "{visiveis} of {total} files  |  filtered"},
        {"barra.detalhes_dica", "Shows or hides the side panel with the details of whatever is selected."},
        {"barra.modo_visao_dica", "Toggle between grid and list view"},
        {"barra.tamanho_dica", "Thumbnail size"},
        {"backup.btn_copiar", "START COPY"},
        {"backup.btn_proximo", "NEXT"},
        {"backup.btn_voltar", "BACK"},
        {"backup.cancelar", "Cancel"},
        {"backup.copiando_progresso", "Copying {0} of {1}..."},
        {"backup.copiando_titulo", "Copying files"},
        {"backup.destino_titulo", "Choose destination"},
        {"backup.destino_vazio", "No volumes available. Connect an external drive."},
        {"backup.done_falhas", "{0} files failed to copy"},
        {"backup.done_titulo", "Backup Complete"},
        {"backup.done_verificados", "{0} files copied and verified"},
        {"backup.escolha_titulo", "What to back up"},
        {"backup.escolha_colecao", "A collection"},
        {"backup.escolha_precisa", "Needs backup"},
        {"backup.escolha_recentes", "Intake"},
        {"backup.escolha_selecionados", "Selected assets"},
        {"backup.escolha_tudo", "Everything"},
        {"backup.preview_espaco", "Space needed: {0}  |  Available: {1}"},
        {"backup.preview_ja_copiados", "{0} already backed up (skipped)"},
        {"backup.preview_novos", "{0} files to copy"},
        {"backup.preview_titulo", "Backup preview"},
        {"backup.step_copiar", "Copy"},
        {"backup.step_destino", "Where"},
        {"backup.step_done", "Done"},
        {"backup.step_escolha", "What"},
        {"backup.step_preview", "Preview"},
        {"backup.step_verificar", "Verify"},
        {"backup.titulo", "Backup"},
        {"backup.verificando_progresso", "Verifying {0} of {1}..."},
        {"backup.verificando_titulo", "Verifying copies"},
        {"backup.voltar_home", "RETURN HOME"},
        {"catalogo.abrir", "Open backup catalog..."},
        {"catalogo.ausente", "source missing"},
        {"catalogo.cancelado", "Catalog cancelled  -  {feito} of {total}. What was written is saved."},
        {"catalogo.disponivel", "available"},
        {"catalogo.fechar", "Close catalog"},
        {"catalogo.gerado", "Catalog written  -  {n} materials browsable without the drive connected."},
        {"catalogo.gerando", "Generating catalog... {feito}/{total}"},
        {"catalogo.gerar", "Generate browsable catalog"},
        {"catalogo.gerar_ajuda", "Thumbnails, records and the location of every file, written alongside the backup. Takes {tamanho} and lets you browse the archive with the drive unplugged."},
        {"catalogo.nao_e_catalogo", "This folder has no Matriz catalog inside it."},
        {"catalogo.onde_esta_corpo", "{titulo}\n\nDrive: {volume}\nFolder: {local}\n\nFull path:\n{caminho}\n\nConnect the drive to open the file."},
        {"catalogo.onde_esta_titulo", "Where this file is"},
        {"catalogo.sem_resultado", "No material found for this search."},
        {"catalogo.titulo", "Backup catalog"},
        {"catalogo.vazio", "This catalog is empty."},
        {"catalogo.volume_desconhecido", "unidentified drive"},
        {"catwork.all", "ALL ASSETS"},
        {"catwork.audio", "Audio"},
        {"catwork.back", "Back to catalog"},
        {"catwork.documents", "Documents"},
        {"catwork.sessions", "Sessions"},
        {"catwork.images", "Images"},
        {"catwork.needs_review", "Needs review"},
        {"catwork.no_backup", "No backup"},
        {"catwork.offline", "Offline"},
        {"catwork.single_copy", "Single copy"},
        {"catwork.source_structure", "Source structure"},
        {"catwork.video", "Video"},
        {"colecoes.ausentes", "Missing"},
        {"colecoes.clipping", "Clipping"},
        {"colecoes.incompletos", "Incomplete"},
        {"colecoes.nao_baixados", "Not downloaded"},
        {"colecoes.revisao", "Needs review"},
        {"colecoes.vulneraveis", "No backup yet"},
        {"comum.cancelar", "Cancel"},
        {"comum.erro", "Error"},
        {"comum.nao", "No"},
        {"comum.ok", "OK"},
        {"comum.salvar", "Save"},
        {"comum.sim", "Yes"},
        {"configuracoes_projeto.aviso_sobrescrever_cancelar", "Cancel"},
        {"configuracoes_projeto.aviso_sobrescrever_confirmar", "I understand, allow it anyway"},
        {"configuracoes_projeto.aviso_sobrescrever_corpo", "Turning this on allows the original master to be overwritten directly, without going through a derivative. This turns off the default preservation guarantee (two files by default, P1)  -  the original file is no longer protected against accidental overwrite. This is a decision for the person responsible for the project: the software warns once, here, and won't ask again after it's confirmed."},
        {"configuracoes_projeto.aviso_sobrescrever_titulo", "Warning: master overwrite"},
        {"configuracoes_projeto.botao_fechar", "Close"},
        {"configuracoes_projeto.campo_nome", "Project name"},
        {"configuracoes_projeto.campo_permitir_sobrescrever", "Allow overwriting master"},
        {"configuracoes_projeto.secao_geral", "General"},
        {"configuracoes_projeto.secao_master", "Master"},
        {"configuracoes_projeto.titulo", "Project settings"},
        {"consolidacao.aviso_conflitos", "{n} duplicate name(s)  -  resolve them before writing."},
        {"consolidacao.aviso_espaco", "Needs: {necessario}  |  Free at destination: {disponivel}"},
        {"consolidacao.aviso_nao_organizados", "{n} file(s) still outside any BACKUP folder  -  they won't be in this backup."},
        {"consolidacao.cancelado", "Cancelled  -  {feito} of {total} processed. What was written is saved and verified."},
        {"consolidacao.consolidando", "Writing... for large archives this can take a long while."},
        {"consolidacao.consolidar", "Write backup"},
        {"consolidacao.destino_nao_escolhido", "Choose the drive or folder where the backup gets written."},
        {"consolidacao.escolher_destino", "Choose where to write..."},
        {"consolidacao.fechar", "Close"},
        {"consolidacao.ja_consolidado", "already copied"},
        {"consolidacao.previa_vazia", "Nothing to write yet. Drag folders or files from SOURCE into the BACKUP TREE folders  -  that layout is what becomes the backup."},
        {"consolidacao.progresso", "Writing... {feito}/{total}"},
        {"consolidacao.resultado", "{consolidados} copied, {pulados} already up to date"},
        {"consolidacao.resultado_falhas", "{n} failed"},
        {"consolidacao.titulo", "Backup"},
        {"dialogo_abrir_projeto.botao_escolher", "Choose project folder..."},
        {"dialogo_abrir_projeto.erro_titulo", "Could not open the project"},
        {"dialogo_abrir_projeto.titulo", "Open project"},
        {"dialogo_novo_projeto.botao_cancelar", "Cancel"},
        {"dialogo_novo_projeto.botao_criar", "Create project"},
        {"dialogo_novo_projeto.botao_escolher_pasta", "CHOOSE PROJECT DESTINATION FOLDER"},
        {"dialogo_novo_projeto.campo_instituicao", "Institution or label (optional)"},
        {"dialogo_novo_projeto.campo_isrc", "ISRC registrant (optional)"},
        {"dialogo_novo_projeto.campo_modo_catalogo", "New Catalog project"},
        {"dialogo_novo_projeto.campo_modo_preservacao", "New Collection project"},
        {"dialogo_novo_projeto.campo_nome", "Project name"},
        {"dialogo_novo_projeto.campo_pasta", "Project destination folder"},
        {"dialogo_novo_projeto.campo_pasta_ajuda", "Files are copied here. Originals stay untouched."},
        {"dialogo_novo_projeto.campo_prefixo", "Naming prefix"},
        {"dialogo_novo_projeto.campo_responsavel", "Responsible party (optional)"},
        {"dialogo_novo_projeto.erro_nome_vazio", "Give the project a name to continue."},
        {"dialogo_novo_projeto.erro_pasta_vazia", "Choose a folder for the project to live in."},
        {"dialogo_novo_projeto.erro_prefixo_vazio", "The naming prefix is required."},
        {"dialogo_novo_projeto.erro_titulo", "Could not create the project"},
        {"dialogo_novo_projeto.titulo", "New project"},
        {"estado_vazio.rodape", "Your original files are never moved or deleted  -  Matriz makes a copy inside the project."},
        {"estado_vazio.subtitulo", "or click here to browse your computer"},
        {"estado_vazio.titulo", "Drag your folder or drive here"},
        {"ficha.alerta_rotulo", "Attention"},
        {"ficha.alternar", "Details"},
        {"ficha.arquivo_ausente", "missing"},
        {"ficha.arquivo_obrigatorio", "required"},
        {"ficha.arquivo_presente", "present"},
        {"ficha.cabecalho_sem_titulo", "(untitled)"},
        {"ficha.campo_booleano_nao", "No"},
        {"ficha.campo_booleano_sim", "Yes"},
        {"ficha.herdado_do_projeto", "inherited from project"},
        {"ficha.lote_aplicar", "Apply"},
        {"ficha.lote_campos_nao_suportados", "Table and person-list fields aren't editable in batch mode yet  -  edit them per item."},
        {"ficha.lote_desfazer", "Undo"},
        {"ficha.lote_escolher_tipo", "None of the selected materials are classified yet. Choose a media type to apply to all of them:"},
        {"ficha.lote_nenhum_campo_tocado", "Edit a field above, then apply it to the whole selection."},
        {"ficha.lote_previa", "{n} materials will be changed: {campos}"},
        {"ficha.lote_resultado", "{sucessos} changed"},
        {"ficha.lote_resultado_desfeito", "{n} restored"},
        {"ficha.lote_resultado_falhas", ", {falhas} failed"},
        {"ficha.lote_tipo_misto", "Selection has mixed media types. Select items of the same type to batch-edit their record sheet."},
        {"ficha.lote_tipo_misto_universais", "Selection has mixed media types  -  only Origin and Year are shared by every type, so only those can be edited together."},
        {"ficha.lote_titulo", "{n} materials selected"},
        {"ficha.lote_valores_multiplos", "Multiple values"},
        {"ficha.nao_classificado", "Not classified yet. Choose a media type to fill in its record sheet:"},
        {"ficha.nivel_faixa_adicionar", "Add track"},
        {"ficha.nivel_faixa_numero", "Track {n}"},
        {"ficha.nivel_faixa_remover", "Remove track"},
        {"ficha.observacao_minutagem_dica", "Time (MM:SS, optional)"},
        {"ficha.observacao_nova", "New note"},
        {"ficha.opcao_livre_criar", "Create \"{texto}\""},
        {"ficha.preenchido_por_leitura_tecnica", "technical reading"},
        {"ficha.recategorizar", "Change type"},
        {"ficha.recategorizar_titulo", "Choose a new media type:"},
        {"ficha.secao_arquivos_esperados", "Expected files"},
        {"ficha.secao_observacoes", "Notes"},
        {"ficha.sugestao_confianca", "confidence {p}%"},
        {"ficha.sugestao_confirmar", "Confirm"},
        {"ficha.sugestao_modelo", "model: {modelo} {versao}"},
        {"ficha.sugestao_rotulo", "suggestion"},
        {"ficha.tabela_adicionar_linha", "Add row"},
        {"ficha.tabela_remover_linha", "Remove"},
        {"ficha.vazia", "Click a file in the grid to see and edit its details here."},
        {"ficha_alertas.cassete.sticky_shed", "Requires thermal treatment before playback"},
        {"ficha_alertas.filme.quebradico", "Handling requires special care  -  risk of breakage or combustion with nitrate"},
        {"ficha_alertas.fita_rolo.sticky_shed", "Requires thermal treatment before playback"},
        {"ficha_alertas.minidisc.atrac_lossy", "Source is already lossy  -  digitization does not recover quality lost in the original recording"},
        {"ficha_campos.cassete.abrangencia", "Recording scope"},
        {"ficha_campos.cassete.ano", "Year"},
        {"ficha_campos.cassete.deck", "Playback deck"},
        {"ficha_campos.cassete.direcao", "Side captured"},
        {"ficha_campos.cassete.dolby", "Noise reduction"},
        {"ficha_campos.cassete.duracao_nominal", "Nominal duration"},
        {"ficha_campos.cassete.estado_geral", "General condition"},
        {"ficha_campos.cassete.fita_solta_enroscada", "Tape loose or tangled in mechanism"},
        {"ficha_campos.cassete.idioma", "Language"},
        {"ficha_campos.cassete.marca", "Brand"},
        {"ficha_campos.cassete.natureza", "Content nature"},
        {"ficha_campos.cassete.origem", "Origin"},
        {"ficha_campos.cassete.sticky_shed", "Signs of sticky shed"},
        {"ficha_campos.cassete.tipo_fita", "Tape type"},
        {"ficha_campos.cassete.trecho_observacao", "Note about the excerpt"},
        {"ficha_campos.cassete.trecho_posicao", "Excerpt position"},
        {"ficha_campos.cd.ano", "Year"},
        {"ficha_campos.cd.estado_fisico", "Disc physical condition"},
        {"ficha_campos.cd.idioma", "Language"},
        {"ficha_campos.cd.marca_midia", "Media brand (if CD-R)"},
        {"ficha_campos.cd.natureza", "Content nature"},
        {"ficha_campos.cd.numero_faixas", "Number of tracks"},
        {"ficha_campos.cd.origem", "Origin"},
        {"ficha_campos.cd.ripagem_bit_exata_confirmada", "Bit-exact rip confirmed"},
        {"ficha_campos.cd.tipo_disco", "Disc type"},
        {"ficha_campos.cd.toc", "TOC / total duration"},
        {"ficha_campos.cover_art.ano", "Year"},
        {"ficha_campos.cover_art.artista", "Artist"},
        {"ficha_campos.cover_art.designer", "Designer / photographer"},
        {"ficha_campos.cover_art.dimensoes", "Dimensions"},
        {"ficha_campos.cover_art.formato", "Format"},
        {"ficha_campos.cover_art.licenca", "License / use"},
        {"ficha_campos.cover_art.origem", "Origin"},
        {"ficha_campos.cover_art.resolucao", "Resolution"},
        {"ficha_campos.cover_art.tipo_arte", "Art type"},
        {"ficha_campos.cover_art.titulo_release", "Release title"},
        {"ficha_grupos.cover_art.identificacao", "Identification"},
        {"ficha_grupos.cover_art.identification", "Identification"},
        {"ficha_grupos.cover_art.imagem", "Image"},
        {"ficha_grupos.cover_art.image", "Image"},
        {"ficha_grupos.cover_art.direitos", "Rights"},
        {"ficha_grupos.cover_art.rights", "Rights"},
        {"ficha_campos.dat.ano", "Year"},
        {"ficha_campos.dat.caminho_captura", "Capture path"},
        {"ficha_campos.dat.deck", "Playback deck"},
        {"ficha_campos.dat.duracao_fita", "Nominal duration"},
        {"ficha_campos.dat.erros_leitura", "Read errors during capture"},
        {"ficha_campos.dat.estado_geral", "General condition"},
        {"ficha_campos.dat.idioma", "Language"},
        {"ficha_campos.dat.marca", "Tape brand"},
        {"ficha_campos.dat.natureza", "Content nature"},
        {"ficha_campos.dat.origem", "Origin"},
        {"ficha_campos.dat.sample_rate_original", "Original sample rate"},
        {"ficha_campos.dat.subcode_disponivel", "Subcode (start ID/program) available"},
        {"ficha_campos.digital_audio.ano", "Year"},
        {"ficha_campos.digital_audio.bit_depth_declarado", "Declared bit depth"},
        {"ficha_campos.digital_audio.codec", "Codec"},
        {"ficha_campos.digital_audio.daw_origem", "Source DAW"},
        {"ficha_campos.digital_audio.eh_mixdown_ou_stem", "Material type"},
        {"ficha_campos.digital_audio.formato_arquivo", "File format"},
        {"ficha_campos.digital_audio.idioma", "Language"},
        {"ficha_campos.digital_audio.natureza", "Content nature"},
        {"ficha_campos.digital_audio.origem", "Origin"},
        {"ficha_campos.digital_audio.plugins_criticos", "Critical plugins (session dependency)"},
        {"ficha_campos.digital_audio.sample_rate_declarado", "Declared sample rate"},
        {"ficha_campos.digital_video.ano", "Year"},
        {"ficha_campos.digital_video.camera", "Camera / model"},
        {"ficha_campos.digital_video.codec", "Codec"},
        {"ficha_campos.digital_video.contagem_poligonos", "Polygon count"},
        {"ficha_campos.digital_video.data_gravacao", "Recording date"},
        {"ficha_campos.digital_video.descricao_conteudo", "Content description"},
        {"ficha_campos.digital_video.formato", "Format"},
        {"ficha_campos.digital_video.formato_container", "Container format"},
        {"ficha_campos.digital_video.frame_rate_declarado", "Declared frame rate"},
        {"ficha_campos.digital_video.origem", "Origin"},
        {"ficha_campos.digital_video.possui_rig", "Has rig"},
        {"ficha_campos.digital_video.possui_texturas", "Has textures"},
        {"ficha_campos.digital_video.resolucao", "Resolution"},
        {"ficha_campos.digital_video.software_origem", "Source software"},
        {"ficha_campos.documento.ano", "Year"},
        {"ficha_campos.documento.assinado", "Signed"},
        {"ficha_campos.documento.autor_documento", "Author / issuer"},
        {"ficha_campos.documento.data_documento", "Document date"},
        {"ficha_campos.documento.estado_fisico", "Physical condition (if digitized from paper)"},
        {"ficha_campos.documento.idioma", "Language"},
        {"ficha_campos.documento.numero_paginas", "Number of pages"},
        {"ficha_campos.documento.origem", "Origin"},
        {"ficha_campos.documento.texto_pesquisavel", "Searchable text in PDF"},
        {"ficha_campos.documento.tipo_documento", "Document type"},
        {"ficha_campos.field_recording.ambiente", "Environment"},
        {"ficha_campos.field_recording.ano", "Year"},
        {"ficha_campos.field_recording.condicoes", "Conditions (wind, rain, background noise)"},
        {"ficha_campos.field_recording.equipamento_gravador", "Recorder"},
        {"ficha_campos.field_recording.idioma", "Language"},
        {"ficha_campos.field_recording.microfone", "Microphone"},
        {"ficha_campos.field_recording.natureza", "Content nature"},
        {"ficha_campos.field_recording.origem", "Origin"},
        {"ficha_campos.field_recording.padrao_polar", "Polar pattern"},
        {"ficha_campos.filme.ano", "Year"},
        {"ficha_campos.filme.bitola", "Gauge"},
        {"ficha_campos.filme.campo_entrelacado_detectado", "Interlaced field detected"},
        {"ficha_campos.filme.cor_pb", "Color or black and white"},
        {"ficha_campos.filme.descricao_conteudo", "Content description"},
        {"ficha_campos.filme.encolhimento", "Base shrinkage"},
        {"ficha_campos.filme.estado_geral", "General condition"},
        {"ficha_campos.filme.fps_captura", "Captured file FPS"},
        {"ficha_campos.filme.fps_original_declarado", "Declared original FPS"},
        {"ficha_campos.filme.mofo", "Signs of mold"},
        {"ficha_campos.filme.origem", "Origin"},
        {"ficha_campos.filme.pulldown_detectado", "3:2 pulldown detected"},
        {"ficha_campos.filme.quadro_duplicado_detectado", "Duplicated frame detected"},
        {"ficha_campos.filme.quebradico", "Brittle material (degraded nitrate/acetate base)"},
        {"ficha_campos.filme.som_optico", "Has optical soundtrack"},
        {"ficha_campos.fita_rolo.abrangencia", "Recording scope"},
        {"ficha_campos.fita_rolo.alinhamento", "Alignment tape used"},
        {"ficha_campos.fita_rolo.ano", "Year"},
        {"ficha_campos.fita_rolo.curva", "Equalization curve"},
        {"ficha_campos.fita_rolo.direcao", "Direction"},
        {"ficha_campos.fita_rolo.emendas", "Visible splices"},
        {"ficha_campos.fita_rolo.espessura", "Thickness"},
        {"ficha_campos.fita_rolo.estado_geral", "General condition"},
        {"ficha_campos.fita_rolo.formulacao", "Formulation"},
        {"ficha_campos.fita_rolo.idioma", "Language"},
        {"ficha_campos.fita_rolo.largura", "Width"},
        {"ficha_campos.fita_rolo.maquina", "Playback machine"},
        {"ficha_campos.fita_rolo.marca", "Brand"},
        {"ficha_campos.fita_rolo.natureza", "Content nature"},
        {"ficha_campos.fita_rolo.origem", "Origin"},
        {"ficha_campos.fita_rolo.pistas", "Track configuration"},
        {"ficha_campos.fita_rolo.print_through", "Audible print-through"},
        {"ficha_campos.fita_rolo.sticky_shed", "Signs of sticky shed"},
        {"ficha_campos.fita_rolo.trecho_observacao", "Note about the excerpt"},
        {"ficha_campos.fita_rolo.trecho_posicao", "Excerpt position"},
        {"ficha_campos.fita_rolo.velocidade", "Speed"},
        {"ficha_campos.foto.ano", "Year"},
        {"ficha_campos.foto.camera", "Camera / model"},
        {"ficha_campos.foto.danos", "Visible damage"},
        {"ficha_campos.foto.data_foto", "Photo date"},
        {"ficha_campos.foto.dimensoes", "Dimensions"},
        {"ficha_campos.foto.estado_fisico", "General condition"},
        {"ficha_campos.foto.evento", "Event"},
        {"ficha_campos.foto.fotografo", "Photographer"},
        {"ficha_campos.foto.licenca", "License / use"},
        {"ficha_campos.foto.local", "Location"},
        {"ficha_campos.foto.origem", "Origin"},
        {"ficha_campos.foto.pessoas_identificadas", "Identified people"},
        {"ficha_campos.foto.suporte", "Support"},
        {"ficha_campos.minidisc.ano", "Year"},
        {"ficha_campos.minidisc.atrac_lossy", "Source in ATRAC (lossy)"},
        {"ficha_campos.minidisc.caminho_captura", "Capture path"},
        {"ficha_campos.minidisc.deck", "Playback deck"},
        {"ficha_campos.minidisc.erros_leitura", "Read errors during capture"},
        {"ficha_campos.minidisc.estado_geral", "General condition"},
        {"ficha_campos.minidisc.idioma", "Language"},
        {"ficha_campos.minidisc.marca", "Brand"},
        {"ficha_campos.minidisc.modo_gravacao", "Recording mode"},
        {"ficha_campos.minidisc.natureza", "Content nature"},
        {"ficha_campos.minidisc.origem", "Origin"},
        {"ficha_campos.minidisc.tipo_disco", "Disc type"},
        {"ficha_campos.negativo.ano", "Year"},
        {"ficha_campos.negativo.cor_pb", "Color or black and white"},
        {"ficha_campos.negativo.data_foto", "Photo date"},
        {"ficha_campos.negativo.desvanecimento", "Color fading"},
        {"ficha_campos.negativo.dimensoes_scan", "Scan dimensions"},
        {"ficha_campos.negativo.estado_geral", "General condition"},
        {"ficha_campos.negativo.formato", "Format"},
        {"ficha_campos.negativo.local", "Location"},
        {"ficha_campos.negativo.mofo", "Signs of mold"},
        {"ficha_campos.negativo.origem", "Origin"},
        {"ficha_campos.negativo.pessoas_identificadas", "Identified people"},
        {"ficha_campos.negativo.resolucao_scan", "Scan resolution"},
        {"ficha_campos.negativo.riscos", "Visible scratches"},
        {"ficha_campos.release.ano", "Year"},
        {"ficha_campos.release.artista_principal", "Main artist"},
        {"ficha_campos.release.compositores", "Composers"},
        {"ficha_campos.release.data_lancamento", "Release date"},
        {"ficha_campos.release.duracao", "Duration"},
        {"ficha_campos.release.editora", "Publisher"},
        {"ficha_campos.release.explicito", "Explicit content"},
        {"ficha_campos.release.formato", "Format"},
        {"ficha_campos.release.genero", "Genre"},
        {"ficha_campos.release.idioma", "Language"},
        {"ficha_campos.release.isrc", "ISRC"},
        {"ficha_campos.release.numero", "Number"},
        {"ficha_campos.release.numero_catalogo", "Catalog number"},
        {"ficha_campos.release.origem", "Origin"},
        {"ficha_campos.release.participacao", "Featured artists"},
        {"ficha_campos.release.selo", "Label"},
        {"ficha_campos.release.splits", "Splits"},
        {"ficha_campos.release.titulo", "Title"},
        {"ficha_campos.release.upc_ean", "UPC/EAN"},
        {"ficha_campos.sample.ano", "Year"},
        {"ficha_campos.sample.bpm", "BPM"},
        {"ficha_campos.sample.categoria", "Category"},
        {"ficha_campos.sample.licenca", "License"},
        {"ficha_campos.sample.origem", "Origin"},
        {"ficha_campos.sample.origem_texto", "Source"},
        {"ficha_campos.sample.tipo_temporal", "Temporal type"},
        {"ficha_campos.sample.tonalidade", "Key"},
        {"ficha_campos.slide.ano", "Year"},
        {"ficha_campos.slide.data_foto", "Photo date"},
        {"ficha_campos.slide.desvanecimento", "Color fading"},
        {"ficha_campos.slide.dimensoes_scan", "Scan dimensions"},
        {"ficha_campos.slide.estado_geral", "General condition"},
        {"ficha_campos.slide.formato", "Format"},
        {"ficha_campos.slide.fungo", "Signs of fungus"},
        {"ficha_campos.slide.local", "Location"},
        {"ficha_campos.slide.moldura", "Mount"},
        {"ficha_campos.slide.origem", "Origin"},
        {"ficha_campos.slide.pessoas_identificadas", "Identified people"},
        {"ficha_campos.slide.resolucao_scan", "Scan resolution"},
        {"ficha_campos.sound_effects.ano", "Year"},
        {"ficha_campos.sound_effects.biblioteca_origem", "Source library"},
        {"ficha_campos.sound_effects.categoria", "Category"},
        {"ficha_campos.sound_effects.licenca", "License"},
        {"ficha_campos.sound_effects.origem", "Origin"},
        {"ficha_campos.video.ano", "Year"},
        {"ficha_campos.video.campo_entrelacado_detectado", "Interlaced field detected"},
        {"ficha_campos.video.cortes_cena_detectados", "Scene cuts detected"},
        {"ficha_campos.video.descricao_conteudo", "Content description"},
        {"ficha_campos.video.dropout_frequente", "Frequent dropout"},
        {"ficha_campos.video.estado_geral", "General condition"},
        {"ficha_campos.video.fita_solta_enroscada", "Tape loose or tangled in mechanism"},
        {"ficha_campos.video.formato_original", "Original format"},
        {"ficha_campos.video.fps_captura", "Captured file FPS"},
        {"ficha_campos.video.origem", "Origin"},
        {"ficha_campos.video.pulldown_detectado", "3:2 pulldown detected"},
        {"ficha_campos.video.quadro_duplicado_detectado", "Duplicated frame detected"},
        {"ficha_campos.video.sistema", "Color system"},
        {"ficha_campos.video.tbc_usado", "TBC used in digitization"},
        {"ficha_campos.vinil.ano", "Year"},
        {"ficha_campos.vinil.cartucho", "Cartridge used"},
        {"ficha_campos.vinil.curva", "Equalization curve"},
        {"ficha_campos.vinil.empenado", "Warped"},
        {"ficha_campos.vinil.estado_capa", "Sleeve condition"},
        {"ficha_campos.vinil.estado_disco", "Disc condition (Goldmine)"},
        {"ficha_campos.vinil.formato", "Format"},
        {"ficha_campos.vinil.idioma", "Language"},
        {"ficha_campos.vinil.natureza", "Content nature"},
        {"ficha_campos.vinil.numero_catalogo", "Catalog number"},
        {"ficha_campos.vinil.origem", "Origin"},
        {"ficha_campos.vinil.peso_gramatura", "Weight"},
        {"ficha_campos.vinil.riscos_audiveis", "Audible scratches"},
        {"ficha_campos.vinil.selo", "Original label/imprint"},
        {"ficha_campos.vinil.toca_discos", "Turntable"},
        {"ficha_campos.vinil.velocidade", "Speed"},
        {"escuta.arquivo_truncado", "Long file: only the first 45 minutes are loaded for playback"},
        {"escuta.correlacao", "CORRELATION"},
        {"escuta.espectro", "SPECTRUM"},
        {"escuta.fechar", "Close"},
        {"escuta.formato_nao_suportado", "This audio format can't be played here  -  the file itself is untouched"},
        {"escuta.loop_in", "Loop in"},
        {"escuta.loop_limpar", "Clear loop"},
        {"escuta.loop_out", "Loop out"},
        {"escuta.parar", "Stop"},
        {"escuta.sem_arquivo", "This item has no file attached yet"},
        {"escuta.sem_forma_onda", "No waveform cached for this item"},
        {"escuta.tocar", "Play"},
        {"escuta.adicionar_marcador", "Add Marker"},
        {"escuta.vault_offline", "Vault offline  -  playback disabled. The file is at: {local}"},
        {"escuta.vetorscopio", "VECTORSCOPE"},
        {"escuta.vu", "VU / PEAK"},
        {"ficha_grupos.3d_file.arquivo", "File"},
        {"ficha_grupos.3d_file.especificacoes", "Specifications"},
        {"ficha_grupos.cassete.abrangencia", "Scope"},
        {"ficha_grupos.cassete.conteudo", "Content"},
        {"ficha_grupos.cassete.estado_fisico", "Physical condition"},
        {"ficha_grupos.cassete.reproducao", "Playback"},
        {"ficha_grupos.cassete.suporte", "Media"},
        {"ficha_grupos.cd.captura", "Capture"},
        {"ficha_grupos.cd.conteudo", "Content"},
        {"ficha_grupos.cd.estado_fisico", "Physical condition"},
        {"ficha_grupos.cd.suporte", "Media"},
        {"ficha_grupos.dat.conteudo", "Content"},
        {"ficha_grupos.dat.estado_fisico", "Physical condition"},
        {"ficha_grupos.dat.reproducao", "Playback"},
        {"ficha_grupos.dat.suporte", "Media"},
        {"ficha_grupos.digital_audio.arquivo", "File"},
        {"ficha_grupos.digital_audio.conteudo", "Content"},
        {"ficha_grupos.digital_audio.origem_digital", "Digital origin"},
        {"ficha_grupos.digital_video.arquivo", "File"},
        {"ficha_grupos.digital_video.captura", "Capture"},
        {"ficha_grupos.digital_video.conteudo", "Content"},
        {"ficha_grupos.digital_video.especificacoes", "Specifications"},
        {"ficha_grupos.documento.estado", "Condition"},
        {"ficha_grupos.documento.identificacao", "Identification"},
        {"ficha_grupos.documento.leitura_tecnica", "Technical reading"},
        {"ficha_grupos.field_recording.ambiente", "Environment"},
        {"ficha_grupos.field_recording.captura", "Capture"},
        {"ficha_grupos.field_recording.conteudo", "Content"},
        {"ficha_grupos.filme.conteudo", "Content"},
        {"ficha_grupos.filme.digitalizacao_proveniencia_tecnica_11_5", "Digitization (technical provenance, Section 11.5)"},
        {"ficha_grupos.filme.estado_fisico", "Physical condition"},
        {"ficha_grupos.filme.suporte", "Media"},
        {"ficha_grupos.fita_rolo.abrangencia", "Scope"},
        {"ficha_grupos.fita_rolo.conteudo", "Content"},
        {"ficha_grupos.fita_rolo.estado_fisico", "Physical condition"},
        {"ficha_grupos.fita_rolo.reproducao", "Playback"},
        {"ficha_grupos.fita_rolo.suporte", "Media"},
        {"ficha_grupos.foto.captura", "Capture"},
        {"ficha_grupos.foto.conteudo", "Content"},
        {"ficha_grupos.foto.direitos", "Rights"},
        {"ficha_grupos.foto.estado_fisico", "Physical condition"},
        {"ficha_grupos.minidisc.conteudo", "Content"},
        {"ficha_grupos.minidisc.estado_fisico", "Physical condition"},
        {"ficha_grupos.minidisc.reproducao", "Playback"},
        {"ficha_grupos.minidisc.suporte", "Media"},
        {"ficha_grupos.negativo.conteudo", "Content"},
        {"ficha_grupos.negativo.digitalizacao", "Digitization"},
        {"ficha_grupos.negativo.estado_fisico", "Physical condition"},
        {"ficha_grupos.negativo.suporte", "Media"},
        {"ficha_grupos.sample.classificacao", "Classification"},
        {"ficha_grupos.sample.direitos_e_origem", "Rights and origin"},
        {"ficha_grupos.sessao.identificacao", "Identification"},
        {"ficha_grupos.slide.conteudo", "Content"},
        {"ficha_grupos.slide.digitalizacao", "Digitization"},
        {"ficha_grupos.slide.estado_fisico", "Physical condition"},
        {"ficha_grupos.slide.suporte", "Media"},
        {"ficha_grupos.sound_effects.classificacao", "Classification"},
        {"ficha_grupos.sound_effects.direitos", "Rights"},
        {"ficha_grupos.betacam.media", "Media"},
        {"ficha_grupos.betacam.digitization", "Digitization"},
        {"ficha_grupos.betacam.physical_condition", "Physical condition"},
        {"ficha_grupos.betacam.content", "Content"},
        {"ficha_grupos.betamax.media", "Media"},
        {"ficha_grupos.betamax.digitization", "Digitization"},
        {"ficha_grupos.betamax.physical_condition", "Physical condition"},
        {"ficha_grupos.betamax.content", "Content"},
        {"ficha_grupos.dvd.media", "Media"},
        {"ficha_grupos.dvd.technical", "Technical"},
        {"ficha_grupos.dvd.physical_condition", "Physical condition"},
        {"ficha_grupos.dvd.content", "Content"},
        {"ficha_grupos.umatic.media", "Media"},
        {"ficha_grupos.umatic.digitization", "Digitization"},
        {"ficha_grupos.umatic.physical_condition", "Physical condition"},
        {"ficha_grupos.umatic.content", "Content"},
        {"ficha_grupos.vhs.media", "Media"},
        {"ficha_grupos.vhs.digitization", "Digitization"},
        {"ficha_grupos.vhs.physical_condition", "Physical condition"},
        {"ficha_grupos.vhs.content", "Content"},
        {"ficha_grupos.video.conteudo", "Content"},
        {"ficha_grupos.video.digitalizacao_proveniencia_tecnica_11_5", "Digitization (technical provenance, Section 11.5)"},
        {"ficha_grupos.video.estado_fisico", "Physical condition"},
        {"ficha_grupos.video.suporte", "Media"},
        {"ficha_grupos.vinil.conteudo", "Content"},
        {"ficha_grupos.vinil.estado_fisico", "Physical condition"},
        {"ficha_grupos.vinil.reproducao", "Playback"},
        {"ficha_grupos.vinil.suporte", "Media"},
        {"ficha_tipos.cassete", "Cassette"},
        {"ficha_tipos.cd", "CD"},
        {"ficha_tipos.dat", "DAT"},
        {"ficha_tipos.digital_audio", "Digital audio"},
        {"ficha_tipos.digital_video", "Digital video"},
        {"ficha_tipos.documento", "Document"},
        {"ficha_tipos.field_recording", "Field recording"},
        {"ficha_tipos.filme", "Film (16 mm / Super 8 / 8 mm)"},
        {"ficha_tipos.fita_rolo", "Reel tape"},
        {"ficha_tipos.cover_art", "Cover Art"},
        {"ficha_tipos.foto", "Photo"},
        {"ficha_tipos.minidisc", "MiniDisc"},
        {"ficha_tipos.negativo", "Photographic negative"},
        {"ficha_tipos.release", "Release"},
        {"ficha_tipos.sample", "Sample"},
        {"ficha_tipos.slide", "Slide"},
        {"ficha_tipos.sound_effects", "Sound effect"},
        {"ficha_tipos.video", "Digitized analog video"},
        {"ficha_tipos.vinil", "Vinyl"},
        {"filtros.limpar", "Clear filters"},
        {"filtros.nome_colecao_mensagem", "Collection name:"},
        {"filtros.nome_colecao_titulo", "Save smart collection"},
        {"filtros.origem_analogico", "Analog"},
        {"filtros.origem_digital", "Digital"},
        {"filtros.salvar_colecao", "Save current search..."},
        {"filtros.secao_colecoes", "Smart collections"},
        {"filtros.secao_colecoes_embutidas", "Smart collections"},
        {"filtros.secao_vaults", "Vaults"},
        {"filtros.secao_collection", "Content"},
        {"filtros.secao_content", "Content"},
        {"filtros.secao_extensao", "File type"},
        {"filtros.secao_origem", "Origin"},
        {"grade.adicionar_material", "Add material..."},
        {"grade.agrupar_automatico", "Group: type"},
        {"grade.agrupar_por_ano", "Group: year"},
        {"grade.nao_classificado", "Unknown"},
        {"grade.sem_ano", "No year"},
        {"grade.tamanho_grande", "L"},
        {"grade.tamanho_lista", "List"},
        {"grade.tamanho_medio", "M"},
        {"grade.tamanho_pequeno", "S"},
        {"grade.modo_lista", "List"},
        {"grade.modo_grade", "Grid"},
        {"guia.backup_corpo", "Click Backup and pick the destination drive. Matriz writes everything in the layout you built."},
        {"guia.backup_titulo", "Ready to write the backup"},
        {"guia.classificar_corpo", "Select several (click one, then Shift+click another) and use \"Batch edit\" to give them a category and details all at once."},
        {"guia.classificar_titulo", "{n} file(s) still have no category"},
        {"guia.mostrar", "Tip"},
        {"guia.ocultar", "Got it"},
        {"guia.organizar_corpo", "Make folders with \"+\" in BACKUP TREE, and drag folders or files from SOURCE into them."},
        {"guia.organizar_titulo", "Now lay out the backup"},
        {"guia.vazio_corpo", "A whole drive, a folder, or loose files. Nothing is moved or deleted: Matriz copies them into the project and builds the view."},
        {"guia.vazio_titulo", "Start by dragging your files here"},
        {"hierarquia.acrescentar", "+ add level..."},
        {"hierarquia.nivel_ano", "Year"},
        {"hierarquia.nivel_artista", "Artist"},
        {"hierarquia.nivel_origem", "Origin"},
        {"hierarquia.nivel_pasta_manual", "Folders I made by hand"},
        {"hierarquia.nivel_projeto", "Project"},
        {"hierarquia.nivel_tipo_arquivo", "File type"},
        {"hierarquia.nivel_tipo_midia", "Media type"},
        {"hierarquia.titulo", "Backup folder structure"},
        {"ingest.cancelado", "Cancelled  -  {feito} of {total} processed. What was done is saved."},
        {"ingest.cancelando", "Cancelling..."},
        {"ingest.cancelar", "Cancel"},
        {"ingest.erro_extensao_desconhecida", "unrecognized extension (media type could not be inferred)"},
        {"ingest.ja_em_andamento", "A batch is already being added. Wait for it to finish before starting another."},
        {"ingest.progresso", "Adding... {feito}/{total}"},
        {"ingest.resumo_duplicatas", "{n} already known"},
        {"ingest.resumo_erros", "{n} failed"},
        {"ingest.resumo_novos", "{n} new"},
        {"ingest.selecionar_tipo_confirmar", "Add"},
        {"ingest.selecionar_tipo_corpo", "{n} file(s) selected. What's the source media type for this batch?"},
        {"ingest.selecionar_tipo_titulo", "Media type"},
        {"ingest.titulo", "Ingest"},
        {"janela_principal.titulo", "BKR Matriz"},
        {"menu.ajuda", "Help"},
        {"menu.arquivo", "File"},
        {"menu.arquivo_abrir_projeto", "Open project..."},
        {"menu.arquivo_fechar_projeto", "Close project"},
        {"menu.arquivo_ingerir_arquivos", "Add files..."},
        {"menu.arquivo_novo_projeto", "New project..."},
        {"menu.arquivo_sair", "Quit"},
        {"menu.exibir", "View"},
        {"menu.exibir_tema_bkr_dark", "BKR Dark"},
        {"menu.exibir_tema_system_crt", "System CRT"},
        {"menu.preferencias", "Preferences"},
        {"menu.preferencias_idioma_ingles", "English"},
        {"menu.preferencias_idioma_portugues", "Portuguese"},
        {"menu.projeto", "Project"},
        {"menu.projeto_configuracoes", "Project settings..."},
        {"metadados.bit_depth", "Bit depth"},
        {"metadados.canais", "Channels"},
        {"metadados.codec", "Codec"},
        {"metadados.dimensoes", "Dimensions"},
        {"metadados.duracao", "Duration"},
        {"metadados.editaveis", "Backup metadata"},
        {"metadados.editaveis_ajuda", "what you fill in"},
        {"metadados.fps", "Frames per second"},
        {"metadados.lossy", "Already lossy-compressed"},
        {"metadados.mais", "+ {n} more fields"},
        {"metadados.sample_rate", "Sample rate"},
        {"metadados.somente_leitura", "read only"},
        {"metadados.tamanho", "File size"},
        {"metadados.titulo", "Original metadata"},
        {"metadados.tamanho_arquivo", "File size"},
        {"metadados.criado_em", "Created"},
        {"metadados.modificado_em", "Modified"},
        {"metadados.extensao", "Extension"},
        {"metadados.vazio", "This file carried no readable technical metadata."},
        {"metricas.bit_depth", "Bit depth"},
        {"metricas.bitrate", "Bitrate"},
        {"metricas.canais", "Channels"},
        {"metricas.codec", "Codec"},
        {"metricas.dimensao", "Dimensions"},
        {"metricas.duracao", "Duration"},
        {"metricas.espaco_cor", "Color space"},
        {"metricas.formato", "Format"},
        {"metricas.fps", "FPS"},
        {"metricas.itens", "Items"},
        {"metricas.lra", "LRA"},
        {"metricas.lufs_i", "LUFS-I"},
        {"metricas.paginas", "Pages"},
        {"metricas.pico", "Peak"},
        {"metricas.profundidade", "Depth"},
        {"metricas.resolucao", "Resolution"},
        {"metricas.resumo_grade", "In the grid"},
        {"metricas.sample_rate", "Sample rate"},
        {"metricas.sem_arquivo", "No file yet"},
        {"metricas.tamanho", "Size"},
        {"mosaico.buscar_placeholder", "Search"},
        {"mosaico.contagem_itens", "{n} items"},
        {"mosaico.estado_alerta", "Alert"},
        {"mosaico.estado_capturado", "Captured"},
        {"mosaico.estado_duplicata", "Already known"},
        {"mosaico.estado_aprovado", "Approved"},
        {"mosaico.estado_arquivado", "Archived"},
        {"mosaico.estado_catalogado", "Cataloged"},
        {"mosaico.estado_em_analise", "In analysis"},
        {"mosaico.estado_novo", "New"},
        {"mosaico.estado_revisado", "Reviewed"},
        {"mosaico.estado_nao_digitalizado", "Not digitized"},
        {"mosaico.estado_publicado", "Published"},
        {"mosaico.estado_qc_ok", "QC ok"},
        {"mosaico.filtrar_estado", "Status"},
        {"mosaico.filtrar_tipo", "Media type"},
        {"mosaico.ordenar", "Sort by"},
        {"mosaico.ordenar_atualizado", "Recently updated"},
        {"mosaico.ordenar_codigo", "Code"},
        {"mosaico.ordenar_estado", "Status"},
        {"mosaico.ordenar_titulo", "Title"},
        {"mosaico.solte_para_ingerir", "Drop to add"},
        {"mosaico.todos", "All"},
        {"mosaico.vazio", "No items in this project yet. Drag files here or use File > Add material..."},
        {"nav.backup", "BACKUP"},
        {"nav.catalog", "CATALOG"},
        {"nav.home", "HOME"},
        {"nav.preservation", "PRESERVATION"},
        {"navegador.abrir", "Browse files..."},
        {"navegador.adicionar", "ADD TO BACKUP"},
        {"navegador.adicionar_n", "ADD {n} TO BACKUP"},
        {"navegador.buscar", "Search this folder and below"},
        {"navegador.filtro_audio", "Audio only"},
        {"navegador.filtro_documento", "Documents only"},
        {"navegador.filtro_imagem", "Images only"},
        {"navegador.filtro_todos", "All files"},
        {"navegador.filtro_video", "Video only"},
        {"navegador.manter_estrutura", "Keep folder structure"},
        {"navegador.ordem_data", "Sort: date"},
        {"navegador.ordem_nome", "Sort: name"},
        {"navegador.ordem_tamanho", "Sort: size"},
        {"navegador.ordem_tipo", "Sort: type"},
        {"navegador.previa_pasta", "Folder"},
        {"navegador.previa_vazia", "Select something to preview it."},
        {"navegador.resumo_selecao", "{n} files, {tamanho}"},
        {"navegador.secao_favoritos", "FAVORITES"},
        {"navegador.secao_recentes", "RECENT"},
        {"navegador.secao_volumes", "VOLUMES"},
        {"navegador.selecao_vazia", "Nothing selected."},
        {"navegador.titulo", "Add to backup"},
        {"navegador.vazio", "Nothing here."},
        {"navegador.visao_colunas", "Columns"},
        {"navegador.visao_icones", "Icons"},
        {"navegador.visao_lista", "List"},
        {"painel_inconsistencias.titulo", "Needs attention"},
        {"painel_inconsistencias.vazio", "Nothing pending here  -  everything is consistent."},
        {"preserv.checksum_problems", "Checksum problems"},
        {"preserv.health_critical", "CRITICAL"},
        {"preserv.health_good", "GOOD"},
        {"preserv.health_warning", "WARNING"},
        {"preserv.incomplete", "Incomplete"},
        {"preserv.needs_backup", "Needs backup"},
        {"preserv.needs_review", "Needs review"},
        {"preserv.single_copy", "Single copy (vulnerable)"},
        {"preserv.titulo", "Archive Health"},
        {"preserv.total_assets", "Total assets"},
        {"preserv.verified", "Verified"},
        {"preserv.view_in_catalog", "View in catalog"},
        {"preview.dimensoes", "Dimensions"},
        {"preview.duracao", "Duration"},
        {"preview.pausar", "Pause"},
        {"preview.sample_rate", "Sample rate"},
        {"preview.sem_arquivo", "No file attached to this item yet."},
        {"preview.sem_visualizacao", "No preview available for this file type."},
        {"preview.tocar", "Play"},
        {"preview.video_sem_player", "Video playback isn't implemented yet  -  showing the keyframe and technical data."},
        {"selecao.contagem", "{n} files selected"},
        {"vault.backup_planejado", "{n} item(s) added to this drive's backup plan  -  {total} planned in total"},
        {"vault.backup_planejado_falhou", "Could not add these items to the backup plan"},
        {"vault.reconciliando", "Checking what changed on the reconnected drive..."},
        {"selecao.contagem_um", "1 file selected"},
        {"selecao.editar_lote", "Batch edit"},
        {"selecao.limpar", "Clear selection"},
        {"selecao.selecionar_todos", "Select all"},
        {"home.atencao_titulo", "NEEDS ATTENTION"},
        {"home.backup_desc", "Copy verified assets to a safe destination with checksum verification."},
        {"home.backup_titulo", "BACKUP"},
        {"home.catalog_desc", "Browse, search and edit metadata for assets already in the archive."},
        {"home.catalog_titulo", "GRID"},
        {"home.ingest_desc", "Scan a folder, auto-classify files, review exceptions, and register assets  -  source files stay untouched."},
        {"home.ingest_titulo", "INGEST MEDIA"},
        {"home.preservacao_desc", "View statistics, metrics, and collection analytics."},
        {"home.preservacao_titulo", "ANALYTICS"},
        {"home.subtitulo", "What would you like to do?"},
        {"home.titulo", "Home"},
        {"home.total_assets", "{0} assets in archive"},
        {"home.total_assets_vazio", "No assets yet  -  start by ingesting media."},
        {"ingest.btn_importar", "IMPORT"},
        {"ingest.btn_proximo", "NEXT"},
        {"ingest.btn_voltar", "BACK"},
        {"ingest.cancelar", "Cancel"},
        {"ingest.concluido_assets", "{0} assets added to the archive"},
        {"ingest.concluido_titulo", "Import Complete"},
        {"ingest.concluido_ver_acervo", "VIEW ARCHIVE"},
        {"ingest.concluido_ver_novos", "VIEW NEW ASSETS"},
        {"ingest.concluido_ver_todos", "VIEW ALL ASSETS"},
        {"ingest.concluido_ver_problemas", "REVIEW ISSUES"},
        {"ingest.concluido_voltar_home", "RETURN HOME"},
        {"ingest.descobre_analisando", "Analyzing {0} of {1} files..."},
        {"ingest.descobre_listando", "Scanning folder..."},
        {"ingest.descobre_titulo", "Discovering & analyzing files"},
        {"ingest.importando_titulo", "Importing assets"},
        {"ingest.importando_progresso", "Writing {0} of {1}..."},
        {"ingest.nenhum_arquivo", "No supported files found in this folder."},
        {"ingest.resumo_categorias", "{0} audio | {1} video | {2} images | {3} documents | {4} other"},
        {"ingest.resumo_duplicatas", "{0} already in archive (duplicates)"},
        {"ingest.resumo_erros", "{0} could not be analyzed"},
        {"ingest.resumo_novos", "{0} new files ready to import"},
        {"ingest.review_aplicar_todos", "Apply to all similar"},
        {"ingest.review_nenhum", "Nothing needs review  -  all files were auto-classified."},
        {"ingest.review_titulo", "Review exceptions"},
        {"ingest.source_arrastar", "Drag a folder here or click to browse"},
        {"ingest.source_titulo", "Choose source"},
        {"ingest.step_concluido", "Done"},
        {"ingest.step_descobre", "Discover"},
        {"ingest.step_importar", "Import"},
        {"ingest.step_review", "Review"},
        {"ingest.step_source", "Source"},
        {"ingest.step_verificar", "Verify"},
        {"ingest.titulo", "Ingest Media"},
        {"ingest.verificando_titulo", "Verifying import"},
        {"ingest.verificando_progresso", "Checking {0} of {1}..."},
        {"tela_inicial.botao_abrir", "Open an existing project..."},
        {"tela_inicial.cartao_archive_descricao", "Photos, video, documents, tape, masters - a single project or artwork unit you want to organize and preserve."},
        {"tela_inicial.cartao_archive_publico", "e.g. albums, films, raw footage, artwork collections"},
        {"tela_inicial.cartao_archive_titulo", "COLLECTION"},
        {"tela_inicial.cartao_catalog_descricao", "Group of Collections - navigate multiple collections and export consolidated backups."},
        {"tela_inicial.cartao_catalog_publico", "e.g. artist catalog, studio discography, multi-project hub"},
        {"tela_inicial.cartao_catalog_titulo", "CATALOG"},
        {"tela_inicial.recente_modo_archive", "Collection"},
        {"tela_inicial.recente_modo_catalog", "Catalog"},
        {"tela_inicial.recentes_titulo", "Pick up where you left off"},
        {"tela_inicial.subtitulo", "Pick one and drag your files in. You can always change your mind later by creating another project."},
        {"tela_inicial.titulo", "What do you want to organize?"},
        {"timeline.marcador", "+ Marker"},
        {"timeline.marcador_apagar", "Delete marker"},
        {"timeline.marcador_dica", "What does this mark?"},
        {"timeline.marcador_editar", "Edit text"},
        {"timeline.sem_onda", "No waveform for this file."},
        {"timeline.timecode", "Timecode"},
        {"timeline.zoom_tudo", "Zoom out"},
        {"transporte.fim", ">>|"},
        {"transporte.inicio", "|<<"},
        {"transporte.jog", "JOG"},
        {"transporte.play", "PLAY"},
        {"transporte.shuttle", "SHUTTLE"},
        {"transporte.stop", "STOP"},
    };
    return strings;
}

} // namespace matriz::i18n
